klee: klee::ImmutableTree< K, V, KOV, CMP >::iterator Class Reference
klee::ImmutableTree< K, V, KOV, CMP >::iterator Class Reference
#include <ImmutableTree.h>
Public Member Functions
iterator (Node *_root, bool atBeginning)
iterator (const iterator &i)
~iterator ()
iterator & operator= (const iterator &b)
const value_type & operator* ()
const value_type * operator-> ()
bool operator== (const iterator &b)
bool operator!= (const iterator &b)
iterator & operator-- ()
iterator & operator++ ()
Private Attributes
Node * root
FixedStack< Node * > stack
Friends
class ImmutableTree< K, V, KOV, CMP >
Detailed Description
template<class K, class V, class KOV, class CMP>
class klee::ImmutableTree< K, V, KOV, CMP >::iterator
Definition at line 140 of file ImmutableTree.h.
Constructor & Destructor Documentation
iterator() [1/2]
template<class K , class V , class KOV , class CMP > klee::ImmutableTree< K, V, KOV, CMP >::iterator::iterator (Node * _root, bool atBeginning) inline
Definition at line 147 of file ImmutableTree.h.
References klee::ImmutableTree< K, V, KOV, CMP >::Node::isTerminator(), and klee::FixedStack< T >::push_back().
iterator() [2/2]
template<class K , class V , class KOV , class CMP > klee::ImmutableTree< K, V, KOV, CMP >::iterator::iterator (const iterator & i) inline
Definition at line 154 of file ImmutableTree.h.
~iterator()
template<class K , class V , class KOV , class CMP > klee::ImmutableTree< K, V, KOV, CMP >::iterator::~iterator () inline
Definition at line 157 of file ImmutableTree.h.
References klee::ImmutableTree< K, V, KOV, CMP >::Node::decref().
Member Function Documentation
operator!=()
template<class K , class V , class KOV , class CMP > bool klee::ImmutableTree< K, V, KOV, CMP >::iterator::operator!= (const iterator & b) inline
Definition at line 182 of file ImmutableTree.h.
References klee::ImmutableTree< K, V, KOV, CMP >::iterator::stack.
operator*()
template<class K , class V , class KOV , class CMP > const value_type & klee::ImmutableTree< K, V, KOV, CMP >::iterator::operator* () inline
Definition at line 169 of file ImmutableTree.h.
References klee::FixedStack< T >::back(), and klee::ImmutableTree< K, V, KOV, CMP >::Node::value.
operator++()
template<class K , class V , class KOV , class CMP > iterator & klee::ImmutableTree< K, V, KOV, CMP >::iterator::operator++ () inline
Definition at line 213 of file ImmutableTree.h.
References klee::FixedStack< T >::back(), klee::FixedStack< T >::empty(), klee::ImmutableTree< K, V, KOV, CMP >::Node::isTerminator(), klee::ImmutableTree< K, V, KOV, CMP >::Node::left, klee::FixedStack< T >::pop_back(), klee::FixedStack< T >::push_back(), and klee::ImmutableTree< K, V, KOV, CMP >::Node::right.
operator--()
template<class K , class V , class KOV , class CMP > iterator & klee::ImmutableTree< K, V, KOV, CMP >::iterator::operator-- () inline
Definition at line 186 of file ImmutableTree.h.
References klee::FixedStack< T >::back(), klee::FixedStack< T >::empty(), klee::ImmutableTree< K, V, KOV, CMP >::Node::isTerminator(), klee::ImmutableTree< K, V, KOV, CMP >::Node::left, klee::FixedStack< T >::pop_back(), klee::FixedStack< T >::push_back(), and klee::ImmutableTree< K, V, KOV, CMP >::Node::right.
operator->()
template<class K , class V , class KOV , class CMP > const value_type * klee::ImmutableTree< K, V, KOV, CMP >::iterator::operator-> () inline
Definition at line 174 of file ImmutableTree.h.
References klee::FixedStack< T >::back(), and klee::ImmutableTree< K, V, KOV, CMP >::Node::value.
operator=()
template<class K , class V , class KOV , class CMP > iterator & klee::ImmutableTree< K, V, KOV, CMP >::iterator::operator= (const iterator & b) inline
Definition at line 161 of file ImmutableTree.h.
References klee::ImmutableTree< K, V, KOV, CMP >::Node::decref(), klee::ImmutableTree< K, V, KOV, CMP >::Node::incref(), klee::ImmutableTree< K, V, KOV, CMP >::iterator::root, and klee::ImmutableTree< K, V, KOV, CMP >::iterator::stack.
operator==()
template<class K , class V , class KOV , class CMP > bool klee::ImmutableTree< K, V, KOV, CMP >::iterator::operator== (const iterator & b) inline
Definition at line 179 of file ImmutableTree.h.
References klee::ImmutableTree< K, V, KOV, CMP >::iterator::stack.
Friends And Related Function Documentation
ImmutableTree< K, V, KOV, CMP >
template<class K , class V , class KOV , class CMP > friend class ImmutableTree< K, V, KOV, CMP > friend
Definition at line 136 of file ImmutableTree.h.
Member Data Documentation
root
template<class K , class V , class KOV , class CMP > Node* klee::ImmutableTree< K, V, KOV, CMP >::iterator::root private
Definition at line 143 of file ImmutableTree.h.
Referenced by klee::ImmutableTree< K, V, KOV, CMP >::iterator::operator=().
stack
template<class K , class V , class KOV , class CMP > FixedStack<Node*> klee::ImmutableTree< K, V, KOV, CMP >::iterator::stack private
Definition at line 144 of file ImmutableTree.h.
Referenced by klee::ImmutableTree< K, V, KOV, CMP >::lower_bound(), klee::ImmutableTree< K, V, KOV, CMP >::iterator::operator!=(), klee::ImmutableTree< K, V, KOV, CMP >::iterator::operator=(), and klee::ImmutableTree< K, V, KOV, CMP >::iterator::operator==().
The documentation for this class was generated from the following file:
/Users/cristic/klee/include/klee/ADT/ImmutableTree.h