klee: klee::BitArray Class Reference
klee::BitArray Class Reference
#include <BitArray.h>
Public Member Functions
BitArray (unsigned size, bool value=false)
BitArray (const BitArray &b, unsigned size)
~BitArray ()
bool get (unsigned idx)
void set (unsigned idx)
void unset (unsigned idx)
void set (unsigned idx, bool value)
Static Protected Member Functions
static uint32_t length (unsigned size)
Private Attributes
uint32_t * bits
Detailed Description
Definition at line 18 of file BitArray.h.
Constructor & Destructor Documentation
BitArray() [1/2]
klee::BitArray::BitArray (unsigned size, bool value = false) inline
Definition at line 26 of file BitArray.h.
References bits, and length().
BitArray() [2/2]
klee::BitArray::BitArray (const BitArray & b, unsigned size) inline
Definition at line 29 of file BitArray.h.
References bits, and length().
~BitArray()
klee::BitArray::~BitArray () inline
Definition at line 32 of file BitArray.h.
References bits.
Member Function Documentation
get()
bool klee::BitArray::get (unsigned idx) inline
Definition at line 34 of file BitArray.h.
References bits.
Referenced by klee::ExprOptimizer::getSelectOptExpr(), klee::ObjectState::isByteConcrete(), klee::ObjectState::isByteUnflushed(), and klee::ExprRewriter::rewrite().
length()
static uint32_t klee::BitArray::length (unsigned size) inline static protected
Definition at line 23 of file BitArray.h.
Referenced by BitArray().
set() [1/2]
void klee::BitArray::set (unsigned idx) inline
Definition at line 35 of file BitArray.h.
References bits.
Referenced by klee::ExprOptimizer::getSelectOptExpr(), klee::ObjectState::markByteConcrete(), klee::ObjectState::markByteUnflushed(), and klee::ExprRewriter::rewrite().
set() [2/2]
void klee::BitArray::set (unsigned idx, bool value) inline
Definition at line 37 of file BitArray.h.
References set(), and unset().
Referenced by set().
unset()
void klee::BitArray::unset (unsigned idx) inline
Definition at line 36 of file BitArray.h.
References bits.
Referenced by klee::ObjectState::flushRangeForRead(), klee::ObjectState::flushRangeForWrite(), klee::ExprOptimizer::getSelectOptExpr(), klee::ObjectState::markByteFlushed(), klee::ObjectState::markByteSymbolic(), and set().
Member Data Documentation
bits
uint32_t* klee::BitArray::bits private
Definition at line 20 of file BitArray.h.
Referenced by BitArray(), get(), set(), unset(), and ~BitArray().
The documentation for this class was generated from the following file:
/Users/cristic/klee/include/klee/ADT/BitArray.h