klee: klee::NotExpr Class Reference
klee::NotExpr Class Reference
#include <Expr.h>
Public Member Functions
Width getWidth () const
Kind getKind () const
unsigned getNumKids () const
ref< Expr > getKid (unsigned i) const
virtual ref< Expr > rebuild (ref< Expr > kids[]) const
virtual unsigned computeHash ()
Public Member Functions inherited from klee::Expr
Expr ()
virtual ~Expr ()
virtual Kind getKind () const =0
virtual Width getWidth () const =0
virtual unsigned getNumKids () const =0
virtual ref< Expr > getKid (unsigned i) const =0
virtual void print (llvm::raw_ostream &os) const
void dump () const
dump - Print the expression to stderr.
virtual unsigned hash () const
Returns the pre-computed hash of the current expression.
virtual unsigned computeHash ()
int compare (const Expr &b) const
virtual ref< Expr > rebuild (ref< Expr > kids[]) const =0
bool isZero () const
isZero - Is this a constant zero.
bool isTrue () const
isTrue - Is this the true expression.
bool isFalse () const
isFalse - Is this the false expression.
Static Public Member Functions
static ref< Expr > alloc (const ref< Expr > &e)
static ref< Expr > create (const ref< Expr > &e)
static bool classof (const Expr *E)
static bool classof (const NotExpr *)
Static Public Member Functions inherited from klee::NonConstantExpr
static bool classof (const Expr *E)
static bool classof (const NonConstantExpr *)
Static Public Member Functions inherited from klee::Expr
static void printKind (llvm::raw_ostream &os, Kind k)
static void printWidth (llvm::raw_ostream &os, Expr::Width w)
static unsigned getMinBytesForWidth (Width w)
returns the smallest number of bytes in which the given width fits
static ref< Expr > createSExtToPointerWidth (ref< Expr > e)
static ref< Expr > createZExtToPointerWidth (ref< Expr > e)
static ref< Expr > createImplies (ref< Expr > hyp, ref< Expr > conc)
static ref< Expr > createIsZero (ref< Expr > e)
static ref< Expr > createTempRead (const Array *array, Expr::Width w)
static ref< ConstantExpr > createPointer (uint64_t v)
static ref< Expr > createFromKind (Kind k, std::vector< CreateArg > args)
static bool isValidKidWidth (unsigned kid, Width w)
static bool needsResultType ()
static bool classof (const Expr *)
Public Attributes
ref< Expr > expr
Public Attributes inherited from klee::Expr
class ReferenceCounter _refCount
Required by klee::ref-managed objects.
Static Public Attributes
static const Kind kind = Not
static const unsigned numKids = 1
Static Public Attributes inherited from klee::Expr
static unsigned count = 0
static const unsigned MAGIC_HASH_CONSTANT = 39
static const Width InvalidWidth = 0
static const Width Bool = 1
static const Width Int8 = 8
static const Width Int16 = 16
static const Width Int32 = 32
static const Width Int64 = 64
static const Width Fl80 = 80
Protected Member Functions
virtual int compareContents (const Expr &b) const
virtual int compareContents (const Expr &b) const =0
Private Member Functions
NotExpr (const ref< Expr > &e)
Additional Inherited Members
Public Types inherited from klee::Expr
enum Kind {
InvalidKind = -1 , Constant = 0 , NotOptimized , Read =NotOptimized+2 ,
Select , Concat , Extract , ZExt ,
SExt , Not , Add , Sub ,
Mul , UDiv , SDiv , URem ,
SRem , And , Or , Xor ,
Shl , LShr , AShr , Eq ,
Ne , Ult , Ule , Ugt ,
Uge , Slt , Sle , Sgt ,
Sge , LastKind =Sge , CastKindFirst =ZExt , CastKindLast =SExt ,
BinaryKindFirst =Add , BinaryKindLast =Sge , CmpKindFirst =Eq , CmpKindLast =Sge
}
typedef unsigned Width
The type of an expression is simply its width, in bits.
Protected Attributes inherited from klee::Expr
unsigned hashValue
Detailed Description
Bitwise Not
Definition at line 793 of file Expr.h.
Constructor & Destructor Documentation
NotExpr()
klee::NotExpr::NotExpr (const ref< Expr > & e) inline private
Definition at line 828 of file Expr.h.
Referenced by alloc().
Member Function Documentation
alloc()
static ref< Expr > klee::NotExpr::alloc (const ref< Expr > & e) inline static
Definition at line 801 of file Expr.h.
References klee::Expr::computeHash(), and NotExpr().
Referenced by create(), and klee::ExprRewriter::rewrite().
classof() [1/2]
static bool klee::NotExpr::classof (const Expr * E) inline static
Definition at line 822 of file Expr.h.
References klee::Expr::getKind(), and klee::Expr::Not.
classof() [2/2]
static bool klee::NotExpr::classof (const NotExpr *) inline static
Definition at line 825 of file Expr.h.
compareContents()
virtual int klee::NotExpr::compareContents (const Expr & b) const inline protected virtual
Compares b to this Expr and determines how they are ordered (ignoring their kid expressions - i.e. those returned by getKid()).
Typically this requires comparing internal attributes of the Expr.
Implementations can assume that b and this are of the same kind.
This method effectively defines a partial order over Expr of the same kind (partial because kid Expr are not compared).
This method should not be called directly. Instead compare() should be used.
Parameters
[in] b Expr to compare this to.
Returns
One of the following values:
-1 if this is < b ignoring kid expressions.
1 if this is > b ignoring kid expressions.
0 if this and b are not ordered.
< and > are binary relations that express the partial order.
Implements klee::Expr.
Definition at line 831 of file Expr.h.
computeHash()
unsigned NotExpr::computeHash () virtual
(Re)computes the hash of the current expression. Returns the hash value.
Reimplemented from klee::Expr.
Definition at line 225 of file Expr.cpp.
References expr, klee::Expr::hash(), klee::Expr::hashValue, klee::Expr::MAGIC_HASH_CONSTANT, and klee::Expr::Not.
create()
ref< Expr > NotExpr::create (const ref< Expr > & e) static
Definition at line 705 of file Expr.cpp.
References alloc(), and klee::Expr::Not.
Referenced by rebuild().
getKid()
ref< Expr > klee::NotExpr::getKid (unsigned i) const inline virtual
Implements klee::Expr.
Definition at line 813 of file Expr.h.
References expr.
getKind()
Kind klee::NotExpr::getKind () const inline virtual
Implements klee::Expr.
Definition at line 810 of file Expr.h.
References klee::Expr::Not.
getNumKids()
unsigned klee::NotExpr::getNumKids () const inline virtual
Implements klee::Expr.
Definition at line 812 of file Expr.h.
References numKids.
getWidth()
Width klee::NotExpr::getWidth () const inline virtual
Implements klee::Expr.
Definition at line 809 of file Expr.h.
References expr, and klee::Expr::getWidth().
rebuild()
virtual ref< Expr > klee::NotExpr::rebuild (ref< Expr > kids[]) const inline virtual
Implements klee::Expr.
Definition at line 815 of file Expr.h.
References create().
Member Data Documentation
expr
ref<Expr> klee::NotExpr::expr
Definition at line 798 of file Expr.h.
Referenced by computeHash(), getKid(), and getWidth().
kind
const Kind klee::NotExpr::kind = Not static
Definition at line 795 of file Expr.h.
numKids
const unsigned klee::NotExpr::numKids = 1 static
Definition at line 796 of file Expr.h.
Referenced by getNumKids().
The documentation for this class was generated from the following files:
/Users/cristic/klee/include/klee/Expr/Expr.h
/Users/cristic/klee/lib/Expr/Expr.cpp