klee: klee::Context Class Reference
klee::Context Class Reference
Context - Helper class for storing global information about a KLEE run.
#include <Context.h>
Public Member Functions
Context ()
bool isLittleEndian () const
Expr::Width getPointerWidth () const
Returns width of the pointer in bits.
Static Public Member Functions
static void initialize (bool IsLittleEndian, Expr::Width PointerWidth)
initialize - Construct the global Context instance.
static const Context & get ()
get - Return the global singleton instance of the Context.
Protected Member Functions
Context (bool _IsLittleEndian, Expr::Width _PointerWidth)
Private Attributes
bool IsLittleEndian
Whether the target architecture is little endian or not.
Expr::Width PointerWidth
The pointer width of the target architecture.
Detailed Description
Context - Helper class for storing global information about a KLEE run.
Definition at line 18 of file Context.h.
Constructor & Destructor Documentation
Context() [1/2]
klee::Context::Context (bool _IsLittleEndian, Expr::Width _PointerWidth) inline protected
Definition at line 26 of file Context.h.
Context() [2/2]
klee::Context::Context () inline
Definition at line 30 of file Context.h.
Referenced by initialize().
Member Function Documentation
get()
const Context & Context::get () static
get - Return the global singleton instance of the Context.
Definition at line 30 of file Context.cpp.
References Initialized, and TheContext.
Referenced by klee::Executor::callExternalFunction(), klee::Executor::computeOffsets(), klee::Executor::computeOffsetsSeqTy(), klee::Expr::createPointer(), klee::Expr::createSExtToPointerWidth(), klee::Expr::createZExtToPointerWidth(), klee::Executor::evalConstant(), klee::Executor::evalConstantExpr(), klee::Executor::executeAlloc(), klee::Executor::executeCall(), klee::Executor::executeInstruction(), klee::MemoryObject::getBaseExpr(), klee::MemoryObject::getBoundsCheckOffset(), klee::MemoryObject::getSizeExpr(), klee::ObjectState::read(), klee::Executor::runFunctionAsMain(), klee::ObjectState::write(), klee::ObjectState::write16(), klee::ObjectState::write32(), and klee::ObjectState::write64().
getPointerWidth()
Expr::Width klee::Context::getPointerWidth () const inline
Returns width of the pointer in bits.
Definition at line 41 of file Context.h.
References PointerWidth.
Referenced by klee::Executor::callExternalFunction(), klee::Executor::evalConstantExpr(), klee::Executor::executeAlloc(), klee::Executor::executeCall(), klee::Executor::executeInstruction(), and klee::Executor::runFunctionAsMain().
initialize()
void Context::initialize (bool IsLittleEndian, Expr::Width PointerWidth) static
initialize - Construct the global Context instance.
Definition at line 24 of file Context.cpp.
References Context(), Initialized, IsLittleEndian, PointerWidth, and TheContext.
Referenced by klee::Executor::setModule().
isLittleEndian()
bool klee::Context::isLittleEndian () const inline
Definition at line 38 of file Context.h.
References IsLittleEndian.
Referenced by klee::ObjectState::read(), klee::ObjectState::write(), klee::ObjectState::write16(), klee::ObjectState::write32(), and klee::ObjectState::write64().
Member Data Documentation
IsLittleEndian
bool klee::Context::IsLittleEndian private
Whether the target architecture is little endian or not.
Definition at line 20 of file Context.h.
Referenced by initialize(), and isLittleEndian().
PointerWidth
Expr::Width klee::Context::PointerWidth private
The pointer width of the target architecture.
Definition at line 23 of file Context.h.
Referenced by getPointerWidth(), and initialize().
The documentation for this class was generated from the following files:
/Users/cristic/klee/lib/Core/Context.h
/Users/cristic/klee/lib/Core/Context.cpp