klee: klee::WallTimer Class Reference
klee::WallTimer Class Reference
#include <Timer.h>
Public Member Functions
WallTimer ()
time::Span delta () const
Return the delta since the timer was created.
Private Attributes
const time::Point start
Detailed Description
A WallTimer stores its creation time.
Definition at line 25 of file Timer.h.
Constructor & Destructor Documentation
WallTimer()
WallTimer::WallTimer ()
Definition at line 20 of file Timer.cpp.
Member Function Documentation
delta()
time::Span WallTimer::delta () const
Return the delta since the timer was created.
Definition at line 22 of file Timer.cpp.
References klee::time::getWallTime(), and start.
Referenced by klee::TimerStatIncrementer::delta(), and klee::TimerStatIncrementer::~TimerStatIncrementer().
Member Data Documentation
start
const time::Point klee::WallTimer::start private
Definition at line 26 of file Timer.h.
Referenced by delta().
The documentation for this class was generated from the following files:
/Users/cristic/klee/include/klee/Support/Timer.h
/Users/cristic/klee/lib/Support/Timer.cpp