klee: klee::Statistic Class Reference
klee::Statistic Class Reference final
#include <Statistic.h>
Public Member Functions
Statistic (const std::string &name, const std::string &shortName)
~Statistic ()=default
std::uint32_t getID () const
getID - Get the unique statistic ID.
const std::string & getName () const
getName - Get the statistic name.
const std::string & getShortName () const
std::uint64_t getValue () const
getValue - Get the current primary statistic value.
operator std::uint64_t () const
operator std::uint64_t - Get the current primary statistic value.
Statistic & operator++ ()
operator++ - Increment the statistic by 1.
Statistic & operator+= (std::uint64_t addend)
operator+= - Increment the statistic by
Private Attributes
std::uint32_t id
const std::string name
const std::string shortName
Friends
class StatisticManager
class StatisticRecord
Detailed Description
Statistic - A named statistic instance.
The Statistic class holds information about the statistic, but not the actual values. Values are managed by the global StatisticManager to enable transparent support for instruction level and call path level statistics.
Definition at line 26 of file Statistic.h.
Constructor & Destructor Documentation
Statistic()
Statistic::Statistic (const std::string & name, const std::string & shortName)
Definition at line 67 of file Statistics.cpp.
References getStatisticManager(), and klee::StatisticManager::registerStatistic().
~Statistic()
klee::Statistic::~Statistic () default
Member Function Documentation
getID()
std::uint32_t klee::Statistic::getID () const inline
getID - Get the unique statistic ID.
Definition at line 40 of file Statistic.h.
References id.
Referenced by klee::StatsTracker::writeIStats().
getName()
const std::string & klee::Statistic::getName () const inline
getName - Get the statistic name.
Definition at line 43 of file Statistic.h.
References name.
Referenced by klee::StatsTracker::writeIStats().
getShortName()
const std::string & klee::Statistic::getShortName () const inline
getShortName - Get the "short" statistic name, used in callgrind output for example.
Definition at line 47 of file Statistic.h.
References shortName.
Referenced by klee::StatsTracker::writeIStats().
getValue()
std::uint64_t Statistic::getValue () const
getValue - Get the current primary statistic value.
Definition at line 77 of file Statistics.cpp.
References klee::StatisticManager::getValue(), and klee::theStatisticManager.
Referenced by operator std::uint64_t(), QueryLoggingSolver::startQuery(), and klee::StatsTracker::stepInstruction().
operator std::uint64_t()
klee::Statistic::operator std::uint64_t () const inline
operator std::uint64_t - Get the current primary statistic value.
Definition at line 53 of file Statistic.h.
References getValue().
operator++()
Statistic & klee::Statistic::operator++ () inline
operator++ - Increment the statistic by 1.
Definition at line 56 of file Statistic.h.
operator+=()
Statistic & Statistic::operator+= (std::uint64_t addend)
operator+= - Increment the statistic by
addend.
Definition at line 72 of file Statistics.cpp.
References klee::StatisticManager::incrementStatistic(), and klee::theStatisticManager.
Friends And Related Function Documentation
StatisticManager
friend class StatisticManager friend
Definition at line 27 of file Statistic.h.
StatisticRecord
friend class StatisticRecord friend
Definition at line 28 of file Statistic.h.
Member Data Documentation
id
std::uint32_t klee::Statistic::id private
Definition at line 31 of file Statistic.h.
Referenced by klee::Executor::dumpStates(), getID(), klee::StatisticManager::getIndexedValue(), klee::StatisticRecord::getValue(), klee::StatisticManager::getValue(), klee::StatisticManager::incrementIndexedValue(), klee::StatisticManager::incrementStatistic(), klee::StatisticRecord::incrementValue(), klee::StatisticManager::registerStatistic(), and klee::StatisticManager::setIndexedValue().
name
const std::string klee::Statistic::name private
Definition at line 32 of file Statistic.h.
Referenced by getName().
shortName
const std::string klee::Statistic::shortName private
Definition at line 33 of file Statistic.h.
Referenced by getShortName().
The documentation for this class was generated from the following files:
/Users/cristic/klee/include/klee/Statistics/Statistic.h
/Users/cristic/klee/lib/Basic/Statistics.cpp