klee: klee::RaiseAsmPass Class Reference
klee::RaiseAsmPass Class Reference
#include <Passes.h>
Inherits llvm::ModulePass.
Public Member Functions
RaiseAsmPass ()
bool runOnModule (llvm::Module &M) override
Private Member Functions
llvm::Function * getIntrinsic (llvm::Module &M, unsigned IID, llvm::Type **Tys, unsigned NumTys)
llvm::Function * getIntrinsic (llvm::Module &M, unsigned IID, llvm::Type *Ty0)
bool runOnInstruction (llvm::Module &M, llvm::Instruction *I)
Private Attributes
const llvm::TargetLowering * TLI
llvm::Triple triple
Static Private Attributes
static char ID = 0
Detailed Description
RaiseAsmPass - This pass raises some common occurences of inline asm which are used by glibc into normal LLVM IR.
Definition at line 35 of file Passes.h.
Constructor & Destructor Documentation
RaiseAsmPass()
klee::RaiseAsmPass::RaiseAsmPass () inline
Definition at line 51 of file Passes.h.
Member Function Documentation
getIntrinsic() [1/2]
llvm::Function * klee::RaiseAsmPass::getIntrinsic (llvm::Module & M, unsigned IID, llvm::Type ** Tys, unsigned NumTys) private
Referenced by getIntrinsic().
getIntrinsic() [2/2]
llvm::Function * klee::RaiseAsmPass::getIntrinsic (llvm::Module & M, unsigned IID, llvm::Type * Ty0) inline private
Definition at line 44 of file Passes.h.
References getIntrinsic().
runOnInstruction()
bool RaiseAsmPass::runOnInstruction (llvm::Module & M, llvm::Instruction * I) private
Definition at line 39 of file RaiseAsm.cpp.
References TLI, and triple.
Referenced by runOnModule().
runOnModule()
bool RaiseAsmPass::runOnModule (llvm::Module & M) override
Definition at line 76 of file RaiseAsm.cpp.
References klee::klee_warning(), runOnInstruction(), TLI, and triple.
Member Data Documentation
ID
char RaiseAsmPass::ID = 0 static private
Definition at line 36 of file Passes.h.
TLI
const llvm::TargetLowering* klee::RaiseAsmPass::TLI private
Definition at line 38 of file Passes.h.
Referenced by runOnInstruction(), and runOnModule().
triple
llvm::Triple klee::RaiseAsmPass::triple private
Definition at line 40 of file Passes.h.
Referenced by runOnInstruction(), and runOnModule().
The documentation for this class was generated from the following files:
/Users/cristic/klee/lib/Module/Passes.h
/Users/cristic/klee/lib/Module/RaiseAsm.cpp