klee: klee::SelectExpr Class Reference
klee::SelectExpr Class Reference
Class representing an if-then-else expression.
#include <Expr.h>
Public Member Functions
Width getWidth () const
Kind getKind () const
unsigned getNumKids () const
ref< Expr > getKid (unsigned i) const
virtual ref< Expr > rebuild (ref< Expr > kids[]) const
Public Member Functions inherited from klee::Expr
Expr ()
virtual ~Expr ()
virtual Kind getKind () const =0
virtual Width getWidth () const =0
virtual unsigned getNumKids () const =0
virtual ref< Expr > getKid (unsigned i) const =0
virtual void print (llvm::raw_ostream &os) const
void dump () const
dump - Print the expression to stderr.
virtual unsigned hash () const
Returns the pre-computed hash of the current expression.
virtual unsigned computeHash ()
int compare (const Expr &b) const
virtual ref< Expr > rebuild (ref< Expr > kids[]) const =0
bool isZero () const
isZero - Is this a constant zero.
bool isTrue () const
isTrue - Is this the true expression.
bool isFalse () const
isFalse - Is this the false expression.
Static Public Member Functions
static ref< Expr > alloc (const ref< Expr > &c, const ref< Expr > &t, const ref< Expr > &f)
static ref< Expr > create (ref< Expr > c, ref< Expr > t, ref< Expr > f)
static bool isValidKidWidth (unsigned kid, Width w)
static bool classof (const Expr *E)
static bool classof (const SelectExpr *)
Static Public Member Functions inherited from klee::NonConstantExpr
static bool classof (const Expr *E)
static bool classof (const NonConstantExpr *)
Static Public Member Functions inherited from klee::Expr
static void printKind (llvm::raw_ostream &os, Kind k)
static void printWidth (llvm::raw_ostream &os, Expr::Width w)
static unsigned getMinBytesForWidth (Width w)
returns the smallest number of bytes in which the given width fits
static ref< Expr > createSExtToPointerWidth (ref< Expr > e)
static ref< Expr > createZExtToPointerWidth (ref< Expr > e)
static ref< Expr > createImplies (ref< Expr > hyp, ref< Expr > conc)
static ref< Expr > createIsZero (ref< Expr > e)
static ref< Expr > createTempRead (const Array *array, Expr::Width w)
static ref< ConstantExpr > createPointer (uint64_t v)
static ref< Expr > createFromKind (Kind k, std::vector< CreateArg > args)
static bool isValidKidWidth (unsigned kid, Width w)
static bool needsResultType ()
static bool classof (const Expr *)
Public Attributes
ref< Expr > cond
ref< Expr > trueExpr
ref< Expr > falseExpr
Public Attributes inherited from klee::Expr
class ReferenceCounter _refCount
Required by klee::ref-managed objects.
Static Public Attributes
static const Kind kind = Select
static const unsigned numKids = 3
Static Public Attributes inherited from klee::Expr
static unsigned count = 0
static const unsigned MAGIC_HASH_CONSTANT = 39
static const Width InvalidWidth = 0
static const Width Bool = 1
static const Width Int8 = 8
static const Width Int16 = 16
static const Width Int32 = 32
static const Width Int64 = 64
static const Width Fl80 = 80
Protected Member Functions
virtual int compareContents (const Expr &b) const
virtual int compareContents (const Expr &b) const =0
Private Member Functions
SelectExpr (const ref< Expr > &c, const ref< Expr > &t, const ref< Expr > &f)
Additional Inherited Members
Public Types inherited from klee::Expr
enum Kind {
InvalidKind = -1 , Constant = 0 , NotOptimized , Read =NotOptimized+2 ,
Select , Concat , Extract , ZExt ,
SExt , Not , Add , Sub ,
Mul , UDiv , SDiv , URem ,
SRem , And , Or , Xor ,
Shl , LShr , AShr , Eq ,
Ne , Ult , Ule , Ugt ,
Uge , Slt , Sle , Sgt ,
Sge , LastKind =Sge , CastKindFirst =ZExt , CastKindLast =SExt ,
BinaryKindFirst =Add , BinaryKindLast =Sge , CmpKindFirst =Eq , CmpKindLast =Sge
}
typedef unsigned Width
The type of an expression is simply its width, in bits.
Protected Attributes inherited from klee::Expr
unsigned hashValue
Detailed Description
Class representing an if-then-else expression.
Definition at line 610 of file Expr.h.
Constructor & Destructor Documentation
SelectExpr()
klee::SelectExpr::SelectExpr (const ref< Expr > & c, const ref< Expr > & t, const ref< Expr > & f) inline private
Definition at line 653 of file Expr.h.
Referenced by alloc().
Member Function Documentation
alloc()
static ref< Expr > klee::SelectExpr::alloc (const ref< Expr > & c, const ref< Expr > & t, const ref< Expr > & f) inline static
Definition at line 619 of file Expr.h.
References klee::Expr::computeHash(), and SelectExpr().
Referenced by create().
classof() [1/2]
static bool klee::SelectExpr::classof (const Expr * E) inline static
Definition at line 657 of file Expr.h.
References klee::Expr::getKind(), and klee::Expr::Select.
classof() [2/2]
static bool klee::SelectExpr::classof (const SelectExpr *) inline static
Definition at line 660 of file Expr.h.
compareContents()
virtual int klee::SelectExpr::compareContents (const Expr & b) const inline protected virtual
Compares b to this Expr and determines how they are ordered (ignoring their kid expressions - i.e. those returned by getKid()).
Typically this requires comparing internal attributes of the Expr.
Implementations can assume that b and this are of the same kind.
This method effectively defines a partial order over Expr of the same kind (partial because kid Expr are not compared).
This method should not be called directly. Instead compare() should be used.
Parameters
[in] b Expr to compare this to.
Returns
One of the following values:
-1 if this is < b ignoring kid expressions.
1 if this is > b ignoring kid expressions.
0 if this and b are not ordered.
< and > are binary relations that express the partial order.
Implements klee::Expr.
Definition at line 663 of file Expr.h.
create()
ref< Expr > SelectExpr::create (ref< Expr > c, ref< Expr > t, ref< Expr > f) static
Definition at line 592 of file Expr.cpp.
References alloc(), klee::Expr::Bool, klee::Expr::createIsZero(), and klee::Expr::getWidth().
Referenced by klee::ExprOptimizer::buildConstantSelectExpr(), klee::ExprOptimizer::buildMixedSelectExpr(), klee::Expr::createFromKind(), klee::Executor::executeCall(), klee::Executor::executeInstruction(), klee::ExecutionState::merge(), and rebuild().
getKid()
ref< Expr > klee::SelectExpr::getKid (unsigned i) const inline virtual
Implements klee::Expr.
Definition at line 632 of file Expr.h.
References cond, falseExpr, and trueExpr.
getKind()
Kind klee::SelectExpr::getKind () const inline virtual
Implements klee::Expr.
Definition at line 629 of file Expr.h.
References klee::Expr::Select.
getNumKids()
unsigned klee::SelectExpr::getNumKids () const inline virtual
Implements klee::Expr.
Definition at line 631 of file Expr.h.
References numKids.
getWidth()
Width klee::SelectExpr::getWidth () const inline virtual
Implements klee::Expr.
Definition at line 628 of file Expr.h.
References klee::Expr::getWidth(), and trueExpr.
isValidKidWidth()
static bool klee::SelectExpr::isValidKidWidth (unsigned kid, Width w) inline static
Definition at line 641 of file Expr.h.
References klee::Expr::Bool.
rebuild()
virtual ref< Expr > klee::SelectExpr::rebuild (ref< Expr > kids[]) const inline virtual
Implements klee::Expr.
Definition at line 648 of file Expr.h.
References create().
Member Data Documentation
cond
ref<Expr> klee::SelectExpr::cond
Definition at line 616 of file Expr.h.
Referenced by klee::ExprRangeEvaluator< T >::evaluate(), klee::ImpliedValue::getImpliedValues(), getKid(), and CexData::propogatePossibleValues().
falseExpr
ref<Expr> klee::SelectExpr::falseExpr
Definition at line 616 of file Expr.h.
Referenced by klee::ExprRangeEvaluator< T >::evaluate(), klee::ImpliedValue::getImpliedValues(), getKid(), and CexData::propogatePossibleValues().
kind
const Kind klee::SelectExpr::kind = Select static
Definition at line 612 of file Expr.h.
numKids
const unsigned klee::SelectExpr::numKids = 3 static
Definition at line 613 of file Expr.h.
Referenced by getNumKids().
trueExpr
ref<Expr> klee::SelectExpr::trueExpr
Definition at line 616 of file Expr.h.
Referenced by klee::ExprRangeEvaluator< T >::evaluate(), klee::ImpliedValue::getImpliedValues(), getKid(), getWidth(), and CexData::propogatePossibleValues().
The documentation for this class was generated from the following files:
/Users/cristic/klee/include/klee/Expr/Expr.h
/Users/cristic/klee/lib/Expr/Expr.cpp