klee: klee::generic_gep_type_iterator< ItTy > Class Template Reference
klee::generic_gep_type_iterator< ItTy > Class Template Reference
#include <GetElementPtrTypeIterator.h>
Inherits std::iterator< std::forward_iterator_tag, llvm::Type *, ptrdiff_t >.
Public Member Functions
bool operator== (const generic_gep_type_iterator &x) const
bool operator!= (const generic_gep_type_iterator &x) const
llvm::Type * operator* () const
llvm::Type * getIndexedType () const
llvm::Type * operator-> () const
llvm::Value * getOperand () const
generic_gep_type_iterator & operator++ ()
generic_gep_type_iterator operator++ (int)
Static Public Member Functions
static generic_gep_type_iterator begin (llvm::Type *Ty, ItTy It)
static generic_gep_type_iterator end (ItTy It)
Private Types
typedef std::iterator< std::forward_iterator_tag, llvm::Type *, ptrdiff_t > super
Private Member Functions
generic_gep_type_iterator ()
llvm::Value * asValue (llvm::Value *V) const
llvm::Value * asValue (unsigned U) const
Private Attributes
ItTy OpIt
llvm::Type * CurTy
Detailed Description
template<typename ItTy = llvm::User::const_op_iterator>
class klee::generic_gep_type_iterator< ItTy >
Definition at line 30 of file GetElementPtrTypeIterator.h.
Member Typedef Documentation
super
template<typename ItTy = llvm::User::const_op_iterator> typedef std::iterator<std::forward_iterator_tag, llvm::Type *, ptrdiff_t> klee::generic_gep_type_iterator< ItTy >::super private
Definition at line 33 of file GetElementPtrTypeIterator.h.
Constructor & Destructor Documentation
generic_gep_type_iterator()
template<typename ItTy = llvm::User::const_op_iterator> klee::generic_gep_type_iterator< ItTy >::generic_gep_type_iterator () inline private
Definition at line 37 of file GetElementPtrTypeIterator.h.
Member Function Documentation
asValue() [1/2]
template<typename ItTy = llvm::User::const_op_iterator> llvm::Value * klee::generic_gep_type_iterator< ItTy >::asValue (llvm::Value * V) const inline private
Definition at line 39 of file GetElementPtrTypeIterator.h.
Referenced by klee::generic_gep_type_iterator< ItTy >::getOperand().
asValue() [2/2]
template<typename ItTy = llvm::User::const_op_iterator> llvm::Value * klee::generic_gep_type_iterator< ItTy >::asValue (unsigned U) const inline private
Definition at line 40 of file GetElementPtrTypeIterator.h.
References klee::generic_gep_type_iterator< ItTy >::CurTy.
begin()
template<typename ItTy = llvm::User::const_op_iterator> static generic_gep_type_iterator klee::generic_gep_type_iterator< ItTy >::begin (llvm::Type * Ty, ItTy It) inline static
Definition at line 45 of file GetElementPtrTypeIterator.h.
References klee::generic_gep_type_iterator< ItTy >::CurTy, and klee::generic_gep_type_iterator< ItTy >::OpIt.
Referenced by klee::ev_type_begin(), klee::gep_type_begin(), klee::iv_type_begin(), and klee::vce_type_begin().
end()
template<typename ItTy = llvm::User::const_op_iterator> static generic_gep_type_iterator klee::generic_gep_type_iterator< ItTy >::end (ItTy It) inline static
Definition at line 51 of file GetElementPtrTypeIterator.h.
References klee::generic_gep_type_iterator< ItTy >::CurTy, and klee::generic_gep_type_iterator< ItTy >::OpIt.
Referenced by klee::ev_type_end(), klee::gep_type_end(), klee::iv_type_end(), and klee::vce_type_end().
getIndexedType()
template<typename ItTy = llvm::User::const_op_iterator> llvm::Type * klee::generic_gep_type_iterator< ItTy >::getIndexedType () const inline
Definition at line 67 of file GetElementPtrTypeIterator.h.
References klee::generic_gep_type_iterator< ItTy >::CurTy, and klee::generic_gep_type_iterator< ItTy >::getOperand().
getOperand()
template<typename ItTy = llvm::User::const_op_iterator> llvm::Value * klee::generic_gep_type_iterator< ItTy >::getOperand () const inline
Definition at line 80 of file GetElementPtrTypeIterator.h.
References klee::generic_gep_type_iterator< ItTy >::asValue(), and klee::generic_gep_type_iterator< ItTy >::OpIt.
Referenced by klee::generic_gep_type_iterator< ItTy >::getIndexedType(), and klee::generic_gep_type_iterator< ItTy >::operator++().
operator!=()
template<typename ItTy = llvm::User::const_op_iterator> bool klee::generic_gep_type_iterator< ItTy >::operator!= (const generic_gep_type_iterator< ItTy > & x) const inline
Definition at line 61 of file GetElementPtrTypeIterator.h.
References klee::generic_gep_type_iterator< ItTy >::operator==().
operator*()
template<typename ItTy = llvm::User::const_op_iterator> llvm::Type * klee::generic_gep_type_iterator< ItTy >::operator* () const inline
Definition at line 65 of file GetElementPtrTypeIterator.h.
References klee::generic_gep_type_iterator< ItTy >::CurTy.
Referenced by klee::generic_gep_type_iterator< ItTy >::operator->().
operator++() [1/2]
template<typename ItTy = llvm::User::const_op_iterator> generic_gep_type_iterator & klee::generic_gep_type_iterator< ItTy >::operator++ () inline
Definition at line 82 of file GetElementPtrTypeIterator.h.
References klee::generic_gep_type_iterator< ItTy >::CurTy, klee::generic_gep_type_iterator< ItTy >::getOperand(), and klee::generic_gep_type_iterator< ItTy >::OpIt.
operator++() [2/2]
template<typename ItTy = llvm::User::const_op_iterator> generic_gep_type_iterator klee::generic_gep_type_iterator< ItTy >::operator++ (int) inline
Definition at line 100 of file GetElementPtrTypeIterator.h.
operator->()
template<typename ItTy = llvm::User::const_op_iterator> llvm::Type * klee::generic_gep_type_iterator< ItTy >::operator-> () const inline
Definition at line 78 of file GetElementPtrTypeIterator.h.
References klee::generic_gep_type_iterator< ItTy >::operator*().
operator==()
template<typename ItTy = llvm::User::const_op_iterator> bool klee::generic_gep_type_iterator< ItTy >::operator== (const generic_gep_type_iterator< ItTy > & x) const inline
Definition at line 58 of file GetElementPtrTypeIterator.h.
References klee::generic_gep_type_iterator< ItTy >::OpIt.
Referenced by klee::generic_gep_type_iterator< ItTy >::operator!=().
Member Data Documentation
CurTy
template<typename ItTy = llvm::User::const_op_iterator> llvm::Type* klee::generic_gep_type_iterator< ItTy >::CurTy private
Definition at line 36 of file GetElementPtrTypeIterator.h.
Referenced by klee::generic_gep_type_iterator< ItTy >::asValue(), klee::generic_gep_type_iterator< ItTy >::begin(), klee::generic_gep_type_iterator< ItTy >::end(), klee::generic_gep_type_iterator< ItTy >::getIndexedType(), klee::generic_gep_type_iterator< ItTy >::operator*(), and klee::generic_gep_type_iterator< ItTy >::operator++().
OpIt
template<typename ItTy = llvm::User::const_op_iterator> ItTy klee::generic_gep_type_iterator< ItTy >::OpIt private
Definition at line 35 of file GetElementPtrTypeIterator.h.
Referenced by klee::generic_gep_type_iterator< ItTy >::begin(), klee::generic_gep_type_iterator< ItTy >::end(), klee::generic_gep_type_iterator< ItTy >::getOperand(), klee::generic_gep_type_iterator< ItTy >::operator++(), and klee::generic_gep_type_iterator< ItTy >::operator==().
The documentation for this class was generated from the following file:
/Users/cristic/klee/lib/Core/GetElementPtrTypeIterator.h