klee: klee::InstructionInfoTable Class Reference
klee::InstructionInfoTable Class Reference
#include <InstructionInfoTable.h>
Public Member Functions
InstructionInfoTable (const llvm::Module &m)
unsigned getMaxID () const
const InstructionInfo & getInfo (const llvm::Instruction &) const
const FunctionInfo & getFunctionInfo (const llvm::Function &) const
Private Attributes
std::unordered_map< const llvm::Instruction *, std::unique_ptr< InstructionInfo > > infos
std::unordered_map< const llvm::Function *, std::unique_ptr< FunctionInfo > > functionInfos
std::vector< std::unique_ptr< std::string > > internedStrings
Detailed Description
Definition at line 66 of file InstructionInfoTable.h.
Constructor & Destructor Documentation
InstructionInfoTable()
InstructionInfoTable::InstructionInfoTable (const llvm::Module & m) explicit
Definition at line 164 of file InstructionInfoTable.cpp.
References functionInfos, DebugInfoExtractor::getFunctionInfo(), DebugInfoExtractor::getInstructionInfo(), infos, and internedStrings.
Member Function Documentation
getFunctionInfo()
const FunctionInfo & InstructionInfoTable::getFunctionInfo (const llvm::Function & f) const
Definition at line 201 of file InstructionInfoTable.cpp.
References functionInfos.
Referenced by klee::StatsTracker::computeReachableUncovered().
getInfo()
const InstructionInfo & InstructionInfoTable::getInfo (const llvm::Instruction & inst) const
Definition at line 192 of file InstructionInfoTable.cpp.
References infos.
Referenced by klee::StatsTracker::computeReachableUncovered().
getMaxID()
unsigned InstructionInfoTable::getMaxID () const
Definition at line 187 of file InstructionInfoTable.cpp.
References functionInfos, and infos.
Member Data Documentation
functionInfos
std::unordered_map<const llvm::Function *, std::unique_ptr<FunctionInfo> > klee::InstructionInfoTable::functionInfos private
Definition at line 71 of file InstructionInfoTable.h.
Referenced by getFunctionInfo(), getMaxID(), and InstructionInfoTable().
infos
std::unordered_map<const llvm::Instruction *, std::unique_ptr<InstructionInfo> > klee::InstructionInfoTable::infos private
Definition at line 69 of file InstructionInfoTable.h.
Referenced by getInfo(), getMaxID(), and InstructionInfoTable().
internedStrings
std::vector<std::unique_ptr<std::string> > klee::InstructionInfoTable::internedStrings private
Definition at line 72 of file InstructionInfoTable.h.
Referenced by InstructionInfoTable().
The documentation for this class was generated from the following files:
/Users/cristic/klee/include/klee/Module/InstructionInfoTable.h
/Users/cristic/klee/lib/Module/InstructionInfoTable.cpp