klee: klee::KleeIRMetaData Class Reference
klee::KleeIRMetaData Class Reference
Handles KLEE-specific LLVM IR meta-data.
#include <KLEEIRMetaData.h>
Inherits llvm::MDBuilder.
Public Member Functions
KleeIRMetaData (llvm::LLVMContext &context)
llvm::MDNode * createStringNode (llvm::StringRef value)
Return a string node reflecting the value.
void addAnnotation (llvm::Instruction &inst, llvm::StringRef key, llvm::StringRef value)
Static Public Member Functions
static bool hasAnnotation (const llvm::Instruction &inst, llvm::StringRef key, llvm::StringRef value)
Check if the instruction has the key/value meta data.
Private Attributes
llvm::LLVMContext & Context
Detailed Description
Handles KLEE-specific LLVM IR meta-data.
Definition at line 18 of file KLEEIRMetaData.h.
Constructor & Destructor Documentation
KleeIRMetaData()
klee::KleeIRMetaData::KleeIRMetaData (llvm::LLVMContext & context) inline
Definition at line 23 of file KLEEIRMetaData.h.
Member Function Documentation
addAnnotation()
void klee::KleeIRMetaData::addAnnotation (llvm::Instruction & inst, llvm::StringRef key, llvm::StringRef value) inline
Definition at line 31 of file KLEEIRMetaData.h.
References createStringNode().
Referenced by klee::DivCheckPass::runOnModule(), and klee::OvershiftCheckPass::runOnModule().
createStringNode()
llvm::MDNode * klee::KleeIRMetaData::createStringNode (llvm::StringRef value) inline
Return a string node reflecting the value.
Definition at line 27 of file KLEEIRMetaData.h.
Referenced by addAnnotation().
hasAnnotation()
static bool klee::KleeIRMetaData::hasAnnotation (const llvm::Instruction & inst, llvm::StringRef key, llvm::StringRef value) inline static
Check if the instruction has the key/value meta data.
Definition at line 37 of file KLEEIRMetaData.h.
Referenced by klee::DivCheckPass::runOnModule(), and klee::OvershiftCheckPass::runOnModule().
Member Data Documentation
Context
llvm::LLVMContext& klee::KleeIRMetaData::Context private
Definition at line 20 of file KLEEIRMetaData.h.
The documentation for this class was generated from the following file:
/Users/cristic/klee/lib/Module/KLEEIRMetaData.h