klee: klee::expr::Decl Class Reference
klee::expr::Decl Class Reference abstract
Decl - Base class for top level declarations.
#include <Parser.h>
Public Types
enum DeclKind {
ArrayDeclKind , ExprVarDeclKind , VersionVarDeclKind , QueryCommandDeclKind ,
DeclKindLast = QueryCommandDeclKind , VarDeclKindFirst = ExprVarDeclKind , VarDeclKindLast = VersionVarDeclKind , CommandDeclKindFirst = QueryCommandDeclKind ,
CommandDeclKindLast = QueryCommandDeclKind
}
Public Member Functions
Decl (DeclKind _Kind)
virtual ~Decl ()
DeclKind getKind () const
getKind - Get the decl kind.
virtual void dump ()=0
dump - Dump the AST node to stderr.
Static Public Member Functions
static bool classof (const Decl *)
Private Attributes
DeclKind Kind
Detailed Description
Decl - Base class for top level declarations.
Definition at line 41 of file Parser.h.
Member Enumeration Documentation
DeclKind
enum klee::expr::Decl::DeclKind
Enumerator
ArrayDeclKind
ExprVarDeclKind
VersionVarDeclKind
QueryCommandDeclKind
DeclKindLast
VarDeclKindFirst
VarDeclKindLast
CommandDeclKindFirst
CommandDeclKindLast
Definition at line 43 of file Parser.h.
Constructor & Destructor Documentation
Decl()
Decl::Decl (DeclKind _Kind)
Definition at line 1604 of file Parser.cpp.
~Decl()
virtual klee::expr::Decl::~Decl () inline virtual
Definition at line 61 of file Parser.h.
Member Function Documentation
classof()
static bool klee::expr::Decl::classof (const Decl *) inline static
Definition at line 69 of file Parser.h.
dump()
virtual void klee::expr::Decl::dump () pure virtual
dump - Dump the AST node to stderr.
Implemented in klee::expr::ArrayDecl, and klee::expr::QueryCommand.
getKind()
DeclKind klee::expr::Decl::getKind () const inline
getKind - Get the decl kind.
Definition at line 64 of file Parser.h.
References Kind.
Referenced by klee::expr::ArrayDecl::classof(), klee::expr::VarDecl::classof(), klee::expr::ExprVarDecl::classof(), klee::expr::VersionVarDecl::classof(), klee::expr::CommandDecl::classof(), and klee::expr::QueryCommand::classof().
Member Data Documentation
Kind
DeclKind klee::expr::Decl::Kind private
Definition at line 57 of file Parser.h.
Referenced by getKind().
The documentation for this class was generated from the following files:
/Users/cristic/klee/include/klee/Expr/Parser/Parser.h
/Users/cristic/klee/lib/Expr/Parser.cpp