klee: DebugInfoExtractor Class Reference
DebugInfoExtractor Class Reference
Public Member Functions
DebugInfoExtractor (std::vector< std::unique_ptr< std::string > > &_internedStrings, const llvm::Module &_module)
std::string & getInternedString (const std::string &s)
std::unique_ptr< FunctionInfo > getFunctionInfo (const llvm::Function &Func)
std::unique_ptr< InstructionInfo > getInstructionInfo (const llvm::Instruction &Inst, const FunctionInfo *f)
Private Attributes
std::vector< std::unique_ptr< std::string > > & internedStrings
std::map< uintptr_t, uint64_t > lineTable
const llvm::Module & module
Detailed Description
Definition at line 84 of file InstructionInfoTable.cpp.
Constructor & Destructor Documentation
DebugInfoExtractor()
DebugInfoExtractor::DebugInfoExtractor (std::vector< std::unique_ptr< std::string > > & _internedStrings, const llvm::Module & _module) inline
Definition at line 91 of file InstructionInfoTable.cpp.
References buildInstructionToLineMap(), lineTable, and module.
Member Function Documentation
getFunctionInfo()
std::unique_ptr< FunctionInfo > DebugInfoExtractor::getFunctionInfo (const llvm::Function & Func) inline
Definition at line 113 of file InstructionInfoTable.cpp.
References getInternedString(), and lineTable.
Referenced by klee::InstructionInfoTable::InstructionInfoTable().
getInstructionInfo()
std::unique_ptr< InstructionInfo > DebugInfoExtractor::getInstructionInfo (const llvm::Instruction & Inst, const FunctionInfo * f) inline
Definition at line 129 of file InstructionInfoTable.cpp.
References klee::FunctionInfo::file, getInternedString(), line, klee::FunctionInfo::line, and lineTable.
Referenced by klee::InstructionInfoTable::InstructionInfoTable().
getInternedString()
std::string & DebugInfoExtractor::getInternedString (const std::string & s) inline
Definition at line 98 of file InstructionInfoTable.cpp.
References internedStrings.
Referenced by getFunctionInfo(), and getInstructionInfo().
Member Data Documentation
internedStrings
std::vector<std::unique_ptr<std::string> >& DebugInfoExtractor::internedStrings private
Definition at line 85 of file InstructionInfoTable.cpp.
Referenced by getInternedString().
lineTable
std::map<uintptr_t, uint64_t> DebugInfoExtractor::lineTable private
Definition at line 86 of file InstructionInfoTable.cpp.
Referenced by DebugInfoExtractor(), getFunctionInfo(), and getInstructionInfo().
module
const llvm::Module& DebugInfoExtractor::module private
Definition at line 88 of file InstructionInfoTable.cpp.
Referenced by DebugInfoExtractor().
The documentation for this class was generated from the following file:
/Users/cristic/klee/lib/Module/InstructionInfoTable.cpp