klee: klee::ExprRangeEvaluator< T > Class Template Reference
klee::ExprRangeEvaluator< T > Class Template Reference abstract
#include <ExprRangeEvaluator.h>
Public Member Functions
ExprRangeEvaluator ()
virtual ~ExprRangeEvaluator ()
T evaluate (const ref< Expr > &e)
Protected Member Functions
virtual T getInitialReadRange (const Array &os, T index)=0
T evalRead (const UpdateList &ul, T index)
Detailed Description
template<class T>
class klee::ExprRangeEvaluator< T >
Definition at line 56 of file ExprRangeEvaluator.h.
Constructor & Destructor Documentation
ExprRangeEvaluator()
template<class T > klee::ExprRangeEvaluator< T >::ExprRangeEvaluator () inline
Definition at line 65 of file ExprRangeEvaluator.h.
~ExprRangeEvaluator()
template<class T > virtual klee::ExprRangeEvaluator< T >::~ExprRangeEvaluator () inline virtual
Definition at line 66 of file ExprRangeEvaluator.h.
Member Function Documentation
evalRead()
template<class T > T klee::ExprRangeEvaluator< T >::evalRead (const UpdateList & ul, T index) protected
Definition at line 72 of file ExprRangeEvaluator.h.
References klee::UpdateList::head, and klee::UpdateList::root.
evaluate()
template<class T > T klee::ExprRangeEvaluator< T >::evaluate (const ref< Expr > & e)
Definition at line 93 of file ExprRangeEvaluator.h.
References klee::Expr::Add, klee::Expr::And, klee::Expr::AShr, klee::Expr::Concat, klee::SelectExpr::cond, klee::Expr::Constant, klee::Expr::Eq, klee::SelectExpr::falseExpr, klee::ref< T >::get(), klee::Expr::getKid(), klee::Expr::getKind(), klee::Expr::getNumKids(), klee::ReadExpr::getWidth(), klee::Expr::getWidth(), klee::ReadExpr::index, klee::BinaryExpr::left, klee::Expr::LShr, klee::bits64::maxValueOfNBits(), klee::Expr::Mul, klee::Expr::Ne, klee::Expr::NotOptimized, klee::Expr::Or, klee::Array::range, klee::Expr::Read, klee::BinaryExpr::right, klee::UpdateList::root, klee::Expr::SDiv, klee::Expr::Select, klee::Expr::Sge, klee::Expr::Sgt, klee::Expr::Shl, klee::Expr::Sle, klee::Expr::Slt, klee::Expr::SRem, klee::Expr::Sub, klee::SelectExpr::trueExpr, klee::Expr::UDiv, klee::Expr::Uge, klee::Expr::Ugt, klee::Expr::Ule, klee::Expr::Ult, klee::ReadExpr::updates, klee::Expr::URem, and klee::Expr::Xor.
Referenced by CexData::evalRangeForExpr().
getInitialReadRange()
template<class T > virtual T klee::ExprRangeEvaluator< T >::getInitialReadRange (const Array & os, T index) protected pure virtual
getInitialReadRange - Return a range for the initial value of the given array (which may be constant), for the given range of indices.
Implemented in CexRangeEvaluator.
The documentation for this class was generated from the following file:
/Users/cristic/klee/include/klee/Expr/ExprRangeEvaluator.h