klee: klee::CallPathManager Class Reference
klee::CallPathManager Class Reference
#include <CallPathManager.h>
Public Member Functions
CallPathManager ()
~CallPathManager ()=default
void getSummaryStatistics (CallSiteSummaryTable &result)
CallPathNode * getCallPath (CallPathNode *parent, const llvm::Instruction *callSite, const llvm::Function *f)
Private Member Functions
CallPathNode * computeCallPath (CallPathNode *parent, const llvm::Instruction *callSite, const llvm::Function *f)
Private Attributes
CallPathNode root
std::vector< std::unique_ptr< CallPathNode > > paths
Detailed Description
Definition at line 65 of file CallPathManager.h.
Constructor & Destructor Documentation
CallPathManager()
CallPathManager::CallPathManager ()
Definition at line 42 of file CallPathManager.cpp.
~CallPathManager()
klee::CallPathManager::~CallPathManager () default
Member Function Documentation
computeCallPath()
CallPathNode * CallPathManager::computeCallPath (CallPathNode * parent, const llvm::Instruction * callSite, const llvm::Function * f) private
Definition at line 61 of file CallPathManager.cpp.
References klee::CallPathNode::parent, and paths.
Referenced by getCallPath().
getCallPath()
CallPathNode * CallPathManager::getCallPath (CallPathNode * parent, const llvm::Instruction * callSite, const llvm::Function * f)
Definition at line 74 of file CallPathManager.cpp.
References klee::CallPathNode::children, computeCallPath(), and root.
Referenced by klee::StatsTracker::framePushed().
getSummaryStatistics()
void CallPathManager::getSummaryStatistics (CallSiteSummaryTable & result)
Definition at line 44 of file CallPathManager.cpp.
References klee::CallSiteInfo::count, paths, and klee::CallSiteInfo::statistics.
Referenced by klee::StatsTracker::writeIStats().
Member Data Documentation
paths
std::vector<std::unique_ptr<CallPathNode> > klee::CallPathManager::paths private
Definition at line 67 of file CallPathManager.h.
Referenced by computeCallPath(), and getSummaryStatistics().
root
CallPathNode klee::CallPathManager::root private
Definition at line 66 of file CallPathManager.h.
Referenced by getCallPath().
The documentation for this class was generated from the following files:
/Users/cristic/klee/lib/Core/CallPathManager.h
/Users/cristic/klee/lib/Core/CallPathManager.cpp