klee: klee::ImmutableMap< K, D, CMP > Class Template Reference
klee::ImmutableMap< K, D, CMP > Class Template Reference
#include <ImmutableMap.h>
Public Types
typedef K key_type
typedef std::pair< K, D > value_type
typedef ImmutableTree< K, value_type, _Select1st< value_type, key_type >, CMP > Tree
typedef Tree::iterator iterator
Public Member Functions
ImmutableMap ()
ImmutableMap (const ImmutableMap &b)
~ImmutableMap ()
ImmutableMap & operator= (const ImmutableMap &b)
bool empty () const
size_t count (const key_type &key) const
const value_type * lookup (const key_type &key) const
const value_type * lookup_previous (const key_type &key) const
const value_type & min () const
const value_type & max () const
size_t size () const
ImmutableMap insert (const value_type &value) const
ImmutableMap replace (const value_type &value) const
ImmutableMap remove (const key_type &key) const
ImmutableMap popMin (const value_type &valueOut) const
ImmutableMap popMax (const value_type &valueOut) const
iterator begin () const
iterator end () const
iterator find (const key_type &key) const
iterator lower_bound (const key_type &key) const
iterator upper_bound (const key_type &key) const
Static Public Member Functions
static size_t getAllocated ()
Private Member Functions
ImmutableMap (const Tree &b)
Private Attributes
Tree elts
Detailed Description
template<class K, class D, class CMP = std::less<K>>
class klee::ImmutableMap< K, D, CMP >
Definition at line 25 of file ImmutableMap.h.
Member Typedef Documentation
iterator
template<class K , class D , class CMP = std::less<K>> typedef Tree::iterator klee::ImmutableMap< K, D, CMP >::iterator
Definition at line 31 of file ImmutableMap.h.
key_type
template<class K , class D , class CMP = std::less<K>> typedef K klee::ImmutableMap< K, D, CMP >::key_type
Definition at line 27 of file ImmutableMap.h.
Tree
template<class K , class D , class CMP = std::less<K>> typedef ImmutableTree<K, value_type, _Select1st<value_type,key_type>, CMP> klee::ImmutableMap< K, D, CMP >::Tree
Definition at line 30 of file ImmutableMap.h.
value_type
template<class K , class D , class CMP = std::less<K>> typedef std::pair<K,D> klee::ImmutableMap< K, D, CMP >::value_type
Definition at line 28 of file ImmutableMap.h.
Constructor & Destructor Documentation
ImmutableMap() [1/3]
template<class K , class D , class CMP = std::less<K>> klee::ImmutableMap< K, D, CMP >::ImmutableMap (const Tree & b) inline private
Definition at line 36 of file ImmutableMap.h.
ImmutableMap() [2/3]
template<class K , class D , class CMP = std::less<K>> klee::ImmutableMap< K, D, CMP >::ImmutableMap () inline
Definition at line 39 of file ImmutableMap.h.
ImmutableMap() [3/3]
template<class K , class D , class CMP = std::less<K>> klee::ImmutableMap< K, D, CMP >::ImmutableMap (const ImmutableMap< K, D, CMP > & b) inline
Definition at line 40 of file ImmutableMap.h.
~ImmutableMap()
template<class K , class D , class CMP = std::less<K>> klee::ImmutableMap< K, D, CMP >::~ImmutableMap () inline
Definition at line 41 of file ImmutableMap.h.
Member Function Documentation
begin()
template<class K , class D , class CMP = std::less<K>> iterator klee::ImmutableMap< K, D, CMP >::begin () const inline
Definition at line 83 of file ImmutableMap.h.
References klee::ImmutableTree< K, V, KOV, CMP >::begin(), and klee::ImmutableMap< K, D, CMP >::elts.
Referenced by klee::AddressSpace::copyOutConcretes(), klee::Executor::getAddressInfo(), klee::ExecutionState::merge(), klee::operator<<(), klee::AddressSpace::resolve(), and klee::AddressSpace::resolveOne().
count()
template<class K , class D , class CMP = std::less<K>> size_t klee::ImmutableMap< K, D, CMP >::count (const key_type & key) const inline
Definition at line 48 of file ImmutableMap.h.
References klee::ImmutableTree< K, V, KOV, CMP >::count(), and klee::ImmutableMap< K, D, CMP >::elts.
empty()
template<class K , class D , class CMP = std::less<K>> bool klee::ImmutableMap< K, D, CMP >::empty () const inline
Definition at line 45 of file ImmutableMap.h.
References klee::ImmutableMap< K, D, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::empty().
end()
template<class K , class D , class CMP = std::less<K>> iterator klee::ImmutableMap< K, D, CMP >::end () const inline
Definition at line 86 of file ImmutableMap.h.
References klee::ImmutableMap< K, D, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::end().
Referenced by klee::AddressSpace::copyOutConcretes(), klee::Executor::getAddressInfo(), klee::ExecutionState::merge(), klee::operator<<(), klee::AddressSpace::resolve(), and klee::AddressSpace::resolveOne().
find()
template<class K , class D , class CMP = std::less<K>> iterator klee::ImmutableMap< K, D, CMP >::find (const key_type & key) const inline
Definition at line 89 of file ImmutableMap.h.
References klee::ImmutableMap< K, D, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::find().
getAllocated()
template<class K , class D , class CMP = std::less<K>> static size_t klee::ImmutableMap< K, D, CMP >::getAllocated () inline static
Definition at line 99 of file ImmutableMap.h.
References klee::ImmutableTree< K, V, KOV, CMP >::allocated.
insert()
template<class K , class D , class CMP = std::less<K>> ImmutableMap klee::ImmutableMap< K, D, CMP >::insert (const value_type & value) const inline
Definition at line 67 of file ImmutableMap.h.
References klee::ImmutableMap< K, D, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::insert().
lookup()
template<class K , class D , class CMP = std::less<K>> const value_type * klee::ImmutableMap< K, D, CMP >::lookup (const key_type & key) const inline
Definition at line 51 of file ImmutableMap.h.
References klee::ImmutableMap< K, D, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::lookup().
Referenced by klee::AddressSpace::findObject().
lookup_previous()
template<class K , class D , class CMP = std::less<K>> const value_type * klee::ImmutableMap< K, D, CMP >::lookup_previous (const key_type & key) const inline
Definition at line 54 of file ImmutableMap.h.
References klee::ImmutableMap< K, D, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::lookup_previous().
Referenced by klee::AddressSpace::resolveOne().
lower_bound()
template<class K , class D , class CMP = std::less<K>> iterator klee::ImmutableMap< K, D, CMP >::lower_bound (const key_type & key) const inline
Definition at line 92 of file ImmutableMap.h.
References klee::ImmutableMap< K, D, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::lower_bound().
max()
template<class K , class D , class CMP = std::less<K>> const value_type & klee::ImmutableMap< K, D, CMP >::max () const inline
Definition at line 60 of file ImmutableMap.h.
References klee::ImmutableMap< K, D, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::max().
min()
template<class K , class D , class CMP = std::less<K>> const value_type & klee::ImmutableMap< K, D, CMP >::min () const inline
Definition at line 57 of file ImmutableMap.h.
References klee::ImmutableMap< K, D, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::min().
operator=()
template<class K , class D , class CMP = std::less<K>> ImmutableMap & klee::ImmutableMap< K, D, CMP >::operator= (const ImmutableMap< K, D, CMP > & b) inline
Definition at line 43 of file ImmutableMap.h.
References klee::ImmutableMap< K, D, CMP >::elts.
popMax()
template<class K , class D , class CMP = std::less<K>> ImmutableMap klee::ImmutableMap< K, D, CMP >::popMax (const value_type & valueOut) const inline
Definition at line 79 of file ImmutableMap.h.
References klee::ImmutableMap< K, D, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::popMax().
popMin()
template<class K , class D , class CMP = std::less<K>> ImmutableMap klee::ImmutableMap< K, D, CMP >::popMin (const value_type & valueOut) const inline
Definition at line 76 of file ImmutableMap.h.
References klee::ImmutableMap< K, D, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::popMin().
remove()
template<class K , class D , class CMP = std::less<K>> ImmutableMap klee::ImmutableMap< K, D, CMP >::remove (const key_type & key) const inline
Definition at line 73 of file ImmutableMap.h.
References klee::ImmutableMap< K, D, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::remove().
Referenced by klee::AddressSpace::unbindObject().
replace()
template<class K , class D , class CMP = std::less<K>> ImmutableMap klee::ImmutableMap< K, D, CMP >::replace (const value_type & value) const inline
Definition at line 70 of file ImmutableMap.h.
References klee::ImmutableMap< K, D, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::replace().
Referenced by klee::AddressSpace::bindObject(), and klee::AddressSpace::getWriteable().
size()
template<class K , class D , class CMP = std::less<K>> size_t klee::ImmutableMap< K, D, CMP >::size () const inline
Definition at line 63 of file ImmutableMap.h.
References klee::ImmutableMap< K, D, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::size().
upper_bound()
template<class K , class D , class CMP = std::less<K>> iterator klee::ImmutableMap< K, D, CMP >::upper_bound (const key_type & key) const inline
Definition at line 95 of file ImmutableMap.h.
References klee::ImmutableMap< K, D, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::upper_bound().
Referenced by klee::Executor::getAddressInfo(), klee::AddressSpace::resolve(), and klee::AddressSpace::resolveOne().
Member Data Documentation
elts
template<class K , class D , class CMP = std::less<K>> Tree klee::ImmutableMap< K, D, CMP >::elts private
Definition at line 34 of file ImmutableMap.h.
Referenced by klee::ImmutableMap< K, D, CMP >::begin(), klee::ImmutableMap< K, D, CMP >::count(), klee::ImmutableMap< K, D, CMP >::empty(), klee::ImmutableMap< K, D, CMP >::end(), klee::ImmutableMap< K, D, CMP >::find(), klee::ImmutableMap< K, D, CMP >::insert(), klee::ImmutableMap< K, D, CMP >::lookup(), klee::ImmutableMap< K, D, CMP >::lookup_previous(), klee::ImmutableMap< K, D, CMP >::lower_bound(), klee::ImmutableMap< K, D, CMP >::max(), klee::ImmutableMap< K, D, CMP >::min(), klee::ImmutableMap< K, D, CMP >::operator=(), klee::ImmutableMap< K, D, CMP >::popMax(), klee::ImmutableMap< K, D, CMP >::popMin(), klee::ImmutableMap< K, D, CMP >::remove(), klee::ImmutableMap< K, D, CMP >::replace(), klee::ImmutableMap< K, D, CMP >::size(), and klee::ImmutableMap< K, D, CMP >::upper_bound().
The documentation for this class was generated from the following file:
/Users/cristic/klee/include/klee/ADT/ImmutableMap.h