klee: klee::StatsTracker Class Reference
klee::StatsTracker Class Reference
#include <StatsTracker.h>
Public Member Functions
StatsTracker (Executor &_executor, std::string _objectFilename, bool _updateMinDistToUncovered)
~StatsTracker ()
StatsTracker (const StatsTracker &other)=delete
StatsTracker (StatsTracker &&other) noexcept=delete
StatsTracker & operator= (const StatsTracker &other)=delete
StatsTracker & operator= (StatsTracker &&other) noexcept=delete
void framePushed (ExecutionState &es, StackFrame *parentFrame)
void framePopped (ExecutionState &es)
void markBranchVisited (ExecutionState *visitedTrue, ExecutionState *visitedFalse)
void done ()
void stepInstruction (ExecutionState &es)
time::Span elapsed ()
Return duration since execution start.
void computeReachableUncovered ()
Static Public Member Functions
static bool useStatistics ()
static bool useIStats ()
Private Member Functions
void updateStateStatistics (uint64_t addend)
void writeStatsHeader ()
void writeStatsLine ()
void writeIStats ()
Private Attributes
Executor & executor
std::string objectFilename
std::unique_ptr< llvm::raw_fd_ostream > istatsFile
::sqlite3 * statsFile = nullptr
::sqlite3_stmt * transactionBeginStmt = nullptr
::sqlite3_stmt * transactionEndStmt = nullptr
::sqlite3_stmt * insertStmt = nullptr
std::uint32_t statsCommitEvery
std::uint32_t statsWriteCount = 0
time::Point startWallTime
unsigned numBranches
unsigned fullBranches
unsigned partialBranches
CallPathManager callPathManager
bool updateMinDistToUncovered
Friends
class WriteStatsTimer
class WriteIStatsTimer
Detailed Description
Definition at line 35 of file StatsTracker.h.
Constructor & Destructor Documentation
StatsTracker() [1/3]
StatsTracker::StatsTracker (Executor & _executor, std::string _objectFilename, bool _updateMinDistToUncovered)
Definition at line 165 of file StatsTracker.cpp.
References klee::TimerGroup::add(), computeReachableUncovered(), executor, klee::KModule::functions, klee::InterpreterHandler::getOutputFilename(), klee::InstructionInfo::id, klee::KInstruction::info, klee::KModule::infos, klee::KInstruction::inst, instructionIsCoverable(), klee::KFunction::instructions, klee::Executor::interpreterHandler, istatsFile, klee::klee_error(), klee::klee_warning(), klee::Executor::kmodule, numBranches, klee::KFunction::numInstructions, objectFilename, klee::InterpreterHandler::openOutputFile(), klee::StatisticManager::setIndex(), sqlite3ErrToStringAndFree(), statsCommitEvery, statsFile, klee::theStatisticManager, klee::Executor::timers, klee::KFunction::trackCoverage, transactionBeginStmt, transactionEndStmt, klee::stats::uncoveredInstructions, updateMinDistToUncovered, klee::StatisticManager::useIndexedStats(), klee::userSearcherRequiresMD2U(), useStatistics(), writeIStats(), writeStatsHeader(), and writeStatsLine().
~StatsTracker()
StatsTracker::~StatsTracker ()
Definition at line 302 of file StatsTracker.cpp.
References insertStmt, klee::klee_warning(), statsFile, transactionBeginStmt, and transactionEndStmt.
StatsTracker() [2/3]
klee::StatsTracker::StatsTracker (const StatsTracker & other) delete
StatsTracker() [3/3]
klee::StatsTracker::StatsTracker (StatsTracker && other) delete noexcept
Member Function Documentation
computeReachableUncovered()
void StatsTracker::computeReachableUncovered ()
Definition at line 777 of file StatsTracker.cpp.
References callTargets, klee::computeMinDistToUncovered(), klee::KModule::escapingFunctions, executor, functionCallers, functionShortestPath, klee::getDirectCallTarget(), klee::InstructionInfoTable::getFunctionInfo(), klee::StatisticManager::getIndexedValue(), klee::InstructionInfoTable::getInfo(), getSuccs(), klee::InstructionInfo::id, klee::FunctionInfo::id, klee::KModule::infos, klee::stats::instructions, klee::Executor::kmodule, klee::stats::minDistToReturn, klee::stats::minDistToUncovered, klee::KModule::module, klee::ExecutionState::pc, klee::StatisticManager::setIndexedValue(), klee::ExecutionState::stack, klee::Executor::states, klee::theStatisticManager, and klee::stats::uncoveredInstructions.
Referenced by done(), and StatsTracker().
done()
void StatsTracker::done ()
Definition at line 316 of file StatsTracker.cpp.
References computeReachableUncovered(), istatsFile, statsFile, updateMinDistToUncovered, writeIStats(), and writeStatsLine().
Referenced by klee::Executor::prepareForEarlyExit(), and klee::Executor::runFunctionAsMain().
elapsed()
time::Span StatsTracker::elapsed ()
Return duration since execution start.
Definition at line 525 of file StatsTracker.cpp.
References klee::time::getWallTime(), and startWallTime.
Referenced by writeStatsLine().
framePopped()
void StatsTracker::framePopped (ExecutionState & es)
Definition at line 413 of file StatsTracker.cpp.
Referenced by klee::Executor::executeInstruction(), and klee::Executor::unwindToNextLandingpad().
framePushed()
void StatsTracker::framePushed (ExecutionState & es, StackFrame * parentFrame)
Definition at line 386 of file StatsTracker.cpp.
References klee::StackFrame::caller, callPathManager, klee::StackFrame::callPathNode, klee::computeMinDistToUncovered(), klee::CallPathNode::count, klee::KFunction::function, klee::CallPathManager::getCallPath(), klee::KInstruction::inst, klee::StackFrame::kf, klee::StackFrame::minDistToUncoveredOnReturn, klee::ExecutionState::stack, and updateMinDistToUncovered.
Referenced by klee::Executor::executeCall(), klee::Executor::runFunctionAsMain(), and klee::Executor::unwindToNextLandingpad().
markBranchVisited()
void StatsTracker::markBranchVisited (ExecutionState * visitedTrue, ExecutionState * visitedFalse)
Definition at line 417 of file StatsTracker.cpp.
References klee::ExecutionState::coveredNew, klee::stats::falseBranches, fullBranches, klee::StatisticManager::getIndex(), klee::StatisticManager::getIndexedValue(), klee::ExecutionState::instsSinceCovNew, partialBranches, klee::theStatisticManager, and klee::stats::trueBranches.
Referenced by klee::Executor::executeInstruction().
operator=() [1/2]
StatsTracker & klee::StatsTracker::operator= (const StatsTracker & other) delete
operator=() [2/2]
StatsTracker & klee::StatsTracker::operator= (StatsTracker && other) delete noexcept
stepInstruction()
void StatsTracker::stepInstruction (ExecutionState & es)
Definition at line 328 of file StatsTracker.cpp.
References klee::StackFrame::callPathNode, klee::stats::coveredInstructions, klee::ExecutionState::coveredLines, klee::ExecutionState::coveredNew, klee::InstructionInfo::file, klee::StatisticManager::getIndexedValue(), klee::time::getUserTime(), klee::Statistic::getValue(), klee::time::getWallTime(), klee::InstructionInfo::id, klee::KInstruction::info, klee::KInstruction::inst, instructionIsCoverable(), klee::stats::instructionRealTime, klee::stats::instructions, klee::stats::instructionTime, klee::ExecutionState::instsSinceCovNew, istatsFile, klee::StackFrame::kf, klee::InstructionInfo::line, klee::ExecutionState::pc, klee::StatisticManager::setContext(), klee::StatisticManager::setIndex(), klee::ExecutionState::stack, klee::CallPathNode::statistics, statsFile, klee::theStatisticManager, klee::KFunction::trackCoverage, klee::stats::uncoveredInstructions, writeIStats(), and writeStatsLine().
Referenced by klee::Executor::stepInstruction().
updateStateStatistics()
void StatsTracker::updateStateStatistics (uint64_t addend) private
Definition at line 571 of file StatsTracker.cpp.
References executor, klee::InstructionInfo::id, klee::StatisticManager::incrementIndexedValue(), klee::KInstruction::info, klee::ExecutionState::pc, klee::ExecutionState::stack, klee::stats::states, klee::Executor::states, and klee::theStatisticManager.
Referenced by writeIStats().
useIStats()
bool StatsTracker::useIStats () static
Definition at line 125 of file StatsTracker.cpp.
Referenced by klee::Executor::Executor().
useStatistics()
bool StatsTracker::useStatistics () static
Definition at line 121 of file StatsTracker.cpp.
Referenced by klee::Executor::setModule(), and StatsTracker().
writeIStats()
void StatsTracker::writeIStats () private
Definition at line 582 of file StatsTracker.cpp.
References klee::InstructionInfo::assemblyLine, klee::FunctionInfo::assemblyLine, callPathManager, klee::CallSiteInfo::count, executor, klee::InstructionInfo::file, klee::FunctionInfo::file, klee::Statistic::getID(), klee::StatisticManager::getIndexedValue(), klee::Statistic::getName(), klee::StatisticManager::getNumStatistics(), klee::Statistic::getShortName(), klee::StatisticManager::getStatistic(), klee::StatisticManager::getStatisticID(), klee::CallPathManager::getSummaryStatistics(), klee::StatisticRecord::getValue(), klee::InstructionInfo::id, istatsFile, klee::Executor::kmodule, klee::InstructionInfo::line, klee::FunctionInfo::line, objectFilename, klee::stats::states, klee::CallSiteInfo::statistics, klee::theStatisticManager, klee::stats::uncoveredInstructions, and updateStateStatistics().
Referenced by done(), StatsTracker(), and stepInstruction().
writeStatsHeader()
void StatsTracker::writeStatsHeader () private
Definition at line 441 of file StatsTracker.cpp.
References insertStmt, klee::klee_error(), sqlite3ErrToStringAndFree(), and statsFile.
Referenced by StatsTracker().
writeStatsLine()
void StatsTracker::writeStatsLine () private
Definition at line 529 of file StatsTracker.cpp.
References klee::stats::cexCacheTime, klee::stats::coveredInstructions, elapsed(), executor, klee::stats::forkTime, fullBranches, klee::util::GetTotalMallocUsage(), klee::MemoryManager::getUsedDeterministicSize(), klee::time::getUserTime(), insertStmt, klee::stats::instructions, klee::klee_error(), klee::klee_warning(), klee::Executor::memory, numBranches, partialBranches, klee::stats::queries, klee::stats::queryCexCacheHits, klee::stats::queryCexCacheMisses, klee::stats::queryConstructs, klee::stats::queryTime, klee::stats::resolveTime, klee::stats::solverTime, klee::Executor::states, statsCommitEvery, statsFile, statsWriteCount, transactionBeginStmt, transactionEndStmt, and klee::stats::uncoveredInstructions.
Referenced by done(), StatsTracker(), and stepInstruction().
Friends And Related Function Documentation
WriteIStatsTimer
friend class WriteIStatsTimer friend
Definition at line 37 of file StatsTracker.h.
WriteStatsTimer
friend class WriteStatsTimer friend
Definition at line 36 of file StatsTracker.h.
Member Data Documentation
callPathManager
CallPathManager klee::StatsTracker::callPathManager private
Definition at line 54 of file StatsTracker.h.
Referenced by framePushed(), and writeIStats().
executor
Executor& klee::StatsTracker::executor private
Definition at line 39 of file StatsTracker.h.
Referenced by computeReachableUncovered(), StatsTracker(), updateStateStatistics(), writeIStats(), and writeStatsLine().
fullBranches
unsigned klee::StatsTracker::fullBranches private
Definition at line 52 of file StatsTracker.h.
Referenced by markBranchVisited(), and writeStatsLine().
insertStmt
::sqlite3_stmt* klee::StatsTracker::insertStmt = nullptr private
Definition at line 46 of file StatsTracker.h.
Referenced by writeStatsHeader(), writeStatsLine(), and ~StatsTracker().
istatsFile
std::unique_ptr<llvm::raw_fd_ostream> klee::StatsTracker::istatsFile private
Definition at line 42 of file StatsTracker.h.
Referenced by done(), StatsTracker(), stepInstruction(), and writeIStats().
numBranches
unsigned klee::StatsTracker::numBranches private
Definition at line 51 of file StatsTracker.h.
Referenced by StatsTracker(), and writeStatsLine().
objectFilename
std::string klee::StatsTracker::objectFilename private
Definition at line 40 of file StatsTracker.h.
Referenced by StatsTracker(), and writeIStats().
partialBranches
unsigned klee::StatsTracker::partialBranches private
Definition at line 52 of file StatsTracker.h.
Referenced by markBranchVisited(), and writeStatsLine().
startWallTime
time::Point klee::StatsTracker::startWallTime private
Definition at line 49 of file StatsTracker.h.
Referenced by elapsed().
statsCommitEvery
std::uint32_t klee::StatsTracker::statsCommitEvery private
Definition at line 47 of file StatsTracker.h.
Referenced by StatsTracker(), and writeStatsLine().
statsFile
::sqlite3* klee::StatsTracker::statsFile = nullptr private
Definition at line 43 of file StatsTracker.h.
Referenced by done(), StatsTracker(), stepInstruction(), writeStatsHeader(), writeStatsLine(), and ~StatsTracker().
statsWriteCount
std::uint32_t klee::StatsTracker::statsWriteCount = 0 private
Definition at line 48 of file StatsTracker.h.
Referenced by writeStatsLine().
transactionBeginStmt
::sqlite3_stmt* klee::StatsTracker::transactionBeginStmt = nullptr private
Definition at line 44 of file StatsTracker.h.
Referenced by StatsTracker(), writeStatsLine(), and ~StatsTracker().
transactionEndStmt
::sqlite3_stmt* klee::StatsTracker::transactionEndStmt = nullptr private
Definition at line 45 of file StatsTracker.h.
Referenced by StatsTracker(), writeStatsLine(), and ~StatsTracker().
updateMinDistToUncovered
bool klee::StatsTracker::updateMinDistToUncovered private
Definition at line 56 of file StatsTracker.h.
Referenced by done(), framePushed(), and StatsTracker().
The documentation for this class was generated from the following files:
/Users/cristic/klee/lib/Core/StatsTracker.h
/Users/cristic/klee/lib/Core/StatsTracker.cpp