klee: klee::ExternalDispatcher Class Reference
klee::ExternalDispatcher Class Reference
#include <ExternalDispatcher.h>
Public Member Functions
ExternalDispatcher (llvm::LLVMContext &ctx)
~ExternalDispatcher ()
bool executeCall (llvm::Function *function, llvm::Instruction *i, uint64_t *args)
void * resolveSymbol (const std::string &name)
int getLastErrno ()
void setLastErrno (int newErrno)
Private Attributes
ExternalDispatcherImpl * impl
Detailed Description
Definition at line 28 of file ExternalDispatcher.h.
Constructor & Destructor Documentation
ExternalDispatcher()
klee::ExternalDispatcher::ExternalDispatcher (llvm::LLVMContext & ctx)
Definition at line 344 of file ExternalDispatcher.cpp.
~ExternalDispatcher()
klee::ExternalDispatcher::~ExternalDispatcher ()
Definition at line 347 of file ExternalDispatcher.cpp.
References impl.
Member Function Documentation
executeCall()
bool klee::ExternalDispatcher::executeCall (llvm::Function * function, llvm::Instruction * i, uint64_t * args)
Definition at line 349 of file ExternalDispatcher.cpp.
References klee::ExternalDispatcherImpl::executeCall(), and impl.
Referenced by klee::Executor::callExternalFunction().
getLastErrno()
int klee::ExternalDispatcher::getLastErrno ()
Definition at line 358 of file ExternalDispatcher.cpp.
References klee::ExternalDispatcherImpl::getLastErrno(), and impl.
Referenced by klee::Executor::callExternalFunction().
resolveSymbol()
void * klee::ExternalDispatcher::resolveSymbol (const std::string & name)
Definition at line 354 of file ExternalDispatcher.cpp.
References impl, and klee::ExternalDispatcherImpl::resolveSymbol().
Referenced by klee::Executor::allocateGlobalObjects(), and klee::Executor::initializeGlobalObjects().
setLastErrno()
void klee::ExternalDispatcher::setLastErrno (int newErrno)
Definition at line 359 of file ExternalDispatcher.cpp.
References impl, and klee::ExternalDispatcherImpl::setLastErrno().
Referenced by klee::Executor::callExternalFunction().
Member Data Documentation
impl
ExternalDispatcherImpl* klee::ExternalDispatcher::impl private
Definition at line 30 of file ExternalDispatcher.h.
Referenced by executeCall(), getLastErrno(), resolveSymbol(), setLastErrno(), and ~ExternalDispatcher().
The documentation for this class was generated from the following files:
/Users/cristic/klee/lib/Core/ExternalDispatcher.h
/Users/cristic/klee/lib/Core/ExternalDispatcher.cpp