klee: klee::ImmutableTree< K, V, KOV, CMP > Class Template Reference
klee::ImmutableTree< K, V, KOV, CMP > Class Template Reference
#include <ImmutableTree.h>
Classes
class iterator
class Node
Public Types
typedef K key_type
typedef V value_type
typedef KOV key_of_value
typedef CMP key_compare
Public Member Functions
ImmutableTree ()
ImmutableTree (const ImmutableTree &s)
~ImmutableTree ()
ImmutableTree & operator= (const ImmutableTree &s)
bool empty () const
size_t count (const key_type &key) const
const value_type * lookup (const key_type &key) const
const value_type * lookup_previous (const key_type &key) const
const value_type & min () const
const value_type & max () const
size_t size () const
ImmutableTree insert (const value_type &value) const
ImmutableTree replace (const value_type &value) const
ImmutableTree remove (const key_type &key) const
ImmutableTree popMin (value_type &valueOut) const
ImmutableTree popMax (value_type &valueOut) const
iterator begin () const
iterator end () const
iterator find (const key_type &key) const
iterator lower_bound (const key_type &key) const
iterator upper_bound (const key_type &key) const
Static Public Member Functions
static size_t getAllocated ()
Static Public Attributes
static size_t allocated = 0
Private Member Functions
ImmutableTree (Node *_node)
Private Attributes
Node * node
Detailed Description
template<class K, class V, class KOV, class CMP>
class klee::ImmutableTree< K, V, KOV, CMP >
Definition at line 18 of file ImmutableTree.h.
Member Typedef Documentation
key_compare
template<class K , class V , class KOV , class CMP > typedef CMP klee::ImmutableTree< K, V, KOV, CMP >::key_compare
Definition at line 26 of file ImmutableTree.h.
key_of_value
template<class K , class V , class KOV , class CMP > typedef KOV klee::ImmutableTree< K, V, KOV, CMP >::key_of_value
Definition at line 25 of file ImmutableTree.h.
key_type
template<class K , class V , class KOV , class CMP > typedef K klee::ImmutableTree< K, V, KOV, CMP >::key_type
Definition at line 23 of file ImmutableTree.h.
value_type
template<class K , class V , class KOV , class CMP > typedef V klee::ImmutableTree< K, V, KOV, CMP >::value_type
Definition at line 24 of file ImmutableTree.h.
Constructor & Destructor Documentation
ImmutableTree() [1/3]
template<class K , class V , class KOV , class CMP > klee::ImmutableTree< K, V, KOV, CMP >::ImmutableTree
Definition at line 424 of file ImmutableTree.h.
ImmutableTree() [2/3]
template<class K , class V , class KOV , class CMP > klee::ImmutableTree< K, V, KOV, CMP >::ImmutableTree (const ImmutableTree< K, V, KOV, CMP > & s)
Definition at line 434 of file ImmutableTree.h.
~ImmutableTree()
template<class K , class V , class KOV , class CMP > klee::ImmutableTree< K, V, KOV, CMP >::~ImmutableTree
Definition at line 439 of file ImmutableTree.h.
ImmutableTree() [3/3]
template<class K , class V , class KOV , class CMP > klee::ImmutableTree< K, V, KOV, CMP >::ImmutableTree (Node * _node) private
Definition at line 429 of file ImmutableTree.h.
Member Function Documentation
begin()
template<class K , class V , class KOV , class CMP > ImmutableTree< K, V, KOV, CMP >::iterator klee::ImmutableTree< K, V, KOV, CMP >::begin inline
Definition at line 563 of file ImmutableTree.h.
Referenced by klee::ImmutableMap< K, D, CMP >::begin(), and klee::ImmutableSet< T, CMP >::begin().
count()
template<class K , class V , class KOV , class CMP > size_t klee::ImmutableTree< K, V, KOV, CMP >::count (const key_type & key) const
Definition at line 457 of file ImmutableTree.h.
References klee::ImmutableTree< K, V, KOV, CMP >::Node::isTerminator(), klee::ImmutableTree< K, V, KOV, CMP >::Node::left, klee::ImmutableTree< K, V, KOV, CMP >::Node::right, and klee::ImmutableTree< K, V, KOV, CMP >::Node::value.
Referenced by klee::ImmutableMap< K, D, CMP >::count(), and klee::ImmutableSet< T, CMP >::count().
empty()
template<class K , class V , class KOV , class CMP > bool klee::ImmutableTree< K, V, KOV, CMP >::empty
Definition at line 452 of file ImmutableTree.h.
Referenced by klee::ImmutableMap< K, D, CMP >::empty(), and klee::ImmutableSet< T, CMP >::empty().
end()
template<class K , class V , class KOV , class CMP > ImmutableTree< K, V, KOV, CMP >::iterator klee::ImmutableTree< K, V, KOV, CMP >::end inline
Definition at line 569 of file ImmutableTree.h.
Referenced by klee::ImmutableMap< K, D, CMP >::end(), and klee::ImmutableSet< T, CMP >::end().
find()
template<class K , class V , class KOV , class CMP > ImmutableTree< K, V, KOV, CMP >::iterator klee::ImmutableTree< K, V, KOV, CMP >::find (const key_type & key) const inline
Definition at line 575 of file ImmutableTree.h.
Referenced by klee::ImmutableMap< K, D, CMP >::find(), and klee::ImmutableSet< T, CMP >::find().
getAllocated()
template<class K , class V , class KOV , class CMP > static size_t klee::ImmutableTree< K, V, KOV, CMP >::getAllocated () inline static
Definition at line 60 of file ImmutableTree.h.
References klee::ImmutableTree< K, V, KOV, CMP >::allocated.
insert()
template<class K , class V , class KOV , class CMP > ImmutableTree< K, V, KOV, CMP > klee::ImmutableTree< K, V, KOV, CMP >::insert (const value_type & value) const
Definition at line 533 of file ImmutableTree.h.
Referenced by klee::ImmutableMap< K, D, CMP >::insert(), and klee::ImmutableSet< T, CMP >::insert().
lookup()
template<class K , class V , class KOV , class CMP > const ImmutableTree< K, V, KOV, CMP >::value_type * klee::ImmutableTree< K, V, KOV, CMP >::lookup (const key_type & key) const
Definition at line 474 of file ImmutableTree.h.
References klee::ImmutableTree< K, V, KOV, CMP >::Node::isTerminator(), klee::ImmutableTree< K, V, KOV, CMP >::Node::left, klee::ImmutableTree< K, V, KOV, CMP >::Node::right, and klee::ImmutableTree< K, V, KOV, CMP >::Node::value.
Referenced by klee::ImmutableMap< K, D, CMP >::lookup(), and klee::ImmutableSet< T, CMP >::lookup().
lookup_previous()
template<class K , class V , class KOV , class CMP > const ImmutableTree< K, V, KOV, CMP >::value_type * klee::ImmutableTree< K, V, KOV, CMP >::lookup_previous (const key_type & key) const
Definition at line 491 of file ImmutableTree.h.
References klee::ImmutableTree< K, V, KOV, CMP >::Node::isTerminator(), klee::ImmutableTree< K, V, KOV, CMP >::Node::left, klee::ImmutableTree< K, V, KOV, CMP >::Node::right, and klee::ImmutableTree< K, V, KOV, CMP >::Node::value.
Referenced by klee::ImmutableMap< K, D, CMP >::lookup_previous().
lower_bound()
template<class K , class V , class KOV , class CMP > ImmutableTree< K, V, KOV, CMP >::iterator klee::ImmutableTree< K, V, KOV, CMP >::lower_bound (const key_type & key) const inline
Definition at line 586 of file ImmutableTree.h.
References klee::ImmutableTree< K, V, KOV, CMP >::Node::isTerminator(), klee::ImmutableTree< K, V, KOV, CMP >::iterator::stack, and klee::ImmutableTree< K, V, KOV, CMP >::Node::value.
Referenced by klee::ImmutableMap< K, D, CMP >::lower_bound(), and klee::ImmutableSet< T, CMP >::lower_bound().
max()
template<class K , class V , class KOV , class CMP > const ImmutableTree< K, V, KOV, CMP >::value_type & klee::ImmutableTree< K, V, KOV, CMP >::max
Definition at line 519 of file ImmutableTree.h.
References klee::ImmutableTree< K, V, KOV, CMP >::Node::isTerminator(), klee::ImmutableTree< K, V, KOV, CMP >::Node::right, and klee::ImmutableTree< K, V, KOV, CMP >::Node::value.
Referenced by klee::ImmutableMap< K, D, CMP >::max(), and klee::ImmutableSet< T, CMP >::max().
min()
template<class K , class V , class KOV , class CMP > const ImmutableTree< K, V, KOV, CMP >::value_type & klee::ImmutableTree< K, V, KOV, CMP >::min
Definition at line 510 of file ImmutableTree.h.
References klee::ImmutableTree< K, V, KOV, CMP >::Node::isTerminator(), klee::ImmutableTree< K, V, KOV, CMP >::Node::left, and klee::ImmutableTree< K, V, KOV, CMP >::Node::value.
Referenced by klee::ImmutableMap< K, D, CMP >::min(), klee::ImmutableSet< T, CMP >::min(), and klee::ImmutableTree< K, V, KOV, CMP >::Node::remove().
operator=()
template<class K , class V , class KOV , class CMP > ImmutableTree< K, V, KOV, CMP > & klee::ImmutableTree< K, V, KOV, CMP >::operator= (const ImmutableTree< K, V, KOV, CMP > & s)
Definition at line 444 of file ImmutableTree.h.
References klee::ImmutableTree< K, V, KOV, CMP >::Node::decref(), klee::ImmutableTree< K, V, KOV, CMP >::Node::incref(), and klee::ImmutableTree< K, V, KOV, CMP >::node.
popMax()
template<class K , class V , class KOV , class CMP > ImmutableTree< K, V, KOV, CMP > klee::ImmutableTree< K, V, KOV, CMP >::popMax (value_type & valueOut) const
Definition at line 557 of file ImmutableTree.h.
Referenced by klee::ImmutableMap< K, D, CMP >::popMax(), and klee::ImmutableSet< T, CMP >::popMax().
popMin()
template<class K , class V , class KOV , class CMP > ImmutableTree< K, V, KOV, CMP > klee::ImmutableTree< K, V, KOV, CMP >::popMin (value_type & valueOut) const
Definition at line 551 of file ImmutableTree.h.
Referenced by klee::ImmutableMap< K, D, CMP >::popMin(), and klee::ImmutableSet< T, CMP >::popMin().
remove()
template<class K , class V , class KOV , class CMP > ImmutableTree< K, V, KOV, CMP > klee::ImmutableTree< K, V, KOV, CMP >::remove (const key_type & key) const
Definition at line 545 of file ImmutableTree.h.
Referenced by klee::ImmutableMap< K, D, CMP >::remove(), and klee::ImmutableSet< T, CMP >::remove().
replace()
template<class K , class V , class KOV , class CMP > ImmutableTree< K, V, KOV, CMP > klee::ImmutableTree< K, V, KOV, CMP >::replace (const value_type & value) const
Definition at line 539 of file ImmutableTree.h.
Referenced by klee::ImmutableMap< K, D, CMP >::replace(), and klee::ImmutableSet< T, CMP >::replace().
size()
template<class K , class V , class KOV , class CMP > size_t klee::ImmutableTree< K, V, KOV, CMP >::size
Definition at line 527 of file ImmutableTree.h.
Referenced by klee::ImmutableSet< T, CMP >::size(), and klee::ImmutableMap< K, D, CMP >::size().
upper_bound()
template<class K , class V , class KOV , class CMP > ImmutableTree< K, V, KOV, CMP >::iterator klee::ImmutableTree< K, V, KOV, CMP >::upper_bound (const key_type & key) const
Definition at line 610 of file ImmutableTree.h.
Referenced by klee::ImmutableMap< K, D, CMP >::upper_bound(), and klee::ImmutableSet< T, CMP >::upper_bound().
Member Data Documentation
allocated
template<class K , class V , class KOV , class CMP > size_t klee::ImmutableTree< K, V, KOV, CMP >::allocated = 0 static
Definition at line 20 of file ImmutableTree.h.
Referenced by klee::ImmutableMap< K, D, CMP >::getAllocated(), klee::ImmutableSet< T, CMP >::getAllocated(), klee::ImmutableTree< K, V, KOV, CMP >::getAllocated(), klee::ImmutableTree< K, V, KOV, CMP >::Node::Node(), and klee::ImmutableTree< K, V, KOV, CMP >::Node::~Node().
node
template<class K , class V , class KOV , class CMP > Node* klee::ImmutableTree< K, V, KOV, CMP >::node private
Definition at line 65 of file ImmutableTree.h.
Referenced by klee::ImmutableTree< K, V, KOV, CMP >::operator=().
The documentation for this class was generated from the following file:
/Users/cristic/klee/include/klee/ADT/ImmutableTree.h