klee: DenseSet< T > Class Template Reference
DenseSet< T > Class Template Reference
Public Member Functions
DenseSet ()
void add (T x)
void add (T start, T end)
bool add (const DenseSet &b)
bool intersects (const DenseSet &b)
std::set< unsigned >::iterator begin ()
std::set< unsigned >::iterator end ()
void print (llvm::raw_ostream &os) const
Private Types
typedef std::set< T > set_ty
Private Attributes
set_ty s
Detailed Description
template<class T>
class DenseSet< T >
Definition at line 31 of file IndependentSolver.cpp.
Member Typedef Documentation
set_ty
template<class T > typedef std::set<T> DenseSet< T >::set_ty private
Definition at line 32 of file IndependentSolver.cpp.
Constructor & Destructor Documentation
DenseSet()
template<class T > DenseSet< T >::DenseSet () inline
Definition at line 36 of file IndependentSolver.cpp.
Member Function Documentation
add() [1/3]
template<class T > bool DenseSet< T >::add (const DenseSet< T > & b) inline
Definition at line 47 of file IndependentSolver.cpp.
References DenseSet< T >::s.
add() [2/3]
template<class T > void DenseSet< T >::add (T start, T end) inline
Definition at line 41 of file IndependentSolver.cpp.
References DenseSet< T >::end(), and DenseSet< T >::s.
add() [3/3]
template<class T > void DenseSet< T >::add (T x) inline
Definition at line 38 of file IndependentSolver.cpp.
References DenseSet< T >::s.
Referenced by IndependentElementSet::IndependentElementSet().
begin()
template<class T > std::set< unsigned >::iterator DenseSet< T >::begin () inline
Definition at line 67 of file IndependentSolver.cpp.
References DenseSet< T >::s.
Referenced by IndependentSolver::computeInitialValues().
end()
template<class T > std::set< unsigned >::iterator DenseSet< T >::end () inline
Definition at line 71 of file IndependentSolver.cpp.
References DenseSet< T >::s.
Referenced by DenseSet< T >::add(), and IndependentSolver::computeInitialValues().
intersects()
template<class T > bool DenseSet< T >::intersects (const DenseSet< T > & b) inline
Definition at line 59 of file IndependentSolver.cpp.
References DenseSet< T >::s.
print()
template<class T > void DenseSet< T >::print (llvm::raw_ostream & os) const inline
Definition at line 75 of file IndependentSolver.cpp.
References DenseSet< T >::s.
Member Data Documentation
s
template<class T > set_ty DenseSet< T >::s private
Definition at line 33 of file IndependentSolver.cpp.
Referenced by DenseSet< T >::add(), DenseSet< T >::begin(), DenseSet< T >::end(), DenseSet< T >::intersects(), and DenseSet< T >::print().
The documentation for this class was generated from the following file:
/Users/cristic/klee/lib/Solver/IndependentSolver.cpp