klee: IndependentSolver Class Reference
IndependentSolver Class Reference
Public Member Functions
IndependentSolver (Solver *_solver)
~IndependentSolver ()
bool computeTruth (const Query &, bool &isValid)
bool computeValidity (const Query &, Solver::Validity &result)
bool computeValue (const Query &, ref< Expr > &result)
bool computeInitialValues (const Query &query, const std::vector< const Array * > &objects, std::vector< std::vector< unsigned char > > &values, bool &hasSolution)
SolverRunStatus getOperationStatusCode ()
getOperationStatusCode - get the status of the last solver operation
char * getConstraintLog (const Query &)
void setCoreSolverTimeout (time::Span timeout)
Public Member Functions inherited from klee::SolverImpl
SolverImpl ()
virtual ~SolverImpl ()
virtual bool computeValidity (const Query &query, Solver::Validity &result)
virtual bool computeTruth (const Query &query, bool &isValid)=0
virtual bool computeValue (const Query &query, ref< Expr > &result)=0
virtual bool computeInitialValues (const Query &query, const std::vector< const Array * > &objects, std::vector< std::vector< unsigned char > > &values, bool &hasSolution)=0
virtual SolverRunStatus getOperationStatusCode ()=0
getOperationStatusCode - get the status of the last solver operation
virtual char * getConstraintLog (const Query &query)
virtual void setCoreSolverTimeout (time::Span timeout)
Private Attributes
Solver * solver
Additional Inherited Members
Public Types inherited from klee::SolverImpl
enum SolverRunStatus {
SOLVER_RUN_STATUS_SUCCESS_SOLVABLE , SOLVER_RUN_STATUS_SUCCESS_UNSOLVABLE , SOLVER_RUN_STATUS_FAILURE , SOLVER_RUN_STATUS_TIMEOUT ,
SOLVER_RUN_STATUS_FORK_FAILED , SOLVER_RUN_STATUS_INTERRUPTED , SOLVER_RUN_STATUS_UNEXPECTED_EXIT_CODE , SOLVER_RUN_STATUS_WAITPID_FAILED
}
Static Public Member Functions inherited from klee::SolverImpl
static const char * getOperationStatusString (SolverRunStatus statusCode)
Detailed Description
Definition at line 389 of file IndependentSolver.cpp.
Constructor & Destructor Documentation
IndependentSolver()
IndependentSolver::IndependentSolver (Solver * _solver) inline
Definition at line 394 of file IndependentSolver.cpp.
~IndependentSolver()
IndependentSolver::~IndependentSolver () inline
Definition at line 396 of file IndependentSolver.cpp.
References solver.
Member Function Documentation
computeInitialValues()
bool IndependentSolver::computeInitialValues (const Query & query, const std::vector< const Array * > & objects, std::vector< std::vector< unsigned char > > & values, bool & hasSolution) virtual
See also
Solver::getInitialValues()
Implements klee::SolverImpl.
Definition at line 473 of file IndependentSolver.cpp.
References assertCreatedPointEvaluatesToTrue(), DenseSet< T >::begin(), calculateArrayReferences(), klee::SolverImpl::computeInitialValues(), DenseSet< T >::end(), getAllIndependentConstraintsSets(), klee::Solver::impl, klee::Array::size, and solver.
computeTruth()
bool IndependentSolver::computeTruth (const Query & query, bool & isValid) virtual
computeTruth - Determine whether the given query expression is provably true given the constraints.
The query expression is guaranteed to be non-constant and have bool type.
This method should evaluate the logical formula:
Where is some assignment, are the constraints in the query and is the query expression.
Parameters
[out] isValid - On success, true iff the logical formula is true.
Returns
True on success
Implements klee::SolverImpl.
Definition at line 420 of file IndependentSolver.cpp.
References klee::SolverImpl::computeTruth(), klee::Query::expr, getIndependentConstraints(), klee::Solver::impl, and solver.
computeValidity()
bool IndependentSolver::computeValidity (const Query & query, Solver::Validity & result) virtual
computeValidity - Compute a full validity result for the query.
The query expression is guaranteed to be non-constant and have bool type.
SolverImpl provides a default implementation which uses computeTruth. Clients should override this if a more efficient implementation is available.
Parameters
[out] result - if
then Solver::True, else if
then Solver::False, else Solver::Unknown
Returns
True on success
Reimplemented from klee::SolverImpl.
Definition at line 410 of file IndependentSolver.cpp.
References klee::SolverImpl::computeValidity(), klee::Query::expr, getIndependentConstraints(), klee::Solver::impl, and solver.
computeValue()
bool IndependentSolver::computeValue (const Query & query, ref< Expr > & result) virtual
computeValue - Compute a feasible value for the expression.
The query expression is guaranteed to be non-constant.
Returns
True on success
Implements klee::SolverImpl.
Definition at line 429 of file IndependentSolver.cpp.
References klee::SolverImpl::computeValue(), klee::Query::expr, getIndependentConstraints(), klee::Solver::impl, and solver.
getConstraintLog()
char * IndependentSolver::getConstraintLog (const Query & query) virtual
Reimplemented from klee::SolverImpl.
Definition at line 552 of file IndependentSolver.cpp.
References klee::SolverImpl::getConstraintLog(), klee::Solver::impl, and solver.
getOperationStatusCode()
SolverImpl::SolverRunStatus IndependentSolver::getOperationStatusCode () virtual
getOperationStatusCode - get the status of the last solver operation
Implements klee::SolverImpl.
Definition at line 548 of file IndependentSolver.cpp.
References klee::SolverImpl::getOperationStatusCode(), klee::Solver::impl, and solver.
setCoreSolverTimeout()
void IndependentSolver::setCoreSolverTimeout (time::Span timeout) virtual
Reimplemented from klee::SolverImpl.
Definition at line 556 of file IndependentSolver.cpp.
References klee::Solver::impl, klee::SolverImpl::setCoreSolverTimeout(), and solver.
Member Data Documentation
solver
Solver* IndependentSolver::solver private
Definition at line 391 of file IndependentSolver.cpp.
Referenced by computeInitialValues(), computeTruth(), computeValidity(), computeValue(), getConstraintLog(), getOperationStatusCode(), setCoreSolverTimeout(), and ~IndependentSolver().
The documentation for this class was generated from the following file:
/Users/cristic/klee/lib/Solver/IndependentSolver.cpp