klee: klee::InterpreterHandler Class Reference
klee::InterpreterHandler Class Reference abstract
#include <Interpreter.h>
Public Member Functions
InterpreterHandler ()
virtual ~InterpreterHandler ()
virtual llvm::raw_ostream & getInfoStream () const =0
virtual std::string getOutputFilename (const std::string &filename)=0
virtual std::unique_ptr< llvm::raw_fd_ostream > openOutputFile (const std::string &filename)=0
virtual void incPathsCompleted ()=0
virtual void incPathsExplored (std::uint32_t num=1)=0
virtual void processTestCase (const ExecutionState &state, const char *err, const char *suffix)=0
Detailed Description
Definition at line 33 of file Interpreter.h.
Constructor & Destructor Documentation
InterpreterHandler()
klee::InterpreterHandler::InterpreterHandler () inline
Definition at line 35 of file Interpreter.h.
~InterpreterHandler()
virtual klee::InterpreterHandler::~InterpreterHandler () inline virtual
Definition at line 36 of file Interpreter.h.
Member Function Documentation
getInfoStream()
virtual llvm::raw_ostream & klee::InterpreterHandler::getInfoStream () const pure virtual
Implemented in KleeHandler.
Referenced by klee::constructUserSearcher().
getOutputFilename()
virtual std::string klee::InterpreterHandler::getOutputFilename (const std::string & filename) pure virtual
Implemented in KleeHandler.
Referenced by klee::Executor::Executor(), klee::Executor::setModule(), and klee::StatsTracker::StatsTracker().
incPathsCompleted()
virtual void klee::InterpreterHandler::incPathsCompleted () pure virtual
Implemented in KleeHandler.
Referenced by klee::Executor::terminateStateOnExit().
incPathsExplored()
virtual void klee::InterpreterHandler::incPathsExplored (std::uint32_t num = 1) pure virtual
Implemented in KleeHandler.
Referenced by klee::Executor::doDumpStates(), and klee::Executor::terminateState().
openOutputFile()
virtual std::unique_ptr< llvm::raw_fd_ostream > klee::InterpreterHandler::openOutputFile (const std::string & filename) pure virtual
Implemented in KleeHandler.
Referenced by klee::Executor::dumpPTree(), klee::Executor::dumpStates(), klee::KModule::manifest(), and klee::StatsTracker::StatsTracker().
processTestCase()
virtual void klee::InterpreterHandler::processTestCase (const ExecutionState & state, const char * err, const char * suffix) pure virtual
Implemented in KleeHandler.
Referenced by klee::Executor::terminateStateEarly(), klee::Executor::terminateStateOnError(), and klee::Executor::terminateStateOnExit().
The documentation for this class was generated from the following file:
/Users/cristic/klee/include/klee/Core/Interpreter.h