klee: klee::ArrayValueOptReplaceVisitor Class Reference
klee::ArrayValueOptReplaceVisitor Class Reference
#include <ArrayExprVisitor.h>
Public Member Functions
ArrayValueOptReplaceVisitor (ExprHashMap< ref< Expr > > &_optimized, bool recursive=true)
Public Member Functions inherited from klee::ExprVisitor
ref< Expr > visit (const ref< Expr > &e)
Protected Member Functions
Action visitConcat (const ConcatExpr &) override
Action visitRead (const ReadExpr &re) override
Protected Member Functions inherited from klee::ExprVisitor
ExprVisitor (bool _recursive=false)
virtual ~ExprVisitor ()
virtual Action visitExpr (const Expr &)
virtual Action visitExprPost (const Expr &)
virtual Action visitNotOptimized (const NotOptimizedExpr &)
virtual Action visitRead (const ReadExpr &)
virtual Action visitSelect (const SelectExpr &)
virtual Action visitConcat (const ConcatExpr &)
virtual Action visitExtract (const ExtractExpr &)
virtual Action visitZExt (const ZExtExpr &)
virtual Action visitSExt (const SExtExpr &)
virtual Action visitAdd (const AddExpr &)
virtual Action visitSub (const SubExpr &)
virtual Action visitMul (const MulExpr &)
virtual Action visitUDiv (const UDivExpr &)
virtual Action visitSDiv (const SDivExpr &)
virtual Action visitURem (const URemExpr &)
virtual Action visitSRem (const SRemExpr &)
virtual Action visitNot (const NotExpr &)
virtual Action visitAnd (const AndExpr &)
virtual Action visitOr (const OrExpr &)
virtual Action visitXor (const XorExpr &)
virtual Action visitShl (const ShlExpr &)
virtual Action visitLShr (const LShrExpr &)
virtual Action visitAShr (const AShrExpr &)
virtual Action visitEq (const EqExpr &)
virtual Action visitNe (const NeExpr &)
virtual Action visitUlt (const UltExpr &)
virtual Action visitUle (const UleExpr &)
virtual Action visitUgt (const UgtExpr &)
virtual Action visitUge (const UgeExpr &)
virtual Action visitSlt (const SltExpr &)
virtual Action visitSle (const SleExpr &)
virtual Action visitSgt (const SgtExpr &)
virtual Action visitSge (const SgeExpr &)
Private Attributes
ExprHashMap< ref< Expr > > optimized
Detailed Description
Definition at line 114 of file ArrayExprVisitor.h.
Constructor & Destructor Documentation
ArrayValueOptReplaceVisitor()
klee::ArrayValueOptReplaceVisitor::ArrayValueOptReplaceVisitor (ExprHashMap< ref< Expr > > & _optimized, bool recursive = true) inline explicit
Definition at line 123 of file ArrayExprVisitor.h.
Member Function Documentation
visitConcat()
ExprVisitor::Action ArrayValueOptReplaceVisitor::visitConcat (const ConcatExpr & ce) override protected virtual
Reimplemented from klee::ExprVisitor.
Definition at line 245 of file ArrayExprVisitor.cpp.
References klee::ExprVisitor::Action::changeTo(), klee::ExprVisitor::Action::doChildren(), and optimized.
visitRead()
ExprVisitor::Action ArrayValueOptReplaceVisitor::visitRead (const ReadExpr & re) override protected virtual
Reimplemented from klee::ExprVisitor.
Definition at line 252 of file ArrayExprVisitor.cpp.
References klee::ExprVisitor::Action::changeTo(), klee::ExprVisitor::Action::doChildren(), and optimized.
Member Data Documentation
optimized
ExprHashMap<ref<Expr> > klee::ArrayValueOptReplaceVisitor::optimized private
Definition at line 116 of file ArrayExprVisitor.h.
Referenced by visitConcat(), and visitRead().
The documentation for this class was generated from the following files:
/Users/cristic/klee/include/klee/Expr/ArrayExprVisitor.h
/Users/cristic/klee/lib/Expr/ArrayExprVisitor.cpp