klee: klee::FixedStack< T > Class Template Reference
klee::FixedStack< T > Class Template Reference
#include <ImmutableTree.h>
Public Member Functions
FixedStack (unsigned _max)
FixedStack (const FixedStack &b)
~FixedStack ()
void push_back (const T &elt)
void pop_back ()
bool empty ()
T & back ()
FixedStack & operator= (const FixedStack &b)
bool operator== (const FixedStack &b)
bool operator!= (const FixedStack &b)
Private Attributes
unsigned pos
unsigned max
T * elts
Detailed Description
template<typename T>
class klee::FixedStack< T >
Definition at line 104 of file ImmutableTree.h.
Constructor & Destructor Documentation
FixedStack() [1/2]
template<typename T > klee::FixedStack< T >::FixedStack (unsigned _max) inline
Definition at line 109 of file ImmutableTree.h.
FixedStack() [2/2]
template<typename T > klee::FixedStack< T >::FixedStack (const FixedStack< T > & b) inline
Definition at line 112 of file ImmutableTree.h.
References klee::FixedStack< T >::elts, and klee::FixedStack< T >::pos.
~FixedStack()
template<typename T > klee::FixedStack< T >::~FixedStack () inline
Definition at line 117 of file ImmutableTree.h.
References klee::FixedStack< T >::elts.
Member Function Documentation
back()
template<typename T > T & klee::FixedStack< T >::back () inline
Definition at line 122 of file ImmutableTree.h.
References klee::FixedStack< T >::elts, and klee::FixedStack< T >::pos.
Referenced by klee::ImmutableTree< K, V, KOV, CMP >::iterator::operator*(), klee::ImmutableTree< K, V, KOV, CMP >::iterator::operator++(), klee::ImmutableTree< K, V, KOV, CMP >::iterator::operator--(), and klee::ImmutableTree< K, V, KOV, CMP >::iterator::operator->().
empty()
template<typename T > bool klee::FixedStack< T >::empty () inline
Definition at line 121 of file ImmutableTree.h.
References klee::FixedStack< T >::pos.
Referenced by klee::ImmutableTree< K, V, KOV, CMP >::iterator::operator++(), and klee::ImmutableTree< K, V, KOV, CMP >::iterator::operator--().
operator!=()
template<typename T > bool klee::FixedStack< T >::operator!= (const FixedStack< T > & b) inline
Definition at line 136 of file ImmutableTree.h.
operator=()
template<typename T > FixedStack & klee::FixedStack< T >::operator= (const FixedStack< T > & b) inline
Definition at line 125 of file ImmutableTree.h.
References klee::FixedStack< T >::elts, klee::FixedStack< T >::max, and klee::FixedStack< T >::pos.
operator==()
template<typename T > bool klee::FixedStack< T >::operator== (const FixedStack< T > & b) inline
Definition at line 132 of file ImmutableTree.h.
References klee::FixedStack< T >::elts, and klee::FixedStack< T >::pos.
pop_back()
template<typename T > void klee::FixedStack< T >::pop_back () inline
Definition at line 120 of file ImmutableTree.h.
References klee::FixedStack< T >::pos.
Referenced by klee::ImmutableTree< K, V, KOV, CMP >::iterator::operator++(), and klee::ImmutableTree< K, V, KOV, CMP >::iterator::operator--().
push_back()
template<typename T > void klee::FixedStack< T >::push_back (const T & elt) inline
Definition at line 119 of file ImmutableTree.h.
References klee::FixedStack< T >::elts, and klee::FixedStack< T >::pos.
Referenced by klee::ImmutableTree< K, V, KOV, CMP >::iterator::iterator(), klee::ImmutableTree< K, V, KOV, CMP >::iterator::operator++(), and klee::ImmutableTree< K, V, KOV, CMP >::iterator::operator--().
Member Data Documentation
elts
template<typename T > T* klee::FixedStack< T >::elts private
Definition at line 106 of file ImmutableTree.h.
Referenced by klee::FixedStack< T >::back(), klee::FixedStack< T >::FixedStack(), klee::FixedStack< T >::operator=(), klee::FixedStack< T >::operator==(), klee::FixedStack< T >::push_back(), and klee::FixedStack< T >::~FixedStack().
max
template<typename T > unsigned klee::FixedStack< T >::max private
Definition at line 105 of file ImmutableTree.h.
Referenced by klee::FixedStack< T >::operator=().
pos
template<typename T > unsigned klee::FixedStack< T >::pos private
Definition at line 105 of file ImmutableTree.h.
Referenced by klee::FixedStack< T >::back(), klee::FixedStack< T >::empty(), klee::FixedStack< T >::FixedStack(), klee::FixedStack< T >::operator=(), klee::FixedStack< T >::operator==(), klee::FixedStack< T >::pop_back(), and klee::FixedStack< T >::push_back().
The documentation for this class was generated from the following file:
/Users/cristic/klee/include/klee/ADT/ImmutableTree.h