klee: klee::ReadExpr Class Reference
klee::ReadExpr Class Reference
Class representing a one byte read from an array.
#include <Expr.h>
Public Member Functions
Width getWidth () const
Kind getKind () const
unsigned getNumKids () const
ref< Expr > getKid (unsigned i) const
int compareContents (const Expr &b) const
virtual ref< Expr > rebuild (ref< Expr > kids[]) const
virtual unsigned computeHash ()
Public Member Functions inherited from klee::Expr
Expr ()
virtual ~Expr ()
virtual Kind getKind () const =0
virtual Width getWidth () const =0
virtual unsigned getNumKids () const =0
virtual ref< Expr > getKid (unsigned i) const =0
virtual void print (llvm::raw_ostream &os) const
void dump () const
dump - Print the expression to stderr.
virtual unsigned hash () const
Returns the pre-computed hash of the current expression.
virtual unsigned computeHash ()
int compare (const Expr &b) const
virtual ref< Expr > rebuild (ref< Expr > kids[]) const =0
bool isZero () const
isZero - Is this a constant zero.
bool isTrue () const
isTrue - Is this the true expression.
bool isFalse () const
isFalse - Is this the false expression.
Static Public Member Functions
static ref< Expr > alloc (const UpdateList &updates, const ref< Expr > &index)
static ref< Expr > create (const UpdateList &updates, ref< Expr > i)
static bool classof (const Expr *E)
static bool classof (const ReadExpr *)
Static Public Member Functions inherited from klee::NonConstantExpr
static bool classof (const Expr *E)
static bool classof (const NonConstantExpr *)
Static Public Member Functions inherited from klee::Expr
static void printKind (llvm::raw_ostream &os, Kind k)
static void printWidth (llvm::raw_ostream &os, Expr::Width w)
static unsigned getMinBytesForWidth (Width w)
returns the smallest number of bytes in which the given width fits
static ref< Expr > createSExtToPointerWidth (ref< Expr > e)
static ref< Expr > createZExtToPointerWidth (ref< Expr > e)
static ref< Expr > createImplies (ref< Expr > hyp, ref< Expr > conc)
static ref< Expr > createIsZero (ref< Expr > e)
static ref< Expr > createTempRead (const Array *array, Expr::Width w)
static ref< ConstantExpr > createPointer (uint64_t v)
static ref< Expr > createFromKind (Kind k, std::vector< CreateArg > args)
static bool isValidKidWidth (unsigned kid, Width w)
static bool needsResultType ()
static bool classof (const Expr *)
Public Attributes
UpdateList updates
ref< Expr > index
Public Attributes inherited from klee::Expr
class ReferenceCounter _refCount
Required by klee::ref-managed objects.
Static Public Attributes
static const Kind kind = Read
static const unsigned numKids = 1
Static Public Attributes inherited from klee::Expr
static unsigned count = 0
static const unsigned MAGIC_HASH_CONSTANT = 39
static const Width InvalidWidth = 0
static const Width Bool = 1
static const Width Int8 = 8
static const Width Int16 = 16
static const Width Int32 = 32
static const Width Int64 = 64
static const Width Fl80 = 80
Private Member Functions
ReadExpr (const UpdateList &_updates, const ref< Expr > &_index)
Additional Inherited Members
Public Types inherited from klee::Expr
enum Kind {
InvalidKind = -1 , Constant = 0 , NotOptimized , Read =NotOptimized+2 ,
Select , Concat , Extract , ZExt ,
SExt , Not , Add , Sub ,
Mul , UDiv , SDiv , URem ,
SRem , And , Or , Xor ,
Shl , LShr , AShr , Eq ,
Ne , Ult , Ule , Ugt ,
Uge , Slt , Sle , Sgt ,
Sge , LastKind =Sge , CastKindFirst =ZExt , CastKindLast =SExt ,
BinaryKindFirst =Add , BinaryKindLast =Sge , CmpKindFirst =Eq , CmpKindLast =Sge
}
typedef unsigned Width
The type of an expression is simply its width, in bits.
virtual int compareContents (const Expr &b) const =0
Protected Attributes inherited from klee::Expr
unsigned hashValue
Detailed Description
Class representing a one byte read from an array.
Definition at line 565 of file Expr.h.
Constructor & Destructor Documentation
ReadExpr()
klee::ReadExpr::ReadExpr (const UpdateList & _updates, const ref< Expr > & _index) inline private
Definition at line 598 of file Expr.h.
References klee::UpdateList::root, and updates.
Referenced by alloc().
Member Function Documentation
alloc()
static ref< Expr > klee::ReadExpr::alloc (const UpdateList & updates, const ref< Expr > & index) inline static
Definition at line 575 of file Expr.h.
References klee::Expr::computeHash(), index, ReadExpr(), and updates.
Referenced by create().
classof() [1/2]
static bool klee::ReadExpr::classof (const Expr * E) inline static
Definition at line 602 of file Expr.h.
References klee::Expr::getKind(), and klee::Expr::Read.
classof() [2/2]
static bool klee::ReadExpr::classof (const ReadExpr *) inline static
Definition at line 605 of file Expr.h.
compareContents()
int ReadExpr::compareContents (const Expr & b) const virtual
Compares b to this Expr and determines how they are ordered (ignoring their kid expressions - i.e. those returned by getKid()).
Typically this requires comparing internal attributes of the Expr.
Implementations can assume that b and this are of the same kind.
This method effectively defines a partial order over Expr of the same kind (partial because kid Expr are not compared).
This method should not be called directly. Instead compare() should be used.
Parameters
[in] b Expr to compare this to.
Returns
One of the following values:
-1 if this is < b ignoring kid expressions.
1 if this is > b ignoring kid expressions.
0 if this and b are not ordered.
< and > are binary relations that express the partial order.
Implements klee::Expr.
Definition at line 588 of file Expr.cpp.
References klee::UpdateList::compare(), and updates.
computeHash()
unsigned ReadExpr::computeHash () virtual
(Re)computes the hash of the current expression. Returns the hash value.
Reimplemented from klee::Expr.
Definition at line 218 of file Expr.cpp.
References klee::Expr::hash(), klee::UpdateList::hash(), klee::Expr::hashValue, index, klee::Expr::MAGIC_HASH_CONSTANT, and updates.
create()
ref< Expr > ReadExpr::create (const UpdateList & updates, ref< Expr > i) static
Definition at line 538 of file Expr.cpp.
References alloc(), klee::Array::constantValues, klee::UpdateList::head, index, klee::Array::isConstantArray(), klee::UpdateList::root, and klee::Array::size.
Referenced by klee::ValidatingSolver::computeInitialValues(), klee::Assignment::createConstraintsFromAssignment(), klee::Expr::createTempRead(), klee::ExprEvaluator::evalRead(), klee::Assignment::evaluate(), klee::SeedInfo::patchSeed(), klee::ObjectState::read8(), and rebuild().
getKid()
ref< Expr > klee::ReadExpr::getKid (unsigned i) const inline virtual
Implements klee::Expr.
Definition at line 587 of file Expr.h.
References index.
getKind()
Kind klee::ReadExpr::getKind () const inline virtual
Implements klee::Expr.
Definition at line 584 of file Expr.h.
References klee::Expr::Read.
getNumKids()
unsigned klee::ReadExpr::getNumKids () const inline virtual
Implements klee::Expr.
Definition at line 586 of file Expr.h.
References numKids.
getWidth()
Width klee::ReadExpr::getWidth () const inline virtual
Implements klee::Expr.
Definition at line 583 of file Expr.h.
References klee::Array::getRange(), klee::UpdateList::root, and updates.
Referenced by klee::ExprRangeEvaluator< T >::evaluate(), klee::ArrayExprHelper::hasOrderedReads(), klee::AssignmentGenerator::hasOrderedReads(), PPrinter::hasOrderedReads(), klee::ArrayExprHelper::isReadExprAtOffset(), klee::AssignmentGenerator::isReadExprAtOffset(), PPrinter::isReadExprAtOffset(), and klee::ArrayReadExprVisitor::visitRead().
rebuild()
virtual ref< Expr > klee::ReadExpr::rebuild (ref< Expr > kids[]) const inline virtual
Implements klee::Expr.
Definition at line 591 of file Expr.h.
References create(), and updates.
Member Data Documentation
index
ref<Expr> klee::ReadExpr::index
Definition at line 572 of file Expr.h.
Referenced by alloc(), klee::ExprOptimizer::buildMixedSelectExpr(), klee::ImpliedValue::checkForImpliedValues(), computeHash(), create(), klee::Executor::doImpliedValueConcretization(), klee::ExprRangeEvaluator< T >::evaluate(), getKid(), klee::ArrayExprHelper::hasOrderedReads(), klee::AssignmentGenerator::hasOrderedReads(), PPrinter::hasOrderedReads(), klee::AssignmentGenerator::helperGenerateAssignment(), IndependentElementSet::IndependentElementSet(), klee::ArrayReadExprVisitor::inspectRead(), klee::ArrayExprHelper::isReadExprAtOffset(), klee::AssignmentGenerator::isReadExprAtOffset(), PPrinter::isReadExprAtOffset(), klee::SeedInfo::patchSeed(), PPrinter::printRead(), CexData::propogateExactValues(), CexData::propogatePossibleValues(), TryConstArrayOpt(), klee::ConstantArrayExprVisitor::visitConcat(), klee::ConstantArrayExprVisitor::visitRead(), klee::IndexCompatibilityExprVisitor::visitRead(), and klee::ExprEvaluator::visitRead().
kind
const Kind klee::ReadExpr::kind = Read static
Definition at line 567 of file Expr.h.
numKids
const unsigned klee::ReadExpr::numKids = 1 static
Definition at line 568 of file Expr.h.
Referenced by getNumKids().
updates
UpdateList klee::ReadExpr::updates
Definition at line 571 of file Expr.h.
Referenced by alloc(), klee::ExprOptimizer::buildMixedSelectExpr(), klee::ImpliedValue::checkForImpliedValues(), compareContents(), computeHash(), klee::ExprRangeEvaluator< T >::evaluate(), getWidth(), klee::AssignmentGenerator::helperGenerateAssignment(), IndependentElementSet::IndependentElementSet(), klee::ArrayReadExprVisitor::inspectRead(), klee::SeedInfo::patchSeed(), PPrinter::printRead(), CexData::propogateExactValues(), CexData::propogatePossibleValues(), ReadExpr(), rebuild(), TryConstArrayOpt(), klee::ConstantArrayExprVisitor::visitConcat(), klee::ConstantArrayExprVisitor::visitRead(), klee::IndexCompatibilityExprVisitor::visitRead(), klee::ExprEvaluator::visitRead(), klee::ConstantArrayFinder::visitRead(), and klee::SymbolicObjectFinder::visitRead().
The documentation for this class was generated from the following files:
/Users/cristic/klee/include/klee/Expr/Expr.h
/Users/cristic/klee/lib/Expr/Expr.cpp