klee: klee::ExprVisitor Class Reference
klee::ExprVisitor Class Reference
#include <ExprVisitor.h>
Classes
class Action
Public Member Functions
ref< Expr > visit (const ref< Expr > &e)
Protected Member Functions
ExprVisitor (bool _recursive=false)
virtual ~ExprVisitor ()
virtual Action visitExpr (const Expr &)
virtual Action visitExprPost (const Expr &)
virtual Action visitNotOptimized (const NotOptimizedExpr &)
virtual Action visitRead (const ReadExpr &)
virtual Action visitSelect (const SelectExpr &)
virtual Action visitConcat (const ConcatExpr &)
virtual Action visitExtract (const ExtractExpr &)
virtual Action visitZExt (const ZExtExpr &)
virtual Action visitSExt (const SExtExpr &)
virtual Action visitAdd (const AddExpr &)
virtual Action visitSub (const SubExpr &)
virtual Action visitMul (const MulExpr &)
virtual Action visitUDiv (const UDivExpr &)
virtual Action visitSDiv (const SDivExpr &)
virtual Action visitURem (const URemExpr &)
virtual Action visitSRem (const SRemExpr &)
virtual Action visitNot (const NotExpr &)
virtual Action visitAnd (const AndExpr &)
virtual Action visitOr (const OrExpr &)
virtual Action visitXor (const XorExpr &)
virtual Action visitShl (const ShlExpr &)
virtual Action visitLShr (const LShrExpr &)
virtual Action visitAShr (const AShrExpr &)
virtual Action visitEq (const EqExpr &)
virtual Action visitNe (const NeExpr &)
virtual Action visitUlt (const UltExpr &)
virtual Action visitUle (const UleExpr &)
virtual Action visitUgt (const UgtExpr &)
virtual Action visitUge (const UgeExpr &)
virtual Action visitSlt (const SltExpr &)
virtual Action visitSle (const SleExpr &)
virtual Action visitSgt (const SgtExpr &)
virtual Action visitSge (const SgeExpr &)
Private Types
typedef ExprHashMap< ref< Expr > > visited_ty
Private Member Functions
ref< Expr > visitActual (const ref< Expr > &e)
Private Attributes
visited_ty visited
bool recursive
Detailed Description
Definition at line 16 of file ExprVisitor.h.
Member Typedef Documentation
visited_ty
typedef ExprHashMap< ref<Expr> > klee::ExprVisitor::visited_ty private
Definition at line 84 of file ExprVisitor.h.
Constructor & Destructor Documentation
ExprVisitor()
klee::ExprVisitor::ExprVisitor (bool _recursive = false) inline explicit protected
Definition at line 45 of file ExprVisitor.h.
~ExprVisitor()
virtual klee::ExprVisitor::~ExprVisitor () inline protected virtual
Definition at line 46 of file ExprVisitor.h.
Member Function Documentation
visit()
ref< Expr > ExprVisitor::visit (const ref< Expr > & e)
Definition at line 26 of file ExprVisitor.cpp.
References visitActual(), and visited.
Referenced by klee::ExprOptimizer::computeIndexes(), klee::ExprEvaluator::evalRead(), klee::Assignment::evaluate(), CexData::evaluateExact(), CexData::evaluatePossible(), klee::findSymbolicObjects(), klee::ExprOptimizer::getSelectOptExpr(), klee::ExprOptimizer::optimizeExpr(), klee::ExprEvaluator::protectedDivOperation(), klee::ExprRewriter::rewrite(), klee::ConstraintManager::rewriteConstraints(), klee::Assignment::satisfies(), klee::ConstraintManager::simplifyExpr(), visitActual(), klee::ConstantArrayExprVisitor::visitConcat(), klee::ConstantArrayExprVisitor::visitRead(), klee::ExprEvaluator::visitRead(), klee::ConstantArrayFinder::visitRead(), and klee::SymbolicObjectFinder::visitRead().
visitActual()
ref< Expr > ExprVisitor::visitActual (const ref< Expr > & e) private
Definition at line 42 of file ExprVisitor.cpp.
References klee::Expr::Add, klee::Expr::And, klee::ExprVisitor::Action::argument, klee::Expr::AShr, klee::ExprVisitor::Action::ChangeTo, klee::Expr::Concat, klee::Expr::Constant, klee::ExprVisitor::Action::DoChildren, klee::Expr::Eq, klee::Expr::Extract, klee::ref< T >::get(), klee::Expr::getKid(), klee::Expr::getKind(), klee::Expr::getNumKids(), klee::ExprVisitor::Action::kind, klee::Expr::LShr, klee::Expr::Mul, klee::Expr::Ne, klee::Expr::Not, klee::Expr::NotOptimized, klee::Expr::Or, klee::Expr::Read, klee::Expr::rebuild(), recursive, klee::Expr::SDiv, klee::Expr::Select, klee::Expr::SExt, klee::Expr::Sge, klee::Expr::Sgt, klee::Expr::Shl, klee::ExprVisitor::Action::SkipChildren, klee::Expr::Sle, klee::Expr::Slt, klee::Expr::SRem, klee::Expr::Sub, klee::Expr::UDiv, klee::Expr::Uge, klee::Expr::Ugt, klee::Expr::Ule, klee::Expr::Ult, klee::Expr::URem, visit(), visitAdd(), visitAnd(), visitAShr(), visitConcat(), visitEq(), visitExpr(), visitExprPost(), visitExtract(), visitLShr(), visitMul(), visitNe(), visitNot(), visitNotOptimized(), visitOr(), visitRead(), visitSDiv(), visitSelect(), visitSExt(), visitSge(), visitSgt(), visitShl(), visitSle(), visitSlt(), visitSRem(), visitSub(), visitUDiv(), visitUge(), visitUgt(), visitUle(), visitUlt(), visitURem(), visitXor(), visitZExt(), klee::Expr::Xor, and klee::Expr::ZExt.
Referenced by visit().
visitAdd()
ExprVisitor::Action ExprVisitor::visitAdd (const AddExpr &) protected virtual
Definition at line 165 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitAnd()
ExprVisitor::Action ExprVisitor::visitAnd (const AndExpr &) protected virtual
Definition at line 197 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitAShr()
ExprVisitor::Action ExprVisitor::visitAShr (const AShrExpr &) protected virtual
Definition at line 217 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitConcat()
ExprVisitor::Action ExprVisitor::visitConcat (const ConcatExpr &) protected virtual
Reimplemented in klee::ConstantArrayExprVisitor, klee::IndexTransformationExprVisitor, klee::ArrayReadExprVisitor, and klee::ArrayValueOptReplaceVisitor.
Definition at line 149 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitEq()
ExprVisitor::Action ExprVisitor::visitEq (const EqExpr &) protected virtual
Definition at line 221 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitExpr()
ExprVisitor::Action ExprVisitor::visitExpr (const Expr &) protected virtual
Reimplemented in klee::ExprEvaluator, and ExprReplaceVisitor.
Definition at line 129 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitExprPost()
ExprVisitor::Action ExprVisitor::visitExprPost (const Expr &) protected virtual
Reimplemented in klee::ExprEvaluator, ExprReplaceVisitor, and ExprReplaceVisitor2.
Definition at line 133 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::skipChildren().
Referenced by visitActual().
visitExtract()
ExprVisitor::Action ExprVisitor::visitExtract (const ExtractExpr &) protected virtual
Definition at line 153 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitLShr()
ExprVisitor::Action ExprVisitor::visitLShr (const LShrExpr &) protected virtual
Definition at line 213 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitMul()
ExprVisitor::Action ExprVisitor::visitMul (const MulExpr &) protected virtual
Reimplemented in klee::IndexTransformationExprVisitor.
Definition at line 173 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitNe()
ExprVisitor::Action ExprVisitor::visitNe (const NeExpr &) protected virtual
Definition at line 225 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitNot()
ExprVisitor::Action ExprVisitor::visitNot (const NotExpr &) protected virtual
Definition at line 193 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitNotOptimized()
ExprVisitor::Action ExprVisitor::visitNotOptimized (const NotOptimizedExpr &) protected virtual
Definition at line 137 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitOr()
ExprVisitor::Action ExprVisitor::visitOr (const OrExpr &) protected virtual
Reimplemented in klee::IndexCompatibilityExprVisitor.
Definition at line 201 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitRead()
ExprVisitor::Action ExprVisitor::visitRead (const ReadExpr &) protected virtual
Reimplemented in klee::ConstantArrayExprVisitor, klee::IndexCompatibilityExprVisitor, klee::ArrayReadExprVisitor, klee::ExprEvaluator, klee::ConstantArrayFinder, klee::SymbolicObjectFinder, and klee::ArrayValueOptReplaceVisitor.
Definition at line 141 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitSDiv()
ExprVisitor::Action ExprVisitor::visitSDiv (const SDivExpr &) protected virtual
Reimplemented in klee::ExprEvaluator.
Definition at line 181 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitSelect()
ExprVisitor::Action ExprVisitor::visitSelect (const SelectExpr &) protected virtual
Definition at line 145 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitSExt()
ExprVisitor::Action ExprVisitor::visitSExt (const SExtExpr &) protected virtual
Definition at line 161 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitSge()
ExprVisitor::Action ExprVisitor::visitSge (const SgeExpr &) protected virtual
Definition at line 257 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitSgt()
ExprVisitor::Action ExprVisitor::visitSgt (const SgtExpr &) protected virtual
Definition at line 253 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitShl()
ExprVisitor::Action ExprVisitor::visitShl (const ShlExpr &) protected virtual
Definition at line 209 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitSle()
ExprVisitor::Action ExprVisitor::visitSle (const SleExpr &) protected virtual
Definition at line 249 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitSlt()
ExprVisitor::Action ExprVisitor::visitSlt (const SltExpr &) protected virtual
Definition at line 245 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitSRem()
ExprVisitor::Action ExprVisitor::visitSRem (const SRemExpr &) protected virtual
Reimplemented in klee::IndexCompatibilityExprVisitor, and klee::ExprEvaluator.
Definition at line 189 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitSub()
ExprVisitor::Action ExprVisitor::visitSub (const SubExpr &) protected virtual
Definition at line 169 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitUDiv()
ExprVisitor::Action ExprVisitor::visitUDiv (const UDivExpr &) protected virtual
Reimplemented in klee::ExprEvaluator.
Definition at line 177 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitUge()
ExprVisitor::Action ExprVisitor::visitUge (const UgeExpr &) protected virtual
Definition at line 241 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitUgt()
ExprVisitor::Action ExprVisitor::visitUgt (const UgtExpr &) protected virtual
Definition at line 237 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitUle()
ExprVisitor::Action ExprVisitor::visitUle (const UleExpr &) protected virtual
Definition at line 233 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitUlt()
ExprVisitor::Action ExprVisitor::visitUlt (const UltExpr &) protected virtual
Definition at line 229 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitURem()
ExprVisitor::Action ExprVisitor::visitURem (const URemExpr &) protected virtual
Reimplemented in klee::IndexCompatibilityExprVisitor, and klee::ExprEvaluator.
Definition at line 185 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitXor()
ExprVisitor::Action ExprVisitor::visitXor (const XorExpr &) protected virtual
Definition at line 205 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
visitZExt()
ExprVisitor::Action ExprVisitor::visitZExt (const ZExtExpr &) protected virtual
Definition at line 157 of file ExprVisitor.cpp.
References klee::ExprVisitor::Action::doChildren().
Referenced by visitActual().
Member Data Documentation
recursive
bool klee::ExprVisitor::recursive private
Definition at line 86 of file ExprVisitor.h.
Referenced by visitActual().
visited
visited_ty klee::ExprVisitor::visited private
Definition at line 85 of file ExprVisitor.h.
Referenced by visit().
The documentation for this class was generated from the following files:
/Users/cristic/klee/include/klee/Expr/ExprVisitor.h
/Users/cristic/klee/lib/Expr/ExprVisitor.cpp