klee: klee::IntrinsicCleanerPass Class Reference
klee::IntrinsicCleanerPass Class Reference
#include <Passes.h>
Inherits llvm::ModulePass.
Public Member Functions
IntrinsicCleanerPass (const llvm::DataLayout &TD)
~IntrinsicCleanerPass ()
bool runOnModule (llvm::Module &M) override
Private Member Functions
bool runOnBasicBlock (llvm::BasicBlock &b, llvm::Module &M)
Private Attributes
const llvm::DataLayout & DataLayout
llvm::IntrinsicLowering * IL
Static Private Attributes
static char ID
Detailed Description
Definition at line 58 of file Passes.h.
Constructor & Destructor Documentation
IntrinsicCleanerPass()
klee::IntrinsicCleanerPass::IntrinsicCleanerPass (const llvm::DataLayout & TD) inline
Definition at line 66 of file Passes.h.
~IntrinsicCleanerPass()
klee::IntrinsicCleanerPass::~IntrinsicCleanerPass () inline
Definition at line 69 of file Passes.h.
References IL.
Member Function Documentation
runOnBasicBlock()
bool klee::IntrinsicCleanerPass::runOnBasicBlock (llvm::BasicBlock & b, llvm::Module & M) private
Definition at line 52 of file IntrinsicCleaner.cpp.
References DataLayout, IL, klee::klee_warning_once(), and klee::floats::trunc().
Referenced by runOnModule().
runOnModule()
bool klee::IntrinsicCleanerPass::runOnModule (llvm::Module & M) override
Definition at line 39 of file IntrinsicCleaner.cpp.
References runOnBasicBlock().
Member Data Documentation
DataLayout
const llvm::DataLayout& klee::IntrinsicCleanerPass::DataLayout private
Definition at line 60 of file Passes.h.
Referenced by runOnBasicBlock().
ID
char klee::IntrinsicCleanerPass::ID static private
Definition at line 59 of file Passes.h.
IL
llvm::IntrinsicLowering* klee::IntrinsicCleanerPass::IL private
Definition at line 61 of file Passes.h.
Referenced by runOnBasicBlock(), and ~IntrinsicCleanerPass().
The documentation for this class was generated from the following files:
/Users/cristic/klee/lib/Module/Passes.h
/Users/cristic/klee/lib/Module/IntrinsicCleaner.cpp