klee: klee::StatisticManager Class Reference
klee::StatisticManager Class Reference
#include <Statistics.h>
Public Member Functions
StatisticManager ()
~StatisticManager ()
void useIndexedStats (unsigned totalIndices)
StatisticRecord * getContext ()
void setContext (StatisticRecord *sr)
void setIndex (unsigned i)
unsigned getIndex ()
unsigned getNumStatistics ()
Statistic & getStatistic (unsigned i)
void registerStatistic (Statistic &s)
void incrementStatistic (Statistic &s, uint64_t addend)
uint64_t getValue (const Statistic &s) const
void incrementIndexedValue (const Statistic &s, unsigned index, uint64_t addend) const
uint64_t getIndexedValue (const Statistic &s, unsigned index) const
void setIndexedValue (const Statistic &s, unsigned index, uint64_t value)
int getStatisticID (const std::string &name) const
Statistic * getStatisticByName (const std::string &name) const
Private Attributes
bool enabled
std::vector< Statistic * > stats
uint64_t * globalStats
uint64_t * indexedStats
StatisticRecord * contextStats
unsigned index
Detailed Description
Definition at line 40 of file Statistics.h.
Constructor & Destructor Documentation
StatisticManager()
StatisticManager::StatisticManager ()
Definition at line 16 of file Statistics.cpp.
~StatisticManager()
StatisticManager::~StatisticManager ()
Definition at line 24 of file Statistics.cpp.
References globalStats, and indexedStats.
Member Function Documentation
getContext()
StatisticRecord * klee::StatisticManager::getContext () inline
Definition at line 88 of file Statistics.h.
References contextStats.
getIndex()
unsigned klee::StatisticManager::getIndex () inline
Definition at line 59 of file Statistics.h.
References index.
Referenced by klee::StatsTracker::markBranchVisited(), and klee::Executor::maxStaticPctChecks().
getIndexedValue()
uint64_t klee::StatisticManager::getIndexedValue (const Statistic & s, unsigned index) const inline
Definition at line 142 of file Statistics.h.
References klee::Statistic::id, index, indexedStats, and stats.
Referenced by klee::computeMinDistToUncovered(), klee::StatsTracker::computeReachableUncovered(), klee::Executor::dumpStates(), klee::WeightedRandomSearcher::getWeight(), klee::StatsTracker::markBranchVisited(), klee::Executor::maxStaticPctChecks(), klee::StatsTracker::stepInstruction(), and klee::StatsTracker::writeIStats().
getNumStatistics()
unsigned klee::StatisticManager::getNumStatistics () inline
Definition at line 60 of file Statistics.h.
References stats.
Referenced by klee::StatisticRecord::operator+=(), klee::StatisticRecord::operator=(), klee::StatisticRecord::StatisticRecord(), klee::StatsTracker::writeIStats(), and klee::StatisticRecord::zero().
getStatistic()
Statistic & klee::StatisticManager::getStatistic (unsigned i) inline
Definition at line 61 of file Statistics.h.
References stats.
Referenced by klee::StatsTracker::writeIStats().
getStatisticByName()
Statistic * StatisticManager::getStatisticByName (const std::string & name) const
Definition at line 50 of file Statistics.cpp.
References stats.
Referenced by EvaluateInputAST(), main(), and QueryLoggingSolver::startQuery().
getStatisticID()
int StatisticManager::getStatisticID (const std::string & name) const
Definition at line 43 of file Statistics.cpp.
References stats.
Referenced by klee::StatsTracker::writeIStats().
getValue()
uint64_t klee::StatisticManager::getValue (const Statistic & s) const inline
Definition at line 132 of file Statistics.h.
References globalStats, and klee::Statistic::id.
Referenced by klee::Statistic::getValue().
incrementIndexedValue()
void klee::StatisticManager::incrementIndexedValue (const Statistic & s, unsigned index, uint64_t addend) const inline
Definition at line 136 of file Statistics.h.
References klee::Statistic::id, index, indexedStats, and stats.
Referenced by klee::StatsTracker::updateStateStatistics().
incrementStatistic()
void klee::StatisticManager::incrementStatistic (Statistic & s, uint64_t addend) inline
Definition at line 76 of file Statistics.h.
References contextStats, klee::StatisticRecord::data, enabled, globalStats, klee::Statistic::id, index, indexedStats, and stats.
Referenced by klee::Statistic::operator+=().
registerStatistic()
void StatisticManager::registerStatistic (Statistic & s)
Definition at line 35 of file Statistics.cpp.
References globalStats, klee::Statistic::id, and stats.
Referenced by klee::Statistic::Statistic().
setContext()
void klee::StatisticManager::setContext (StatisticRecord * sr) inline
Definition at line 91 of file Statistics.h.
References contextStats.
Referenced by klee::StatsTracker::stepInstruction().
setIndex()
void klee::StatisticManager::setIndex (unsigned i) inline
Definition at line 58 of file Statistics.h.
References index.
Referenced by klee::StatsTracker::StatsTracker(), and klee::StatsTracker::stepInstruction().
setIndexedValue()
void klee::StatisticManager::setIndexedValue (const Statistic & s, unsigned index, uint64_t value) inline
Definition at line 147 of file Statistics.h.
References klee::Statistic::id, index, indexedStats, and stats.
Referenced by klee::StatsTracker::computeReachableUncovered().
useIndexedStats()
void StatisticManager::useIndexedStats (unsigned totalIndices)
Definition at line 29 of file Statistics.cpp.
References indexedStats, and stats.
Referenced by klee::StatsTracker::StatsTracker().
Member Data Documentation
contextStats
StatisticRecord* klee::StatisticManager::contextStats private
Definition at line 46 of file Statistics.h.
Referenced by getContext(), incrementStatistic(), and setContext().
enabled
bool klee::StatisticManager::enabled private
Definition at line 42 of file Statistics.h.
Referenced by incrementStatistic().
globalStats
uint64_t* klee::StatisticManager::globalStats private
Definition at line 44 of file Statistics.h.
Referenced by getValue(), incrementStatistic(), registerStatistic(), and ~StatisticManager().
index
unsigned klee::StatisticManager::index private
Definition at line 47 of file Statistics.h.
Referenced by getIndex(), getIndexedValue(), incrementIndexedValue(), incrementStatistic(), setIndex(), and setIndexedValue().
indexedStats
uint64_t* klee::StatisticManager::indexedStats private
Definition at line 45 of file Statistics.h.
Referenced by getIndexedValue(), incrementIndexedValue(), incrementStatistic(), setIndexedValue(), useIndexedStats(), and ~StatisticManager().
stats
std::vector<Statistic*> klee::StatisticManager::stats private
Definition at line 43 of file Statistics.h.
Referenced by getIndexedValue(), getNumStatistics(), getStatistic(), getStatisticByName(), getStatisticID(), incrementIndexedValue(), incrementStatistic(), registerStatistic(), setIndexedValue(), and useIndexedStats().
The documentation for this class was generated from the following files:
/Users/cristic/klee/include/klee/Statistics/Statistics.h
/Users/cristic/klee/lib/Basic/Statistics.cpp