klee: /Users/cristic/klee/include/klee/ADT/KTest.h File Reference
KTest.h File Reference
Classes
struct KTestObject
struct KTest
Typedefs
typedef struct KTestObject KTestObject
typedef struct KTest KTest
Functions
unsigned kTest_getCurrentVersion ()
int kTest_isKTestFile (const char *path)
KTest * kTest_fromFile (const char *path)
int kTest_toFile (KTest *, const char *path)
unsigned kTest_numBytes (KTest *)
void kTest_free (KTest *)
Typedef Documentation
KTest
typedef struct KTest KTest
Definition at line 24 of file KTest.h.
KTestObject
typedef struct KTestObject KTestObject
Definition at line 17 of file KTest.h.
Function Documentation
kTest_free()
void kTest_free (KTest * bo)
Definition at line 229 of file KTest.cpp.
References KTest::args, KTestObject::bytes, KTestObject::name, KTest::numArgs, KTest::numObjects, and KTest::objects.
Referenced by main().
kTest_fromFile()
KTest * kTest_fromFile (const char * path)
Definition at line 94 of file KTest.cpp.
References KTest::args, KTestObject::bytes, kTest_checkHeader(), kTest_getCurrentVersion(), KTestObject::name, KTest::numArgs, KTestObject::numBytes, KTest::numObjects, KTest::objects, read_string(), read_uint32(), KTest::symArgvLen, KTest::symArgvs, and KTest::version.
Referenced by main().
kTest_getCurrentVersion()
unsigned kTest_getCurrentVersion ()
Definition at line 67 of file KTest.cpp.
References KTEST_VERSION.
Referenced by kTest_fromFile().
kTest_isKTestFile()
int kTest_isKTestFile (const char * path)
Definition at line 82 of file KTest.cpp.
References kTest_checkHeader().
kTest_numBytes()
unsigned kTest_numBytes (KTest * bo)
Definition at line 222 of file KTest.cpp.
References KTestObject::numBytes, KTest::numObjects, and KTest::objects.
Referenced by main().
kTest_toFile()
int kTest_toFile (KTest * bo, const char * path)
Definition at line 178 of file KTest.cpp.
References KTest::args, KTestObject::bytes, KTEST_MAGIC, KTEST_VERSION, KTestObject::name, KTest::numArgs, KTestObject::numBytes, KTest::numObjects, KTest::objects, KTest::symArgvLen, KTest::symArgvs, write_string(), and write_uint32().
Referenced by main(), and KleeHandler::processTestCase().