klee: klee::bits32 Namespace Reference
klee::bits32 Namespace Reference
Functions
unsigned maxValueOfNBits (unsigned N)
unsigned truncateToNBits (unsigned x, unsigned N)
unsigned withoutRightmostBit (unsigned x)
unsigned isolateRightmostBit (unsigned x)
unsigned isPowerOfTwo (unsigned x)
unsigned indexOfSingleBit (unsigned x)
unsigned indexOfRightmostBit (unsigned x)
Function Documentation
indexOfRightmostBit()
unsigned klee::bits32::indexOfRightmostBit (unsigned x) inline
Definition at line 62 of file Bits.h.
References indexOfSingleBit(), and isolateRightmostBit().
indexOfSingleBit()
unsigned klee::bits32::indexOfSingleBit (unsigned x) inline
Definition at line 49 of file Bits.h.
References withoutRightmostBit().
Referenced by indexOfRightmostBit(), and klee::bits64::indexOfSingleBit().
isolateRightmostBit()
unsigned klee::bits32::isolateRightmostBit (unsigned x) inline
Definition at line 38 of file Bits.h.
Referenced by indexOfRightmostBit().
isPowerOfTwo()
unsigned klee::bits32::isPowerOfTwo (unsigned x) inline
Definition at line 42 of file Bits.h.
Referenced by ValueRange::binaryXor().
maxValueOfNBits()
unsigned klee::bits32::maxValueOfNBits (unsigned N) inline
Definition at line 21 of file Bits.h.
Referenced by ValueRange::add(), ValueRange::extract(), ValueRange::isFullRange(), ValueRange::mul(), CexData::propogatePossibleValues(), ValueRange::sdiv(), ValueRange::srem(), ValueRange::sub(), ValueRange::udiv(), and ValueRange::urem().
truncateToNBits()
unsigned klee::bits32::truncateToNBits (unsigned x, unsigned N) inline
Definition at line 29 of file Bits.h.
withoutRightmostBit()
unsigned klee::bits32::withoutRightmostBit (unsigned x) inline
Definition at line 34 of file Bits.h.
Referenced by ValueRange::binaryXor(), and indexOfSingleBit().