klee: llvm Namespace Reference
llvm Namespace Reference
Classes
struct simplify_type< ::klee::ref< T > >
struct simplify_type< const ::klee::ref< T > >
Functions
void Optimize (Module *, llvm::ArrayRef< const char * > preservedFunctions)
static void AddStandardCompilePasses (legacy::PassManager &PM)
Function Documentation
AddStandardCompilePasses()
static void llvm::AddStandardCompilePasses (legacy::PassManager & PM) static
Definition at line 97 of file Optimize.cpp.
References addPass(), DisableInline(), and StripDebug().
Referenced by Optimize().
Optimize()
void llvm::Optimize (Module * M, llvm::ArrayRef< const char * > preservedFunctions)
Optimize - Perform link time optimizations. This will run the scalar optimizations, any loaded plugin-optimization modules, and then the inter-procedural optimizations if applicable.
Definition at line 161 of file Optimize.cpp.
References addPass(), AddStandardCompilePasses(), DisableInline(), DisableInternalize(), Strip(), StripDebug(), and VerifyEach().
Referenced by klee::KModule::optimiseAndPrepare().