klee: klee::time Namespace Reference
klee::time Namespace Reference
Classes
struct Point
struct Span
Functions
std::string getClockInfo ()
Returns information about clock.
Span getUserTime ()
Returns time spent by this process in user mode.
Point getWallTime ()
Returns point in time using a monotonic steady clock.
Point operator+ (const Point &, const Span &)
Point operator+ (const Span &, const Point &)
Point operator- (const Point &, const Span &)
Span operator- (const Point &, const Point &)
bool operator== (const Point &, const Point &)
bool operator!= (const Point &, const Point &)
bool operator< (const Point &, const Point &)
bool operator<= (const Point &, const Point &)
bool operator> (const Point &, const Point &)
bool operator>= (const Point &, const Point &)
Span operator+ (const Span &, const Span &)
Span operator- (const Span &, const Span &)
Span operator* (const Span &, double)
Span operator* (double, const Span &)
Span operator* (const Span &, unsigned)
Span operator* (unsigned, const Span &)
Span operator/ (const Span &, unsigned)
bool operator== (const Span &, const Span &)
bool operator<= (const Span &, const Span &)
bool operator>= (const Span &, const Span &)
bool operator< (const Span &, const Span &)
bool operator> (const Span &, const Span &)
std::ostream & operator<< (std::ostream &, Span)
Span -> "X.Ys".
llvm::raw_ostream & operator<< (llvm::raw_ostream &, Span)
Span hours (std::uint16_t)
time spans
Span minutes (std::uint16_t)
Span seconds (std::uint64_t)
Span milliseconds (std::uint64_t)
Span microseconds (std::uint64_t)
Span nanoseconds (std::uint64_t)
Function Documentation
getClockInfo()
std::string klee::time::getClockInfo ()
Returns information about clock.
Definition at line 179 of file Time.cpp.
Referenced by main().
getUserTime()
time::Span klee::time::getUserTime ()
Returns time spent by this process in user mode.
Definition at line 191 of file Time.cpp.
References klee::klee_warning(), microseconds(), seconds(), and usage().
Referenced by klee::StatsTracker::stepInstruction(), and klee::StatsTracker::writeStatsLine().
getWallTime()
time::Point klee::time::getWallTime ()
Returns point in time using a monotonic steady clock.
Definition at line 206 of file Time.cpp.
Referenced by klee::WallTimer::delta(), klee::StatsTracker::elapsed(), QueryLoggingSolver::finishQuery(), klee::TimerGroup::invoke(), main(), KleeHandler::processTestCase(), klee::TimerGroup::reset(), klee::Executor::run(), klee::BatchingSearcher::selectState(), klee::IterativeDeepeningTimeSearcher::selectState(), QueryLoggingSolver::startQuery(), klee::StatsTracker::stepInstruction(), and klee::IterativeDeepeningTimeSearcher::update().
hours()
time::Span klee::time::hours (std::uint16_t ticks)
time spans
Definition at line 137 of file Time.cpp.
References hours().
Referenced by hours(), and klee::time::Span::Span().
microseconds()
time::Span klee::time::microseconds (std::uint64_t ticks)
Definition at line 141 of file Time.cpp.
References microseconds().
Referenced by getUserTime(), microseconds(), operator*(), klee::time::Span::operator*=(), and klee::time::Span::Span().
milliseconds()
time::Span klee::time::milliseconds (std::uint64_t ticks)
Definition at line 140 of file Time.cpp.
References milliseconds().
Referenced by milliseconds(), and klee::time::Span::Span().
minutes()
time::Span klee::time::minutes (std::uint16_t ticks)
Definition at line 138 of file Time.cpp.
References minutes().
Referenced by minutes(), and klee::time::Span::Span().
nanoseconds()
time::Span klee::time::nanoseconds (std::uint64_t ticks)
Definition at line 142 of file Time.cpp.
References nanoseconds().
Referenced by nanoseconds(), and klee::time::Span::Span().
operator!=()
bool klee::time::operator!= (const Point & lhs, const Point & rhs)
Definition at line 47 of file Time.cpp.
References klee::time::Point::point.
operator*() [1/4]
time::Span klee::time::operator* (const Span & span, double factor)
Definition at line 117 of file Time.cpp.
References microseconds(), and klee::time::Span::toMicroseconds().
operator*() [2/4]
time::Span klee::time::operator* (const Span & span, unsigned factor)
Definition at line 123 of file Time.cpp.
References klee::time::Span::duration.
operator*() [3/4]
time::Span klee::time::operator* (double factor, const Span & span)
Definition at line 120 of file Time.cpp.
References microseconds(), and klee::time::Span::toMicroseconds().
operator*() [4/4]
time::Span klee::time::operator* (unsigned factor, const Span & span)
Definition at line 124 of file Time.cpp.
References klee::time::Span::duration.
operator+() [1/3]
time::Point klee::time::operator+ (const Point & point, const Span & span)
Definition at line 42 of file Time.cpp.
References klee::time::Span::duration, and klee::time::Point::point.
operator+() [2/3]
time::Point klee::time::operator+ (const Span & span, const Point & point)
Definition at line 43 of file Time.cpp.
References klee::time::Span::duration, and klee::time::Point::point.
operator+() [3/3]
time::Span klee::time::operator+ (const Span & lhs, const Span & rhs)
Definition at line 115 of file Time.cpp.
References klee::time::Span::duration.
operator-() [1/3]
time::Span klee::time::operator- (const Point & lhs, const Point & rhs)
Definition at line 45 of file Time.cpp.
References klee::time::Point::point.
operator-() [2/3]
time::Point klee::time::operator- (const Point & point, const Span & span)
Definition at line 44 of file Time.cpp.
References klee::time::Span::duration, and klee::time::Point::point.
operator-() [3/3]
time::Span klee::time::operator- (const Span & lhs, const Span & rhs)
Definition at line 116 of file Time.cpp.
References klee::time::Span::duration.
operator/()
time::Span klee::time::operator/ (const Span & span, unsigned divisor)
Definition at line 125 of file Time.cpp.
References klee::time::Span::duration.
operator<() [1/2]
bool klee::time::operator< (const Point & lhs, const Point & rhs)
Definition at line 48 of file Time.cpp.
References klee::time::Point::point.
operator<() [2/2]
bool klee::time::operator< (const Span & lhs, const Span & rhs)
Definition at line 129 of file Time.cpp.
References klee::time::Span::duration.
operator<<() [1/2]
llvm::raw_ostream & klee::time::operator<< (llvm::raw_ostream & stream, time::Span span)
Definition at line 133 of file Time.cpp.
References klee::time::Span::toSeconds().
operator<<() [2/2]
std::ostream & klee::time::operator<< (std::ostream & stream, time::Span span)
Span -> "X.Ys".
Definition at line 132 of file Time.cpp.
References klee::time::Span::toSeconds().
operator<=() [1/2]
bool klee::time::operator<= (const Point & lhs, const Point & rhs)
Definition at line 49 of file Time.cpp.
References klee::time::Point::point.
operator<=() [2/2]
bool klee::time::operator<= (const Span & lhs, const Span & rhs)
Definition at line 127 of file Time.cpp.
References klee::time::Span::duration.
operator==() [1/2]
bool klee::time::operator== (const Point & lhs, const Point & rhs)
Definition at line 46 of file Time.cpp.
References klee::time::Point::point.
operator==() [2/2]
bool klee::time::operator== (const Span & lhs, const Span & rhs)
Definition at line 126 of file Time.cpp.
References klee::time::Span::duration.
operator>() [1/2]
bool klee::time::operator> (const Point & lhs, const Point & rhs)
Definition at line 50 of file Time.cpp.
References klee::time::Point::point.
operator>() [2/2]
bool klee::time::operator> (const Span & lhs, const Span & rhs)
Definition at line 130 of file Time.cpp.
References klee::time::Span::duration.
operator>=() [1/2]
bool klee::time::operator>= (const Point & lhs, const Point & rhs)
Definition at line 51 of file Time.cpp.
References klee::time::Point::point.
operator>=() [2/2]
bool klee::time::operator>= (const Span & lhs, const Span & rhs)
Definition at line 128 of file Time.cpp.
References klee::time::Span::duration.
seconds()
time::Span klee::time::seconds (std::uint64_t ticks)
Definition at line 139 of file Time.cpp.
References seconds().
Referenced by getUserTime(), main(), klee::Executor::run(), seconds(), and klee::time::Span::Span().