klee: klee::bits64 Namespace Reference
klee::bits64 Namespace Reference
Functions
uint64_t maxValueOfNBits (unsigned N)
uint64_t truncateToNBits (uint64_t x, unsigned N)
uint64_t withoutRightmostBit (uint64_t x)
uint64_t isolateRightmostBit (uint64_t x)
uint64_t isPowerOfTwo (uint64_t x)
unsigned indexOfSingleBit (uint64_t x)
uint64_t indexOfRightmostBit (uint64_t x)
Function Documentation
indexOfRightmostBit()
uint64_t klee::bits64::indexOfRightmostBit (uint64_t x) inline
Definition at line 108 of file Bits.h.
References indexOfSingleBit(), and isolateRightmostBit().
Referenced by klee::ComputeMultConstants64().
indexOfSingleBit()
unsigned klee::bits64::indexOfSingleBit (uint64_t x) inline
Definition at line 98 of file Bits.h.
References klee::bits32::indexOfSingleBit().
Referenced by klee::ComputeMultConstants64(), and indexOfRightmostBit().
isolateRightmostBit()
uint64_t klee::bits64::isolateRightmostBit (uint64_t x) inline
Definition at line 87 of file Bits.h.
Referenced by klee::ComputeMultConstants64(), and indexOfRightmostBit().
isPowerOfTwo()
uint64_t klee::bits64::isPowerOfTwo (uint64_t x) inline
Definition at line 91 of file Bits.h.
Referenced by klee::Executor::getAllocationAlignment(), and klee::ObjectState::write().
maxValueOfNBits()
uint64_t klee::bits64::maxValueOfNBits (unsigned N) inline
Definition at line 70 of file Bits.h.
Referenced by klee::ExprRangeEvaluator< T >::evaluate(), and klee::Solver::getRange().
truncateToNBits()
uint64_t klee::bits64::truncateToNBits (uint64_t x, unsigned N) inline
Definition at line 78 of file Bits.h.
Referenced by klee::floats::add(), klee::ints::add(), klee::ints::ashr(), klee::ConstantExpr::create(), klee::floats::div(), klee::floats::ext(), klee::floats::mod(), klee::floats::mul(), klee::ints::mul(), klee::ints::sdiv(), klee::ints::sext(), klee::ints::shl(), klee::floats::SignedIntToFP(), klee::ints::srem(), klee::floats::sub(), klee::ints::sub(), klee::floats::toSignedInt(), klee::floats::toUnsignedInt(), klee::floats::trunc(), klee::ints::trunc(), klee::ints::udiv(), klee::floats::UnsignedIntToFP(), and klee::ints::urem().
withoutRightmostBit()
uint64_t klee::bits64::withoutRightmostBit (uint64_t x) inline
Definition at line 83 of file Bits.h.