klee: /Users/cristic/klee/lib/Module/Optimize.cpp File Reference
Optimize.cpp File Reference
#include "klee/Config/Version.h"
#include "klee/Support/OptionCategories.h"
#include "llvm/Analysis/GlobalsModRef.h"
#include "llvm/Analysis/Passes.h"
#include "llvm/Analysis/LoopPass.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Verifier.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/DynamicLibrary.h"
#include "llvm/Support/PluginLoader.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/IPO/FunctionAttrs.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Scalar/GVN.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/InstCombine/InstCombine.h"
Namespaces
namespace llvm
Functions
static cl::opt< bool > DisableInline ("disable-inlining", cl::desc("Do not run the inliner pass (default=false)"), cl::init(false), cl::cat(klee::ModuleCat))
static cl::opt< bool > DisableInternalize ("disable-internalize", cl::desc("Do not mark all symbols as internal (default=false)"), cl::init(false), cl::cat(klee::ModuleCat))
static cl::opt< bool > VerifyEach ("verify-each", cl::desc("Verify intermediate results of all optimization passes (default=false)"), cl::init(false), cl::cat(klee::ModuleCat))
static cl::alias ExportDynamic ("export-dynamic", cl::aliasopt(DisableInternalize), cl::desc("Alias for -disable-internalize"))
static cl::opt< bool > Strip ("strip-all", cl::desc("Strip all symbol information from executable"), cl::init(false), cl::cat(klee::ModuleCat))
static cl::alias A0 ("s", cl::desc("Alias for --strip-all"), cl::aliasopt(Strip))
static cl::opt< bool > StripDebug ("strip-debug", cl::desc("Strip debugger symbol info from executable"), cl::init(false), cl::cat(klee::ModuleCat))
static cl::alias A1 ("S", cl::desc("Alias for --strip-debug"), cl::aliasopt(StripDebug))
static void addPass (legacy::PassManager &PM, Pass *P)
static void llvm::AddStandardCompilePasses (legacy::PassManager &PM)
void llvm::Optimize (Module *, llvm::ArrayRef< const char * > preservedFunctions)
Function Documentation
A0()
static cl::alias A0 ("s" , cl::desc("Alias for --strip-all") , cl::aliasopt(Strip)) static
A1()
static cl::alias A1 ("S" , cl::desc("Alias for --strip-debug") , cl::aliasopt(StripDebug)) static
addPass()
static void addPass (legacy::PassManager & PM, Pass * P) inline static
Definition at line 85 of file Optimize.cpp.
References VerifyEach().
Referenced by llvm::AddStandardCompilePasses(), and llvm::Optimize().
DisableInline()
static cl::opt< bool > DisableInline ("disable-inlining" , cl::desc("Do not run the inliner pass (default=false)") , cl::init(false) , cl::cat(klee::ModuleCat)) static
Referenced by llvm::AddStandardCompilePasses(), and llvm::Optimize().
DisableInternalize()
static cl::opt< bool > DisableInternalize ("disable-internalize" , cl::desc("Do not mark all symbols as internal (default=false)") , cl::init(false) , cl::cat(klee::ModuleCat)) static
Referenced by llvm::Optimize().
ExportDynamic()
static cl::alias ExportDynamic ("export-dynamic" , cl::aliasopt(DisableInternalize) , cl::desc("Alias for -disable-internalize")) static
Strip()
static cl::opt< bool > Strip ("strip-all" , cl::desc("Strip all symbol information from executable") , cl::init(false) , cl::cat(klee::ModuleCat)) static
Referenced by llvm::Optimize().
StripDebug()
static cl::opt< bool > StripDebug ("strip-debug" , cl::desc("Strip debugger symbol info from executable") , cl::init(false) , cl::cat(klee::ModuleCat)) static
Referenced by llvm::AddStandardCompilePasses(), and llvm::Optimize().
VerifyEach()
static cl::opt< bool > VerifyEach ("verify-each" , cl::desc("Verify intermediate results of all optimization passes (default=false)") , cl::init(false) , cl::cat(klee::ModuleCat)) static
Referenced by addPass(), and llvm::Optimize().