klee: klee::time::Span Struct Reference
klee::time::Span Struct Reference
#include <Time.h>
Public Member Functions
Span ()=default
Span (const Duration &d)
Span (const std::string &s)
returns span from string in old (X.Y) and new (3h4min) format
Span & operator= (const Duration &)
Span & operator+= (const Span &)
Span & operator-= (const Span &)
Span & operator*= (unsigned)
Span & operator*= (double)
operator Duration () const
operator bool () const
operator timeval () const
std::uint64_t toMicroseconds () const
double toSeconds () const
std::tuple< std::uint32_t, std::uint8_t, std::uint8_t > toHMS () const
Public Attributes
Duration duration = Duration::zero()
Detailed Description
Definition at line 67 of file Time.h.
Constructor & Destructor Documentation
Span() [1/3]
klee::time::Span::Span () default
Span() [2/3]
klee::time::Span::Span (const Duration & d) inline explicit
Definition at line 72 of file Time.h.
Span() [3/3]
time::Span::Span (const std::string & s) explicit
returns span from string in old (X.Y) and new (3h4min) format
Definition at line 58 of file Time.cpp.
References klee::time::hours(), klee::klee_error(), klee::time::microseconds(), klee::time::milliseconds(), klee::time::minutes(), klee::time::nanoseconds(), and klee::time::seconds().
Member Function Documentation
operator bool()
time::Span::operator bool () const explicit
Definition at line 148 of file Time.cpp.
operator Duration()
klee::time::Span::operator Duration () const explicit
operator timeval()
time::Span::operator timeval () const explicit
Definition at line 150 of file Time.cpp.
operator*=() [1/2]
time::Span & time::Span::operator*= (double factor)
Definition at line 110 of file Time.cpp.
References klee::time::microseconds().
operator*=() [2/2]
time::Span & time::Span::operator*= (unsigned factor)
Definition at line 109 of file Time.cpp.
operator+=()
time::Span & time::Span::operator+= (const Span & other)
Definition at line 107 of file Time.cpp.
References duration.
operator-=()
time::Span & time::Span::operator-= (const Span & other)
Definition at line 108 of file Time.cpp.
References duration.
operator=()
time::Span & time::Span::operator= (const Duration &)
Definition at line 106 of file Time.cpp.
toHMS()
std::tuple< std::uint32_t, std::uint8_t, std::uint8_t > time::Span::toHMS () const
Definition at line 167 of file Time.cpp.
Referenced by main().
toMicroseconds()
std::uint64_t time::Span::toMicroseconds () const
Definition at line 159 of file Time.cpp.
Referenced by klee::time::operator*(), and klee::TimerStatIncrementer::~TimerStatIncrementer().
toSeconds()
double time::Span::toSeconds () const
Definition at line 163 of file Time.cpp.
Referenced by klee::WeightedRandomSearcher::getWeight(), klee::time::operator<<(), klee::BatchingSearcher::selectState(), and klee::IterativeDeepeningTimeSearcher::update().
Member Data Documentation
duration
Duration klee::time::Span::duration = Duration::zero()
Definition at line 68 of file Time.h.
Referenced by klee::time::operator*(), klee::time::operator+(), klee::time::Point::operator+=(), operator+=(), klee::time::operator-(), klee::time::Point::operator-=(), operator-=(), klee::time::operator/(), klee::time::operator<(), klee::time::operator<=(), klee::time::operator==(), klee::time::operator>(), and klee::time::operator>=().
The documentation for this struct was generated from the following files:
/Users/cristic/klee/include/klee/System/Time.h
/Users/cristic/klee/lib/Support/Time.cpp