klee: klee::SymbolicObjectFinder Class Reference
klee::SymbolicObjectFinder Class Reference
Public Member Functions
SymbolicObjectFinder (std::vector< const Array * > &_objects)
Public Member Functions inherited from klee::ExprVisitor
ref< Expr > visit (const ref< Expr > &e)
Public Attributes
std::set< const Array * > results
std::vector< const Array * > & objects
Protected Member Functions
Action visitRead (const ReadExpr &re)
Protected Member Functions inherited from klee::ExprVisitor
ExprVisitor (bool _recursive=false)
virtual ~ExprVisitor ()
virtual Action visitExpr (const Expr &)
virtual Action visitExprPost (const Expr &)
virtual Action visitNotOptimized (const NotOptimizedExpr &)
virtual Action visitRead (const ReadExpr &)
virtual Action visitSelect (const SelectExpr &)
virtual Action visitConcat (const ConcatExpr &)
virtual Action visitExtract (const ExtractExpr &)
virtual Action visitZExt (const ZExtExpr &)
virtual Action visitSExt (const SExtExpr &)
virtual Action visitAdd (const AddExpr &)
virtual Action visitSub (const SubExpr &)
virtual Action visitMul (const MulExpr &)
virtual Action visitUDiv (const UDivExpr &)
virtual Action visitSDiv (const SDivExpr &)
virtual Action visitURem (const URemExpr &)
virtual Action visitSRem (const SRemExpr &)
virtual Action visitNot (const NotExpr &)
virtual Action visitAnd (const AndExpr &)
virtual Action visitOr (const OrExpr &)
virtual Action visitXor (const XorExpr &)
virtual Action visitShl (const ShlExpr &)
virtual Action visitLShr (const LShrExpr &)
virtual Action visitAShr (const AShrExpr &)
virtual Action visitEq (const EqExpr &)
virtual Action visitNe (const NeExpr &)
virtual Action visitUlt (const UltExpr &)
virtual Action visitUle (const UleExpr &)
virtual Action visitUgt (const UgtExpr &)
virtual Action visitUge (const UgeExpr &)
virtual Action visitSlt (const SltExpr &)
virtual Action visitSle (const SleExpr &)
virtual Action visitSgt (const SgtExpr &)
virtual Action visitSge (const SgeExpr &)
Detailed Description
Definition at line 80 of file ExprUtil.cpp.
Constructor & Destructor Documentation
SymbolicObjectFinder()
klee::SymbolicObjectFinder::SymbolicObjectFinder (std::vector< const Array * > & _objects) inline
Definition at line 102 of file ExprUtil.cpp.
Member Function Documentation
visitRead()
Action klee::SymbolicObjectFinder::visitRead (const ReadExpr & re) inline protected virtual
Reimplemented from klee::ExprVisitor.
Definition at line 82 of file ExprUtil.cpp.
References klee::ExprVisitor::Action::doChildren(), klee::UpdateList::head, klee::Array::isSymbolicArray(), objects, results, klee::UpdateList::root, klee::ReadExpr::updates, and klee::ExprVisitor::visit().
Member Data Documentation
objects
std::vector<const Array*>& klee::SymbolicObjectFinder::objects
Definition at line 100 of file ExprUtil.cpp.
Referenced by visitRead().
results
std::set<const Array*> klee::SymbolicObjectFinder::results
Definition at line 99 of file ExprUtil.cpp.
Referenced by visitRead().
The documentation for this class was generated from the following file:
/Users/cristic/klee/lib/Expr/ExprUtil.cpp