klee: klee::TimerStatIncrementer Class Reference
klee::TimerStatIncrementer Class Reference
#include <TimerStatIncrementer.h>
Public Member Functions
TimerStatIncrementer (Statistic &statistic)
~TimerStatIncrementer ()
time::Span delta () const
Private Attributes
const WallTimer timer
Statistic & statistic
Detailed Description
A TimerStatIncrementer adds its lifetime to a specified Statistic.
Definition at line 21 of file TimerStatIncrementer.h.
Constructor & Destructor Documentation
TimerStatIncrementer()
klee::TimerStatIncrementer::TimerStatIncrementer (Statistic & statistic) inline explicit
Definition at line 27 of file TimerStatIncrementer.h.
~TimerStatIncrementer()
klee::TimerStatIncrementer::~TimerStatIncrementer () inline
Definition at line 28 of file TimerStatIncrementer.h.
References klee::WallTimer::delta(), statistic, timer, and klee::time::Span::toMicroseconds().
Member Function Documentation
delta()
time::Span klee::TimerStatIncrementer::delta () const inline
Definition at line 33 of file TimerStatIncrementer.h.
References klee::WallTimer::delta(), and timer.
Referenced by klee::TimingSolver::evaluate(), klee::TimingSolver::getInitialValues(), klee::TimingSolver::getRange(), klee::TimingSolver::getValue(), klee::TimingSolver::mustBeTrue(), and klee::AddressSpace::resolve().
Member Data Documentation
statistic
Statistic& klee::TimerStatIncrementer::statistic private
Definition at line 24 of file TimerStatIncrementer.h.
Referenced by ~TimerStatIncrementer().
timer
const WallTimer klee::TimerStatIncrementer::timer private
Definition at line 23 of file TimerStatIncrementer.h.
Referenced by delta(), and ~TimerStatIncrementer().
The documentation for this class was generated from the following file:
/Users/cristic/klee/include/klee/Statistics/TimerStatIncrementer.h