klee: klee::StatisticRecord Class Reference
klee::StatisticRecord Class Reference
#include <Statistics.h>
Public Member Functions
StatisticRecord ()
StatisticRecord (const StatisticRecord &s)
~StatisticRecord ()
void zero ()
uint64_t getValue (const Statistic &s) const
void incrementValue (const Statistic &s, uint64_t addend) const
StatisticRecord & operator= (const StatisticRecord &s)
StatisticRecord & operator+= (const StatisticRecord &sr)
Private Attributes
uint64_t * data
Friends
class StatisticManager
Detailed Description
Definition at line 21 of file Statistics.h.
Constructor & Destructor Documentation
StatisticRecord() [1/2]
klee::StatisticRecord::StatisticRecord () inline
Definition at line 99 of file Statistics.h.
References zero().
StatisticRecord() [2/2]
klee::StatisticRecord::StatisticRecord (const StatisticRecord & s) inline
Definition at line 104 of file Statistics.h.
References data, klee::StatisticManager::getNumStatistics(), and klee::theStatisticManager.
~StatisticRecord()
klee::StatisticRecord::~StatisticRecord () inline
Definition at line 30 of file Statistics.h.
References data.
Member Function Documentation
getValue()
uint64_t klee::StatisticRecord::getValue (const Statistic & s) const inline
Definition at line 120 of file Statistics.h.
References data, and klee::Statistic::id.
Referenced by klee::Executor::dumpStates(), klee::WeightedRandomSearcher::getWeight(), klee::Executor::maxStaticPctChecks(), and klee::StatsTracker::writeIStats().
incrementValue()
void klee::StatisticRecord::incrementValue (const Statistic & s, uint64_t addend) const inline
Definition at line 116 of file Statistics.h.
References data, and klee::Statistic::id.
operator+=()
StatisticRecord & klee::StatisticRecord::operator+= (const StatisticRecord & sr) inline
Definition at line 125 of file Statistics.h.
References data, klee::StatisticManager::getNumStatistics(), and klee::theStatisticManager.
operator=()
StatisticRecord & klee::StatisticRecord::operator= (const StatisticRecord & s) inline
Definition at line 110 of file Statistics.h.
References data, klee::StatisticManager::getNumStatistics(), and klee::theStatisticManager.
zero()
void klee::StatisticRecord::zero () inline
Definition at line 95 of file Statistics.h.
References data, klee::StatisticManager::getNumStatistics(), and klee::theStatisticManager.
Referenced by StatisticRecord().
Friends And Related Function Documentation
StatisticManager
friend class StatisticManager friend
Definition at line 22 of file Statistics.h.
Member Data Documentation
data
uint64_t* klee::StatisticRecord::data private
Definition at line 25 of file Statistics.h.
Referenced by getValue(), klee::StatisticManager::incrementStatistic(), incrementValue(), operator+=(), operator=(), StatisticRecord(), zero(), and ~StatisticRecord().
The documentation for this class was generated from the following file:
/Users/cristic/klee/include/klee/Statistics/Statistics.h