klee: klee::ArrayExprHelper Class Reference
klee::ArrayExprHelper Class Reference
#include <ArrayExprVisitor.h>
Static Public Member Functions
static ReadExpr * hasOrderedReads (const ConcatExpr &ce)
Static Private Member Functions
static bool isReadExprAtOffset (ref< Expr > e, const ReadExpr *base, ref< Expr > offset)
Detailed Description
Definition at line 24 of file ArrayExprVisitor.h.
Member Function Documentation
hasOrderedReads()
ReadExpr * ArrayExprHelper::hasOrderedReads (const ConcatExpr & ce) static
Definition at line 27 of file ArrayExprVisitor.cpp.
References klee::ConstantExpr::alloc(), klee::Expr::Concat, klee::ConstantExpr::create(), klee::ref< T >::get(), klee::ConcatExpr::getKid(), klee::Expr::getKid(), klee::Expr::getKind(), klee::ReadExpr::getWidth(), klee::Expr::getWidth(), klee::ReadExpr::index, klee::Expr::Int8, and isReadExprAtOffset().
Referenced by klee::ConstantArrayExprVisitor::visitConcat(), and klee::ArrayReadExprVisitor::visitConcat().
isReadExprAtOffset()
bool ArrayExprHelper::isReadExprAtOffset (ref< Expr > e, const ReadExpr * base, ref< Expr > offset) static private
Definition at line 19 of file ArrayExprVisitor.cpp.
References klee::ref< T >::get(), klee::ReadExpr::getWidth(), klee::ReadExpr::index, and klee::Expr::Int8.
Referenced by hasOrderedReads().
The documentation for this class was generated from the following files:
/Users/cristic/klee/include/klee/Expr/ArrayExprVisitor.h
/Users/cristic/klee/lib/Expr/ArrayExprVisitor.cpp