klee: klee::ConstantArrayFinder Class Reference
klee::ConstantArrayFinder Class Reference
#include <ExprUtil.h>
Public Attributes
std::set< const Array * > results
Protected Member Functions
ExprVisitor::Action visitRead (const ReadExpr &re)
Protected Member Functions inherited from klee::ExprVisitor
ExprVisitor (bool _recursive=false)
virtual ~ExprVisitor ()
virtual Action visitExpr (const Expr &)
virtual Action visitExprPost (const Expr &)
virtual Action visitNotOptimized (const NotOptimizedExpr &)
virtual Action visitRead (const ReadExpr &)
virtual Action visitSelect (const SelectExpr &)
virtual Action visitConcat (const ConcatExpr &)
virtual Action visitExtract (const ExtractExpr &)
virtual Action visitZExt (const ZExtExpr &)
virtual Action visitSExt (const SExtExpr &)
virtual Action visitAdd (const AddExpr &)
virtual Action visitSub (const SubExpr &)
virtual Action visitMul (const MulExpr &)
virtual Action visitUDiv (const UDivExpr &)
virtual Action visitSDiv (const SDivExpr &)
virtual Action visitURem (const URemExpr &)
virtual Action visitSRem (const SRemExpr &)
virtual Action visitNot (const NotExpr &)
virtual Action visitAnd (const AndExpr &)
virtual Action visitOr (const OrExpr &)
virtual Action visitXor (const XorExpr &)
virtual Action visitShl (const ShlExpr &)
virtual Action visitLShr (const LShrExpr &)
virtual Action visitAShr (const AShrExpr &)
virtual Action visitEq (const EqExpr &)
virtual Action visitNe (const NeExpr &)
virtual Action visitUlt (const UltExpr &)
virtual Action visitUle (const UleExpr &)
virtual Action visitUgt (const UgtExpr &)
virtual Action visitUge (const UgeExpr &)
virtual Action visitSlt (const SltExpr &)
virtual Action visitSle (const SleExpr &)
virtual Action visitSgt (const SgtExpr &)
virtual Action visitSge (const SgeExpr &)
Additional Inherited Members
Public Member Functions inherited from klee::ExprVisitor
ref< Expr > visit (const ref< Expr > &e)
Detailed Description
Definition at line 43 of file ExprUtil.h.
Member Function Documentation
visitRead()
ExprVisitor::Action klee::ConstantArrayFinder::visitRead (const ReadExpr & re) protected virtual
Reimplemented from klee::ExprVisitor.
Definition at line 106 of file ExprUtil.cpp.
References klee::ExprVisitor::Action::doChildren(), klee::UpdateList::head, klee::Array::isConstantArray(), results, klee::UpdateList::root, klee::ReadExpr::updates, and klee::ExprVisitor::visit().
Member Data Documentation
results
std::set<const Array *> klee::ConstantArrayFinder::results
Definition at line 48 of file ExprUtil.h.
Referenced by visitRead().
The documentation for this class was generated from the following files:
/Users/cristic/klee/include/klee/Expr/ExprUtil.h
/Users/cristic/klee/lib/Expr/ExprUtil.cpp