klee: klee::ExprVisitor::Action Class Reference
klee::ExprVisitor::Action Class Reference
#include <ExprVisitor.h>
Public Types
enum Kind { SkipChildren , DoChildren , ChangeTo }
Static Public Member Functions
static Action changeTo (const ref< Expr > &expr)
static Action doChildren ()
static Action skipChildren ()
Public Attributes
Kind kind
ref< Expr > argument
Private Member Functions
Action (Kind _kind)
Action (Kind _kind, const ref< Expr > &_argument)
Friends
class ExprVisitor
Detailed Description
Definition at line 19 of file ExprVisitor.h.
Member Enumeration Documentation
Kind
enum klee::ExprVisitor::Action::Kind
Enumerator
SkipChildren
DoChildren
ChangeTo
Definition at line 21 of file ExprVisitor.h.
Constructor & Destructor Documentation
Action() [1/2]
klee::ExprVisitor::Action::Action (Kind _kind) inline private
Definition at line 25 of file ExprVisitor.h.
Referenced by changeTo(), doChildren(), and skipChildren().
Action() [2/2]
klee::ExprVisitor::Action::Action (Kind _kind, const ref< Expr > & _argument) inline private
Definition at line 27 of file ExprVisitor.h.
Member Function Documentation
changeTo()
static Action klee::ExprVisitor::Action::changeTo (const ref< Expr > & expr) inline static
Definition at line 36 of file ExprVisitor.h.
References Action(), and ChangeTo.
Referenced by klee::ExprEvaluator::evalRead(), klee::ExprEvaluator::protectedDivOperation(), klee::ArrayValueOptReplaceVisitor::visitConcat(), klee::ExprEvaluator::visitExpr(), ExprReplaceVisitor::visitExpr(), klee::ExprEvaluator::visitExprPost(), ExprReplaceVisitor::visitExprPost(), ExprReplaceVisitor2::visitExprPost(), and klee::ArrayValueOptReplaceVisitor::visitRead().
doChildren()
static Action klee::ExprVisitor::Action::doChildren () inline static
Definition at line 39 of file ExprVisitor.h.
References Action(), and DoChildren.
Referenced by klee::ArrayReadExprVisitor::inspectRead(), klee::ExprVisitor::visitAdd(), klee::ExprVisitor::visitAnd(), klee::ExprVisitor::visitAShr(), klee::ExprVisitor::visitConcat(), klee::ConstantArrayExprVisitor::visitConcat(), klee::IndexTransformationExprVisitor::visitConcat(), klee::ArrayReadExprVisitor::visitConcat(), klee::ArrayValueOptReplaceVisitor::visitConcat(), klee::ExprVisitor::visitEq(), klee::ExprVisitor::visitExpr(), klee::ExprEvaluator::visitExpr(), ExprReplaceVisitor::visitExpr(), ExprReplaceVisitor::visitExprPost(), ExprReplaceVisitor2::visitExprPost(), klee::ExprVisitor::visitExtract(), klee::ExprVisitor::visitLShr(), klee::ExprVisitor::visitMul(), klee::IndexTransformationExprVisitor::visitMul(), klee::ExprVisitor::visitNe(), klee::ExprVisitor::visitNot(), klee::ExprVisitor::visitNotOptimized(), klee::ExprVisitor::visitOr(), klee::ExprVisitor::visitRead(), klee::ConstantArrayExprVisitor::visitRead(), klee::IndexCompatibilityExprVisitor::visitRead(), klee::ExprEvaluator::visitRead(), klee::ConstantArrayFinder::visitRead(), klee::SymbolicObjectFinder::visitRead(), klee::ArrayValueOptReplaceVisitor::visitRead(), klee::ExprVisitor::visitSDiv(), klee::ExprVisitor::visitSelect(), klee::ExprVisitor::visitSExt(), klee::ExprVisitor::visitSge(), klee::ExprVisitor::visitSgt(), klee::ExprVisitor::visitShl(), klee::ExprVisitor::visitSle(), klee::ExprVisitor::visitSlt(), klee::ExprVisitor::visitSRem(), klee::ExprVisitor::visitSub(), klee::ExprVisitor::visitUDiv(), klee::ExprVisitor::visitUge(), klee::ExprVisitor::visitUgt(), klee::ExprVisitor::visitUle(), klee::ExprVisitor::visitUlt(), klee::ExprVisitor::visitURem(), klee::ExprVisitor::visitXor(), and klee::ExprVisitor::visitZExt().
skipChildren()
static Action klee::ExprVisitor::Action::skipChildren () inline static
Definition at line 40 of file ExprVisitor.h.
References Action(), and SkipChildren.
Referenced by klee::ArrayReadExprVisitor::inspectRead(), klee::ExprEvaluator::protectedDivOperation(), klee::ConstantArrayExprVisitor::visitConcat(), klee::ExprVisitor::visitExprPost(), klee::ExprEvaluator::visitExprPost(), klee::IndexCompatibilityExprVisitor::visitOr(), klee::ConstantArrayExprVisitor::visitRead(), klee::IndexCompatibilityExprVisitor::visitRead(), klee::IndexCompatibilityExprVisitor::visitSRem(), and klee::IndexCompatibilityExprVisitor::visitURem().
Friends And Related Function Documentation
ExprVisitor
friend class ExprVisitor friend
Definition at line 30 of file ExprVisitor.h.
Member Data Documentation
argument
ref<Expr> klee::ExprVisitor::Action::argument
Definition at line 34 of file ExprVisitor.h.
Referenced by klee::ExprVisitor::visitActual().
kind
Kind klee::ExprVisitor::Action::kind
Definition at line 33 of file ExprVisitor.h.
Referenced by klee::ExprVisitor::visitActual().
The documentation for this class was generated from the following file:
/Users/cristic/klee/include/klee/Expr/ExprVisitor.h