klee: klee::ImmutableSet< T, CMP > Class Template Reference
klee::ImmutableSet< T, CMP > Class Template Reference
#include <ImmutableSet.h>
Public Types
typedef T key_type
typedef T value_type
typedef ImmutableTree< T, T, _Identity< T >, CMP > Tree
typedef Tree::iterator iterator
Public Member Functions
ImmutableSet ()
ImmutableSet (const ImmutableSet &b)
~ImmutableSet ()
ImmutableSet & operator= (const ImmutableSet &b)
bool empty () const
size_t count (const key_type &key) const
const value_type * lookup (const key_type &key) const
const value_type & min () const
const value_type & max () const
size_t size ()
ImmutableSet insert (const value_type &value) const
ImmutableSet replace (const value_type &value) const
ImmutableSet remove (const key_type &key) const
ImmutableSet popMin (const value_type &valueOut) const
ImmutableSet popMax (const value_type &valueOut) const
iterator begin () const
iterator end () const
iterator find (const key_type &key) const
iterator lower_bound (const key_type &key) const
iterator upper_bound (const key_type &key) const
Static Public Member Functions
static size_t getAllocated ()
Private Member Functions
ImmutableSet (const Tree &b)
Private Attributes
Tree elts
Detailed Description
template<class T, class CMP = std::less<T>>
class klee::ImmutableSet< T, CMP >
Definition at line 25 of file ImmutableSet.h.
Member Typedef Documentation
iterator
template<class T , class CMP = std::less<T>> typedef Tree::iterator klee::ImmutableSet< T, CMP >::iterator
Definition at line 31 of file ImmutableSet.h.
key_type
template<class T , class CMP = std::less<T>> typedef T klee::ImmutableSet< T, CMP >::key_type
Definition at line 27 of file ImmutableSet.h.
Tree
template<class T , class CMP = std::less<T>> typedef ImmutableTree<T, T, _Identity<T>, CMP> klee::ImmutableSet< T, CMP >::Tree
Definition at line 30 of file ImmutableSet.h.
value_type
template<class T , class CMP = std::less<T>> typedef T klee::ImmutableSet< T, CMP >::value_type
Definition at line 28 of file ImmutableSet.h.
Constructor & Destructor Documentation
ImmutableSet() [1/3]
template<class T , class CMP = std::less<T>> klee::ImmutableSet< T, CMP >::ImmutableSet (const Tree & b) inline private
Definition at line 36 of file ImmutableSet.h.
ImmutableSet() [2/3]
template<class T , class CMP = std::less<T>> klee::ImmutableSet< T, CMP >::ImmutableSet () inline
Definition at line 39 of file ImmutableSet.h.
ImmutableSet() [3/3]
template<class T , class CMP = std::less<T>> klee::ImmutableSet< T, CMP >::ImmutableSet (const ImmutableSet< T, CMP > & b) inline
Definition at line 40 of file ImmutableSet.h.
~ImmutableSet()
template<class T , class CMP = std::less<T>> klee::ImmutableSet< T, CMP >::~ImmutableSet () inline
Definition at line 41 of file ImmutableSet.h.
Member Function Documentation
begin()
template<class T , class CMP = std::less<T>> iterator klee::ImmutableSet< T, CMP >::begin () const inline
Definition at line 80 of file ImmutableSet.h.
References klee::ImmutableTree< K, V, KOV, CMP >::begin(), and klee::ImmutableSet< T, CMP >::elts.
count()
template<class T , class CMP = std::less<T>> size_t klee::ImmutableSet< T, CMP >::count (const key_type & key) const inline
Definition at line 48 of file ImmutableSet.h.
References klee::ImmutableTree< K, V, KOV, CMP >::count(), and klee::ImmutableSet< T, CMP >::elts.
empty()
template<class T , class CMP = std::less<T>> bool klee::ImmutableSet< T, CMP >::empty () const inline
Definition at line 45 of file ImmutableSet.h.
References klee::ImmutableSet< T, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::empty().
end()
template<class T , class CMP = std::less<T>> iterator klee::ImmutableSet< T, CMP >::end () const inline
Definition at line 83 of file ImmutableSet.h.
References klee::ImmutableSet< T, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::end().
find()
template<class T , class CMP = std::less<T>> iterator klee::ImmutableSet< T, CMP >::find (const key_type & key) const inline
Definition at line 86 of file ImmutableSet.h.
References klee::ImmutableSet< T, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::find().
getAllocated()
template<class T , class CMP = std::less<T>> static size_t klee::ImmutableSet< T, CMP >::getAllocated () inline static
Definition at line 96 of file ImmutableSet.h.
References klee::ImmutableTree< K, V, KOV, CMP >::allocated.
insert()
template<class T , class CMP = std::less<T>> ImmutableSet klee::ImmutableSet< T, CMP >::insert (const value_type & value) const inline
Definition at line 64 of file ImmutableSet.h.
References klee::ImmutableSet< T, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::insert().
lookup()
template<class T , class CMP = std::less<T>> const value_type * klee::ImmutableSet< T, CMP >::lookup (const key_type & key) const inline
Definition at line 51 of file ImmutableSet.h.
References klee::ImmutableSet< T, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::lookup().
lower_bound()
template<class T , class CMP = std::less<T>> iterator klee::ImmutableSet< T, CMP >::lower_bound (const key_type & key) const inline
Definition at line 89 of file ImmutableSet.h.
References klee::ImmutableSet< T, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::lower_bound().
max()
template<class T , class CMP = std::less<T>> const value_type & klee::ImmutableSet< T, CMP >::max () const inline
Definition at line 57 of file ImmutableSet.h.
References klee::ImmutableSet< T, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::max().
min()
template<class T , class CMP = std::less<T>> const value_type & klee::ImmutableSet< T, CMP >::min () const inline
Definition at line 54 of file ImmutableSet.h.
References klee::ImmutableSet< T, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::min().
operator=()
template<class T , class CMP = std::less<T>> ImmutableSet & klee::ImmutableSet< T, CMP >::operator= (const ImmutableSet< T, CMP > & b) inline
Definition at line 43 of file ImmutableSet.h.
References klee::ImmutableSet< T, CMP >::elts.
popMax()
template<class T , class CMP = std::less<T>> ImmutableSet klee::ImmutableSet< T, CMP >::popMax (const value_type & valueOut) const inline
Definition at line 76 of file ImmutableSet.h.
References klee::ImmutableSet< T, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::popMax().
popMin()
template<class T , class CMP = std::less<T>> ImmutableSet klee::ImmutableSet< T, CMP >::popMin (const value_type & valueOut) const inline
Definition at line 73 of file ImmutableSet.h.
References klee::ImmutableSet< T, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::popMin().
remove()
template<class T , class CMP = std::less<T>> ImmutableSet klee::ImmutableSet< T, CMP >::remove (const key_type & key) const inline
Definition at line 70 of file ImmutableSet.h.
References klee::ImmutableSet< T, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::remove().
replace()
template<class T , class CMP = std::less<T>> ImmutableSet klee::ImmutableSet< T, CMP >::replace (const value_type & value) const inline
Definition at line 67 of file ImmutableSet.h.
References klee::ImmutableSet< T, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::replace().
size()
template<class T , class CMP = std::less<T>> size_t klee::ImmutableSet< T, CMP >::size () inline
Definition at line 60 of file ImmutableSet.h.
References klee::ImmutableSet< T, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::size().
upper_bound()
template<class T , class CMP = std::less<T>> iterator klee::ImmutableSet< T, CMP >::upper_bound (const key_type & key) const inline
Definition at line 92 of file ImmutableSet.h.
References klee::ImmutableSet< T, CMP >::elts, and klee::ImmutableTree< K, V, KOV, CMP >::upper_bound().
Member Data Documentation
elts
template<class T , class CMP = std::less<T>> Tree klee::ImmutableSet< T, CMP >::elts private
Definition at line 34 of file ImmutableSet.h.
Referenced by klee::ImmutableSet< T, CMP >::begin(), klee::ImmutableSet< T, CMP >::count(), klee::ImmutableSet< T, CMP >::empty(), klee::ImmutableSet< T, CMP >::end(), klee::ImmutableSet< T, CMP >::find(), klee::ImmutableSet< T, CMP >::insert(), klee::ImmutableSet< T, CMP >::lookup(), klee::ImmutableSet< T, CMP >::lower_bound(), klee::ImmutableSet< T, CMP >::max(), klee::ImmutableSet< T, CMP >::min(), klee::ImmutableSet< T, CMP >::operator=(), klee::ImmutableSet< T, CMP >::popMax(), klee::ImmutableSet< T, CMP >::popMin(), klee::ImmutableSet< T, CMP >::remove(), klee::ImmutableSet< T, CMP >::replace(), klee::ImmutableSet< T, CMP >::size(), and klee::ImmutableSet< T, CMP >::upper_bound().
The documentation for this class was generated from the following file:
/Users/cristic/klee/include/klee/ADT/ImmutableSet.h