klee: klee::Timer Class Reference
klee::Timer Class Reference
#include <Timer.h>
Public Member Functions
Timer (const time::Span &interval, std::function< void()> &&callback)
time::Span getInterval () const
Return specified interval between invocations.
void invoke (const time::Point &currentTime)
Execute callback if invocation time exceeded.
void reset (const time::Point &currentTime)
Set new invocation time to currentTime + interval.
Private Attributes
time::Span interval
Approximate interval between callback invocations.
time::Point nextInvocationTime
Wall time for next invocation.
std::function< void()> run
The event callback.
Detailed Description
A Timer repeatedly executes a callback after a specified interval. An object of this class is passive and only keeps track of the next invocation time. Passive means, that it has to be invoked by an external caller with the current time. Only when the time span between the current time and the last invocation exceeds the specified interval, the callback will be executed. Multiple timers are typically managed by a TimerGroup.
Definition at line 43 of file Timer.h.
Constructor & Destructor Documentation
Timer()
Timer::Timer (const time::Span & interval, std::function< void()> && callback)
Parameters
interval The time span between callback invocations.
callback The event callback.
Definition at line 29 of file Timer.cpp.
Member Function Documentation
getInterval()
time::Span Timer::getInterval () const
Return specified interval between invocations.
Definition at line 32 of file Timer.cpp.
References interval.
Referenced by klee::TimerGroup::add().
invoke()
void Timer::invoke (const time::Point & currentTime)
Execute callback if invocation time exceeded.
Definition at line 36 of file Timer.cpp.
References interval, nextInvocationTime, and run.
Referenced by klee::TimerGroup::invoke().
reset()
void Timer::reset (const time::Point & currentTime)
Set new invocation time to currentTime + interval.
Definition at line 43 of file Timer.cpp.
References interval, and nextInvocationTime.
Referenced by klee::TimerGroup::reset().
Member Data Documentation
interval
time::Span klee::Timer::interval private
Approximate interval between callback invocations.
Definition at line 45 of file Timer.h.
Referenced by getInterval(), invoke(), and reset().
nextInvocationTime
time::Point klee::Timer::nextInvocationTime private
Wall time for next invocation.
Definition at line 47 of file Timer.h.
Referenced by invoke(), and reset().
run
std::function<void()> klee::Timer::run private
The event callback.
Definition at line 49 of file Timer.h.
Referenced by invoke().
The documentation for this class was generated from the following files:
/Users/cristic/klee/include/klee/Support/Timer.h
/Users/cristic/klee/lib/Support/Timer.cpp