klee: klee::RNG Class Reference
klee::RNG Class Reference
#include <RNG.h>
Public Member Functions
RNG ()
RNG (unsigned int seed)
void seed (unsigned int seed)
unsigned int getInt32 ()
int getInt31 ()
double getDoubleLR ()
float getFloatLR ()
double getDoubleL ()
float getFloatL ()
double getDouble ()
float getFloat ()
bool getBool ()
Private Attributes
unsigned int mt [N]
int mti
Static Private Attributes
static const int N = 624
static const int M = 397
static const unsigned int MATRIX_A = 0x9908b0dfUL
static const unsigned int UPPER_MASK = 0x80000000UL
static const unsigned int LOWER_MASK = 0x7fffffffUL
Detailed Description
Definition at line 14 of file RNG.h.
Constructor & Destructor Documentation
RNG() [1/2]
RNG::RNG ()
Definition at line 58 of file RNG.cpp.
References seed().
RNG() [2/2]
RNG::RNG (unsigned int seed) explicit
Definition at line 63 of file RNG.cpp.
References seed().
Member Function Documentation
getBool()
bool RNG::getBool ()
Definition at line 151 of file RNG.cpp.
References getInt32().
Referenced by klee::Executor::fork().
getDouble()
double RNG::getDouble ()
Definition at line 133 of file RNG.cpp.
References getInt32().
getDoubleL()
double RNG::getDoubleL ()
Definition at line 127 of file RNG.cpp.
References getInt32().
Referenced by klee::WeightedRandomSearcher::selectState().
getDoubleLR()
double RNG::getDoubleLR ()
Definition at line 121 of file RNG.cpp.
References getInt32().
getFloat()
float RNG::getFloat ()
Definition at line 146 of file RNG.cpp.
References getInt32().
getFloatL()
float RNG::getFloatL ()
Definition at line 142 of file RNG.cpp.
References getInt32().
getFloatLR()
float RNG::getFloatLR ()
Definition at line 138 of file RNG.cpp.
References getInt32().
getInt31()
int RNG::getInt31 ()
Definition at line 116 of file RNG.cpp.
References getInt32().
getInt32()
unsigned int RNG::getInt32 ()
Definition at line 82 of file RNG.cpp.
References LOWER_MASK, M, MATRIX_A, mt, mti, N, and UPPER_MASK.
Referenced by klee::Executor::branch(), klee::Executor::checkMemoryUsage(), getBool(), getDouble(), getDoubleL(), getDoubleLR(), getFloat(), getFloatL(), getFloatLR(), getInt31(), klee::RandomSearcher::selectState(), and klee::RandomPathSearcher::selectState().
seed()
void RNG::seed (unsigned int seed)
Definition at line 67 of file RNG.cpp.
References mt, mti, and N.
Referenced by RNG().
Member Data Documentation
LOWER_MASK
const unsigned int klee::RNG::LOWER_MASK = 0x7fffffffUL static private
Definition at line 21 of file RNG.h.
Referenced by getInt32().
M
const int klee::RNG::M = 397 static private
Definition at line 18 of file RNG.h.
Referenced by getInt32().
MATRIX_A
const unsigned int klee::RNG::MATRIX_A = 0x9908b0dfUL static private
Definition at line 19 of file RNG.h.
Referenced by getInt32().
mt
unsigned int klee::RNG::mt[N] private
Definition at line 24 of file RNG.h.
Referenced by getInt32(), and seed().
mti
int klee::RNG::mti private
Definition at line 25 of file RNG.h.
Referenced by getInt32(), and seed().
N
const int klee::RNG::N = 624 static private
Definition at line 17 of file RNG.h.
Referenced by getInt32(), and seed().
UPPER_MASK
const unsigned int klee::RNG::UPPER_MASK = 0x80000000UL static private
Definition at line 20 of file RNG.h.
Referenced by getInt32().
The documentation for this class was generated from the following files:
/Users/cristic/klee/include/klee/ADT/RNG.h
/Users/cristic/klee/lib/Support/RNG.cpp