klee: klee::expr::Parser Class Reference
klee::expr::Parser Class Reference abstract
Parser - Public interface for parsing a .kquery language file.
#include <Parser.h>
Public Member Functions
virtual ~Parser ()
virtual void SetMaxErrors (unsigned N)=0
SetMaxErrors - Suppress anything beyond the first N errors.
virtual unsigned GetNumErrors () const =0
GetNumErrors - Return the number of encountered errors.
virtual Decl * ParseTopLevelDecl ()=0
Static Public Member Functions
static Parser * Create (const std::string Name, const llvm::MemoryBuffer *MB, ExprBuilder *Builder, bool ClearArrayAfterQuery)
Protected Member Functions
Parser ()
Detailed Description
Parser - Public interface for parsing a .kquery language file.
Definition at line 206 of file Parser.h.
Constructor & Destructor Documentation
Parser()
Parser::Parser () protected
Definition at line 1642 of file Parser.cpp.
~Parser()
Parser::~Parser () virtual
Definition at line 1645 of file Parser.cpp.
Member Function Documentation
Create()
Parser * Parser::Create (const std::string Name, const llvm::MemoryBuffer * MB, ExprBuilder * Builder, bool ClearArrayAfterQuery) static
CreateParser - Create a parser implementation for the given MemoryBuffer.
Name - The name to use in diagnostic messages.
MB - The input data.
Builder - The expression builder to use for constructing expressions.
Definition at line 1648 of file Parser.cpp.
GetNumErrors()
virtual unsigned klee::expr::Parser::GetNumErrors () const pure virtual
GetNumErrors - Return the number of encountered errors.
Referenced by EvaluateInputAST(), printInputAsSMTLIBv2(), and PrintInputAST().
ParseTopLevelDecl()
virtual Decl * klee::expr::Parser::ParseTopLevelDecl () pure virtual
ParseTopLevelDecl - Parse and return a top level declaration, which the caller assumes ownership of.
Returns
NULL indicates the end of the file has been reached.
Referenced by EvaluateInputAST(), printInputAsSMTLIBv2(), and PrintInputAST().
SetMaxErrors()
virtual void klee::expr::Parser::SetMaxErrors (unsigned N) pure virtual
SetMaxErrors - Suppress anything beyond the first N errors.
Referenced by EvaluateInputAST(), printInputAsSMTLIBv2(), and PrintInputAST().
The documentation for this class was generated from the following files:
/Users/cristic/klee/include/klee/Expr/Parser/Parser.h
/Users/cristic/klee/lib/Expr/Parser.cpp