klee: klee::TreeOStream Class Reference
klee::TreeOStream Class Reference
#include <TreeStream.h>
Public Member Functions
TreeOStream ()
~TreeOStream ()
unsigned getID () const
void write (const char *buffer, unsigned size)
TreeOStream & operator<< (const std::string &s)
void flush ()
Private Member Functions
TreeOStream (TreeStreamWriter &_writer, unsigned _id)
Private Attributes
TreeStreamWriter * writer
unsigned id
Friends
class TreeStreamWriter
Detailed Description
Definition at line 53 of file TreeStream.h.
Constructor & Destructor Documentation
TreeOStream() [1/2]
TreeOStream::TreeOStream (TreeStreamWriter & _writer, unsigned _id) private
Definition at line 170 of file TreeStream.cpp.
TreeOStream() [2/2]
TreeOStream::TreeOStream ()
Definition at line 165 of file TreeStream.cpp.
~TreeOStream()
TreeOStream::~TreeOStream ()
Definition at line 175 of file TreeStream.cpp.
Member Function Documentation
flush()
void TreeOStream::flush ()
Definition at line 194 of file TreeStream.cpp.
References klee::TreeStreamWriter::flush(), and writer.
getID()
unsigned TreeOStream::getID () const
Definition at line 178 of file TreeStream.cpp.
References id, and writer.
Referenced by klee::Executor::getPathStreamID(), and klee::Executor::getSymbolicPathStreamID().
operator<<()
TreeOStream & TreeOStream::operator<< (const std::string & s)
Definition at line 188 of file TreeStream.cpp.
References write(), and writer.
write()
void TreeOStream::write (const char * buffer, unsigned size)
Definition at line 183 of file TreeStream.cpp.
References klee::TreeStreamWriter::write(), and writer.
Referenced by operator<<().
Friends And Related Function Documentation
TreeStreamWriter
friend class TreeStreamWriter friend
Definition at line 54 of file TreeStream.h.
Member Data Documentation
id
unsigned klee::TreeOStream::id private
Definition at line 58 of file TreeStream.h.
Referenced by getID(), klee::TreeStreamWriter::open(), and klee::TreeStreamWriter::write().
writer
TreeStreamWriter* klee::TreeOStream::writer private
Definition at line 57 of file TreeStream.h.
Referenced by flush(), getID(), klee::TreeStreamWriter::open(), operator<<(), and write().
The documentation for this class was generated from the following files:
/Users/cristic/klee/include/klee/ADT/TreeStream.h
/Users/cristic/klee/lib/Support/TreeStream.cpp