klee: CexObjectData Class Reference
CexObjectData Class Reference
Public Member Functions
CexObjectData (uint64_t size)
const CexValueData getPossibleValues (size_t index) const
void setPossibleValues (size_t index, CexValueData values)
void setPossibleValue (size_t index, unsigned char value)
const CexValueData getExactValues (size_t index) const
void setExactValues (size_t index, CexValueData values)
unsigned char getPossibleValue (size_t index) const
getPossibleValue - Return some possible value.
Private Member Functions
CexObjectData (const CexObjectData &)
void operator= (const CexObjectData &)
Private Attributes
std::vector< CexValueData > possibleContents
std::vector< CexValueData > exactContents
Detailed Description
Definition at line 305 of file FastCexSolver.cpp.
Constructor & Destructor Documentation
CexObjectData() [1/2]
CexObjectData::CexObjectData (const CexObjectData &) private
CexObjectData() [2/2]
CexObjectData::CexObjectData (uint64_t size) inline
Definition at line 322 of file FastCexSolver.cpp.
References exactContents, and possibleContents.
Member Function Documentation
getExactValues()
const CexValueData CexObjectData::getExactValues (size_t index) const inline
Definition at line 339 of file FastCexSolver.cpp.
References exactContents.
Referenced by CexData::dump(), and CexData::propogateExactValues().
getPossibleValue()
unsigned char CexObjectData::getPossibleValue (size_t index) const inline
getPossibleValue - Return some possible value.
Definition at line 347 of file FastCexSolver.cpp.
References ValueRange::max(), ValueRange::min(), and possibleContents.
getPossibleValues()
const CexValueData CexObjectData::getPossibleValues (size_t index) const inline
Definition at line 329 of file FastCexSolver.cpp.
References possibleContents.
Referenced by CexData::dump(), and CexData::propogatePossibleValues().
operator=()
void CexObjectData::operator= (const CexObjectData &) private
setExactValues()
void CexObjectData::setExactValues (size_t index, CexValueData values) inline
Definition at line 342 of file FastCexSolver.cpp.
References exactContents.
Referenced by CexData::propogateExactValues().
setPossibleValue()
void CexObjectData::setPossibleValue (size_t index, unsigned char value) inline
Definition at line 335 of file FastCexSolver.cpp.
References possibleContents.
Referenced by CexData::propogatePossibleValues().
setPossibleValues()
void CexObjectData::setPossibleValues (size_t index, CexValueData values) inline
Definition at line 332 of file FastCexSolver.cpp.
References possibleContents.
Referenced by CexData::propogatePossibleValues().
Member Data Documentation
exactContents
std::vector<CexValueData> CexObjectData::exactContents private
exactContents - An array of exact values for the object.
The exact values are a conservative approximation for the set of values for each array location.
Definition at line 316 of file FastCexSolver.cpp.
Referenced by CexObjectData(), getExactValues(), and setExactValues().
possibleContents
std::vector<CexValueData> CexObjectData::possibleContents private
possibleContents - An array of "possible" values for the object.
The possible values is an inexact approximation for the set of values for each array location.
Definition at line 310 of file FastCexSolver.cpp.
Referenced by CexObjectData(), getPossibleValue(), getPossibleValues(), setPossibleValue(), and setPossibleValues().
The documentation for this class was generated from the following file:
/Users/cristic/klee/lib/Solver/FastCexSolver.cpp