klee: klee::StagedSolverImpl Class Reference
klee::StagedSolverImpl Class Reference
#include <IncompleteSolver.h>
Public Member Functions
StagedSolverImpl (IncompleteSolver *_primary, Solver *_secondary)
~StagedSolverImpl ()
bool computeTruth (const Query &, bool &isValid)
bool computeValidity (const Query &, Solver::Validity &result)
bool computeValue (const Query &, ref< Expr > &result)
bool computeInitialValues (const Query &, const std::vector< const Array * > &objects, std::vector< std::vector< unsigned char > > &values, bool &hasSolution)
SolverRunStatus getOperationStatusCode ()
getOperationStatusCode - get the status of the last solver operation
char * getConstraintLog (const Query &)
void setCoreSolverTimeout (time::Span timeout)
Public Member Functions inherited from klee::SolverImpl
SolverImpl ()
virtual ~SolverImpl ()
virtual bool computeValidity (const Query &query, Solver::Validity &result)
virtual bool computeTruth (const Query &query, bool &isValid)=0
virtual bool computeValue (const Query &query, ref< Expr > &result)=0
virtual bool computeInitialValues (const Query &query, const std::vector< const Array * > &objects, std::vector< std::vector< unsigned char > > &values, bool &hasSolution)=0
virtual SolverRunStatus getOperationStatusCode ()=0
getOperationStatusCode - get the status of the last solver operation
virtual char * getConstraintLog (const Query &query)
virtual void setCoreSolverTimeout (time::Span timeout)
Private Attributes
IncompleteSolver * primary
Solver * secondary
Additional Inherited Members
Public Types inherited from klee::SolverImpl
enum SolverRunStatus {
SOLVER_RUN_STATUS_SUCCESS_SOLVABLE , SOLVER_RUN_STATUS_SUCCESS_UNSOLVABLE , SOLVER_RUN_STATUS_FAILURE , SOLVER_RUN_STATUS_TIMEOUT ,
SOLVER_RUN_STATUS_FORK_FAILED , SOLVER_RUN_STATUS_INTERRUPTED , SOLVER_RUN_STATUS_UNEXPECTED_EXIT_CODE , SOLVER_RUN_STATUS_WAITPID_FAILED
}
Static Public Member Functions inherited from klee::SolverImpl
static const char * getOperationStatusString (SolverRunStatus statusCode)
Detailed Description
StagedSolver - Adapter class for staging an incomplete solver with a complete secondary solver, to form an (optimized) complete solver.
Definition at line 88 of file IncompleteSolver.h.
Constructor & Destructor Documentation
StagedSolverImpl()
StagedSolverImpl::StagedSolverImpl (IncompleteSolver * _primary, Solver * _secondary)
Definition at line 61 of file IncompleteSolver.cpp.
~StagedSolverImpl()
StagedSolverImpl::~StagedSolverImpl ()
Definition at line 67 of file IncompleteSolver.cpp.
References primary, and secondary.
Member Function Documentation
computeInitialValues()
bool StagedSolverImpl::computeInitialValues (const Query & query, const std::vector< const Array * > & objects, std::vector< std::vector< unsigned char > > & values, bool & hasSolution) virtual
See also
Solver::getInitialValues()
Implements klee::SolverImpl.
Definition at line 125 of file IncompleteSolver.cpp.
References klee::IncompleteSolver::computeInitialValues(), klee::SolverImpl::computeInitialValues(), klee::Solver::impl, primary, and secondary.
computeTruth()
bool StagedSolverImpl::computeTruth (const Query & query, bool & isValid) virtual
computeTruth - Determine whether the given query expression is provably true given the constraints.
The query expression is guaranteed to be non-constant and have bool type.
This method should evaluate the logical formula:
Where is some assignment, are the constraints in the query and is the query expression.
Parameters
[out] isValid - On success, true iff the logical formula is true.
Returns
True on success
Implements klee::SolverImpl.
Definition at line 72 of file IncompleteSolver.cpp.
References klee::IncompleteSolver::computeTruth(), klee::SolverImpl::computeTruth(), klee::Solver::impl, klee::IncompleteSolver::MustBeTrue, klee::IncompleteSolver::None, primary, and secondary.
computeValidity()
bool StagedSolverImpl::computeValidity (const Query & query, Solver::Validity & result) virtual
computeValidity - Compute a full validity result for the query.
The query expression is guaranteed to be non-constant and have bool type.
SolverImpl provides a default implementation which uses computeTruth. Clients should override this if a more efficient implementation is available.
Parameters
[out] result - if
then Solver::True, else if
then Solver::False, else Solver::Unknown
Returns
True on success
Reimplemented from klee::SolverImpl.
Definition at line 83 of file IncompleteSolver.cpp.
References klee::SolverImpl::computeTruth(), klee::IncompleteSolver::computeValidity(), klee::SolverImpl::computeValidity(), klee::Solver::False, klee::Solver::impl, klee::IncompleteSolver::MayBeFalse, klee::IncompleteSolver::MayBeTrue, klee::IncompleteSolver::MustBeFalse, klee::IncompleteSolver::MustBeTrue, klee::Query::negateExpr(), primary, secondary, klee::Solver::True, klee::IncompleteSolver::TrueOrFalse, and klee::Solver::Unknown.
computeValue()
bool StagedSolverImpl::computeValue (const Query & query, ref< Expr > & result) virtual
computeValue - Compute a feasible value for the expression.
The query expression is guaranteed to be non-constant.
Returns
True on success
Implements klee::SolverImpl.
Definition at line 116 of file IncompleteSolver.cpp.
References klee::IncompleteSolver::computeValue(), klee::SolverImpl::computeValue(), klee::Solver::impl, primary, and secondary.
getConstraintLog()
char * StagedSolverImpl::getConstraintLog (const Query & query) virtual
Reimplemented from klee::SolverImpl.
Definition at line 142 of file IncompleteSolver.cpp.
References klee::SolverImpl::getConstraintLog(), klee::Solver::impl, and secondary.
getOperationStatusCode()
SolverImpl::SolverRunStatus StagedSolverImpl::getOperationStatusCode () virtual
getOperationStatusCode - get the status of the last solver operation
Implements klee::SolverImpl.
Definition at line 138 of file IncompleteSolver.cpp.
References klee::SolverImpl::getOperationStatusCode(), klee::Solver::impl, and secondary.
setCoreSolverTimeout()
void StagedSolverImpl::setCoreSolverTimeout (time::Span timeout) virtual
Reimplemented from klee::SolverImpl.
Definition at line 146 of file IncompleteSolver.cpp.
References klee::Solver::impl, secondary, and klee::SolverImpl::setCoreSolverTimeout().
Member Data Documentation
primary
IncompleteSolver* klee::StagedSolverImpl::primary private
Definition at line 90 of file IncompleteSolver.h.
Referenced by computeInitialValues(), computeTruth(), computeValidity(), computeValue(), and ~StagedSolverImpl().
secondary
Solver* klee::StagedSolverImpl::secondary private
Definition at line 91 of file IncompleteSolver.h.
Referenced by computeInitialValues(), computeTruth(), computeValidity(), computeValue(), getConstraintLog(), getOperationStatusCode(), setCoreSolverTimeout(), and ~StagedSolverImpl().
The documentation for this class was generated from the following files:
/Users/cristic/klee/include/klee/Solver/IncompleteSolver.h
/Users/cristic/klee/lib/Solver/IncompleteSolver.cpp