klee: /Users/cristic/klee/lib/Support/ErrorHandling.cpp File Reference
ErrorHandling.cpp File Reference
#include "klee/Support/ErrorHandling.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Support/CommandLine.h"
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
#include <assert.h>
#include <string.h>
#include <set>
Namespaces
namespace klee
Functions
cl::OptionCategory klee::MiscCat ("Miscellaneous options", "")
static bool shouldSetColor (const char *pfx, const char *msg, const char *prefixToSearchFor)
static void klee_vfmessage (FILE *fp, const char *pfx, const char *msg, va_list ap)
static void klee_vmessage (const char *pfx, bool onlyToFile, const char *msg, va_list ap)
Variables
static const char * warningPrefix = "WARNING"
static const char * warningOncePrefix = "WARNING ONCE"
static const char * errorPrefix = "ERROR"
static const char * notePrefix = "NOTE"
Function Documentation
klee_vfmessage()
static void klee_vfmessage (FILE * fp, const char * pfx, const char * msg, va_list ap) static
Definition at line 57 of file ErrorHandling.cpp.
References errorPrefix, notePrefix, shouldSetColor(), warningOncePrefix, and warningPrefix.
Referenced by klee_vmessage().
klee_vmessage()
static void klee_vmessage (const char * pfx, bool onlyToFile, const char * msg, va_list ap) static
Definition at line 118 of file ErrorHandling.cpp.
References klee::klee_message_file, klee_vfmessage(), and klee::klee_warning_file.
Referenced by klee::klee_error(), klee::klee_message(), klee::klee_message_to_file(), klee::klee_warning(), and klee::klee_warning_once().
shouldSetColor()
static bool shouldSetColor (const char * pfx, const char * msg, const char * prefixToSearchFor) static
Definition at line 46 of file ErrorHandling.cpp.
Referenced by klee_vfmessage().
Variable Documentation
errorPrefix
const char* errorPrefix = "ERROR" static
Definition at line 31 of file ErrorHandling.cpp.
Referenced by klee::klee_error(), and klee_vfmessage().
notePrefix
const char* notePrefix = "NOTE" static
Definition at line 32 of file ErrorHandling.cpp.
Referenced by klee_vfmessage().
warningOncePrefix
const char* warningOncePrefix = "WARNING ONCE" static
Definition at line 30 of file ErrorHandling.cpp.
Referenced by klee_vfmessage(), and klee::klee_warning_once().
warningPrefix
const char* warningPrefix = "WARNING" static
Definition at line 29 of file ErrorHandling.cpp.
Referenced by klee_vfmessage(), and klee::klee_warning().