klee: /Users/cristic/klee/tools/gen-bout/gen-bout.cpp File Reference
gen-bout.cpp File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
#include "klee/ADT/KTest.h"
Macros
#define MAX 64
Functions
static void push_obj (KTest *b, const char *name, unsigned total_bytes, unsigned char *bytes)
static void push_range (KTest *b, const char *name, unsigned value)
void print_usage_and_exit (char *program_name)
int main (int argc, char *argv[])
Macro Definition Documentation
MAX
#define MAX 64
Definition at line 26 of file gen-bout.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 64 of file gen-bout.cpp.
References KTest::args, KTestObject::bytes, kTest_toFile(), MAX, KTestObject::name, KTest::numArgs, KTest::numObjects, KTest::objects, print_usage_and_exit(), push_obj(), push_range(), KTest::symArgvLen, and KTest::symArgvs.
print_usage_and_exit()
void print_usage_and_exit (char * program_name)
Definition at line 50 of file gen-bout.cpp.
Referenced by main().
push_obj()
static void push_obj (KTest * b, const char * name, unsigned total_bytes, unsigned char * bytes) static
Definition at line 27 of file gen-bout.cpp.
References KTestObject::bytes, MAX, KTestObject::name, KTestObject::numBytes, KTest::numObjects, and KTest::objects.
Referenced by main().
push_range()
static void push_range (KTest * b, const char * name, unsigned value) static
Definition at line 39 of file gen-bout.cpp.
References KTestObject::bytes, MAX, KTestObject::name, KTestObject::numBytes, KTest::numObjects, and KTest::objects.
Referenced by main().