klee: /Users/cristic/klee/tools/klee-replay/klee-replay.h File Reference
klee-replay.h File Reference
#include "klee/Config/config.h"
#include "../../runtime/POSIX/fd.h"
#include <sys/time.h>
Macros
#define _LARGEFILE64_SOURCE
#define _FILE_OFFSET_BITS 64
Functions
void replay_create_files (exe_file_system_t *exe_fs)
void replay_delete_files ()
void process_status (int status, time_t elapsed, const char *pfx) __attribute__((noreturn))
Variables
char replay_dir []
int keep_temps
Macro Definition Documentation
_FILE_OFFSET_BITS
#define _FILE_OFFSET_BITS 64
Definition at line 14 of file klee-replay.h.
_LARGEFILE64_SOURCE
#define _LARGEFILE64_SOURCE
Definition at line 13 of file klee-replay.h.
Function Documentation
process_status()
void process_status (int status, time_t elapsed, const char * pfx)
Definition at line 136 of file klee-replay.c.
Referenced by create_char_dev(), create_pipe(), and run_monitored().
replay_create_files()
void replay_create_files (exe_file_system_t * exe_fs)
Definition at line 398 of file file-creator.c.
References __STDIN, __STDOUT, check_file(), create_file(), and replay_dir.
Referenced by main().
replay_delete_files()
void replay_delete_files ()
Definition at line 444 of file file-creator.c.
References keep_temps, remove_callback(), and replay_dir.
Referenced by main().
Variable Documentation
keep_temps
int keep_temps extern
Definition at line 284 of file klee-replay.c.
Referenced by main(), and replay_delete_files().
replay_dir
char replay_dir[] extern
Definition at line 396 of file file-creator.c.
Referenced by check_file(), replay_create_files(), replay_delete_files(), and run_monitored().