klee: /Users/cristic/klee/lib/Expr/Lexer.cpp File Reference
Lexer.cpp File Reference
#include "klee/Expr/Parser/Lexer.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/raw_ostream.h"
#include <iomanip>
#include <string.h>
Functions
static bool isInternalIdentifierChar (int Char)
static bool isReservedKW (const char *Str, unsigned N)
static bool isWidthKW (const char *Str, unsigned N)
Function Documentation
isInternalIdentifierChar()
static bool isInternalIdentifierChar (int Char) inline static
Definition at line 62 of file Lexer.cpp.
Referenced by klee::expr::Lexer::LexIdentifier().
isReservedKW()
static bool isReservedKW (const char * Str, unsigned N) static
Definition at line 109 of file Lexer.cpp.
Referenced by klee::expr::Lexer::SetIdentifierTokenKind().
isWidthKW()
static bool isWidthKW (const char * Str, unsigned N) static
Definition at line 132 of file Lexer.cpp.
Referenced by klee::expr::Lexer::SetIdentifierTokenKind().