klee: klee::ints Namespace Reference
klee::ints Namespace Reference
Functions
uint64_t add (uint64_t l, uint64_t r, unsigned inWidth)
uint64_t sub (uint64_t l, uint64_t r, unsigned inWidth)
uint64_t mul (uint64_t l, uint64_t r, unsigned inWidth)
uint64_t trunc (uint64_t l, unsigned outWidth, unsigned inWidth)
uint64_t zext (uint64_t l, unsigned outWidth, unsigned inWidth)
uint64_t sext (uint64_t l, unsigned outWidth, unsigned inWidth)
uint64_t udiv (uint64_t l, uint64_t r, unsigned inWidth)
uint64_t urem (uint64_t l, uint64_t r, unsigned inWidth)
uint64_t sdiv (uint64_t l, uint64_t r, unsigned inWidth)
uint64_t srem (uint64_t l, uint64_t r, unsigned inWidth)
uint64_t ashr (uint64_t l, uint64_t shift, unsigned inWidth)
uint64_t lshr (uint64_t l, uint64_t shift, unsigned inWidth)
uint64_t shl (uint64_t l, uint64_t shift, unsigned inWidth)
uint64_t land (uint64_t l, uint64_t r, unsigned inWidth)
uint64_t lor (uint64_t l, uint64_t r, unsigned inWidth)
uint64_t lxor (uint64_t l, uint64_t r, unsigned inWidth)
uint64_t eq (uint64_t l, uint64_t r, unsigned inWidth)
uint64_t ne (uint64_t l, uint64_t r, unsigned inWidth)
uint64_t ult (uint64_t l, uint64_t r, unsigned inWidth)
uint64_t ule (uint64_t l, uint64_t r, unsigned inWidth)
uint64_t ugt (uint64_t l, uint64_t r, unsigned inWidth)
uint64_t uge (uint64_t l, uint64_t r, unsigned inWidth)
uint64_t slt (uint64_t l, uint64_t r, unsigned inWidth)
uint64_t sle (uint64_t l, uint64_t r, unsigned inWidth)
uint64_t sgt (uint64_t l, uint64_t r, unsigned inWidth)
uint64_t sge (uint64_t l, uint64_t r, unsigned inWidth)
Function Documentation
add()
uint64_t klee::ints::add (uint64_t l, uint64_t r, unsigned inWidth) inline
Definition at line 25 of file IntEvaluation.h.
References klee::bits64::truncateToNBits().
ashr()
uint64_t klee::ints::ashr (uint64_t l, uint64_t shift, unsigned inWidth) inline
Definition at line 82 of file IntEvaluation.h.
References MAX_BITS, sext(), and klee::bits64::truncateToNBits().
eq()
uint64_t klee::ints::eq (uint64_t l, uint64_t r, unsigned inWidth) inline
Definition at line 113 of file IntEvaluation.h.
land()
uint64_t klee::ints::land (uint64_t l, uint64_t r, unsigned inWidth) inline
Definition at line 98 of file IntEvaluation.h.
lor()
uint64_t klee::ints::lor (uint64_t l, uint64_t r, unsigned inWidth) inline
Definition at line 103 of file IntEvaluation.h.
lshr()
uint64_t klee::ints::lshr (uint64_t l, uint64_t shift, unsigned inWidth) inline
Definition at line 88 of file IntEvaluation.h.
lxor()
uint64_t klee::ints::lxor (uint64_t l, uint64_t r, unsigned inWidth) inline
Definition at line 108 of file IntEvaluation.h.
mul()
uint64_t klee::ints::mul (uint64_t l, uint64_t r, unsigned inWidth) inline
Definition at line 35 of file IntEvaluation.h.
References klee::bits64::truncateToNBits().
ne()
uint64_t klee::ints::ne (uint64_t l, uint64_t r, unsigned inWidth) inline
Definition at line 117 of file IntEvaluation.h.
sdiv()
uint64_t klee::ints::sdiv (uint64_t l, uint64_t r, unsigned inWidth) inline
Definition at line 66 of file IntEvaluation.h.
References MAX_BITS, sext(), and klee::bits64::truncateToNBits().
sext()
uint64_t klee::ints::sext (uint64_t l, unsigned outWidth, unsigned inWidth) inline
Definition at line 50 of file IntEvaluation.h.
References MAX_BITS, and klee::bits64::truncateToNBits().
Referenced by ashr(), ValueRange::maxSigned(), ValueRange::minSigned(), sdiv(), sge(), sgt(), klee::floats::SignedIntToFP(), sle(), slt(), and srem().
sge()
uint64_t klee::ints::sge (uint64_t l, uint64_t r, unsigned inWidth) inline
Definition at line 155 of file IntEvaluation.h.
References MAX_BITS, and sext().
sgt()
uint64_t klee::ints::sgt (uint64_t l, uint64_t r, unsigned inWidth) inline
Definition at line 149 of file IntEvaluation.h.
References MAX_BITS, and sext().
shl()
uint64_t klee::ints::shl (uint64_t l, uint64_t shift, unsigned inWidth) inline
Definition at line 93 of file IntEvaluation.h.
References klee::bits64::truncateToNBits().
sle()
uint64_t klee::ints::sle (uint64_t l, uint64_t r, unsigned inWidth) inline
Definition at line 143 of file IntEvaluation.h.
References MAX_BITS, and sext().
slt()
uint64_t klee::ints::slt (uint64_t l, uint64_t r, unsigned inWidth) inline
Definition at line 137 of file IntEvaluation.h.
References MAX_BITS, and sext().
srem()
uint64_t klee::ints::srem (uint64_t l, uint64_t r, unsigned inWidth) inline
Definition at line 74 of file IntEvaluation.h.
References MAX_BITS, sext(), and klee::bits64::truncateToNBits().
sub()
uint64_t klee::ints::sub (uint64_t l, uint64_t r, unsigned inWidth) inline
Definition at line 30 of file IntEvaluation.h.
References klee::bits64::truncateToNBits().
trunc()
uint64_t klee::ints::trunc (uint64_t l, unsigned outWidth, unsigned inWidth) inline
Definition at line 40 of file IntEvaluation.h.
References klee::bits64::truncateToNBits().
udiv()
uint64_t klee::ints::udiv (uint64_t l, uint64_t r, unsigned inWidth) inline
Definition at line 56 of file IntEvaluation.h.
References klee::bits64::truncateToNBits().
uge()
uint64_t klee::ints::uge (uint64_t l, uint64_t r, unsigned inWidth) inline
Definition at line 133 of file IntEvaluation.h.
ugt()
uint64_t klee::ints::ugt (uint64_t l, uint64_t r, unsigned inWidth) inline
Definition at line 129 of file IntEvaluation.h.
ule()
uint64_t klee::ints::ule (uint64_t l, uint64_t r, unsigned inWidth) inline
Definition at line 125 of file IntEvaluation.h.
ult()
uint64_t klee::ints::ult (uint64_t l, uint64_t r, unsigned inWidth) inline
Definition at line 121 of file IntEvaluation.h.
urem()
uint64_t klee::ints::urem (uint64_t l, uint64_t r, unsigned inWidth) inline
Definition at line 61 of file IntEvaluation.h.
References klee::bits64::truncateToNBits().
zext()
uint64_t klee::ints::zext (uint64_t l, unsigned outWidth, unsigned inWidth) inline
Definition at line 45 of file IntEvaluation.h.