klee: klee::util Namespace Reference
klee::util Namespace Reference
Classes
struct ExprCmp
struct ExprHash
Functions
size_t GetTotalMallocUsage ()
Get total malloc usage in bytes.
Function Documentation
GetTotalMallocUsage()
size_t klee::util::GetTotalMallocUsage ()
Get total malloc usage in bytes.
Definition at line 87 of file MemoryUsage.cpp.
References klee::klee_error().
Referenced by klee::Executor::checkMemoryUsage(), and klee::StatsTracker::writeStatsLine().